### ISSUE TITLE
payment_page_confirm fixture broken in v1.13.7

### ISSUE THREAD

**Issue by relves** [stripe/stripe-cli#1018]
### Issue
Upon upgrade to v1.13.7, it appears the payment_page_confirm fixture is passing a metadata parameter that is not expected by stripe API:
```json
parameter_unknown - metadata
Received unknown parameter: metadata
```

```json
{
  "expected_amount": "3000",
  "payment_method": "...",
  "metadata": {
    "_created_by_fixture": "2023-01-09 23:09:53.280124676 +0000 UTC m=+2.046070586"
  }
}
```

Downgrading to v1.13.6 resolves the issue.

**Comment by gracegoo-stripe** [comment]
This is fixed in v1.13.8, thanks for reporting!
