### ISSUE TITLE
panic: runtime error: slice bounds out of range [:8] with length 0

### ISSUE THREAD

**Issue by agiveygives** [stripe/stripe-cli#1028]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
_Describe what happened and what you were trying to do_

I was switching my config to a new Stripe account, and set the live keys to empty strings. Now I am unable to do anything with the config command. Every command I've tried just errors out.

### Expected Behavior
_Tell us what you expected to happen_

I should _at least_ still be able to edit my config when that value is an empty string.

### Steps to reproduce
_What are the steps we can take to reproduce this and verify it's fixed?_

1. `stripe config --edit`
2. update `live_mode_api_key` and `live_mode_publishable_key` to be `''`
3. save
4. `stripe config --help`

### Traceback
_Share any debug output that was given by the CLI_

```
(!) Livemode value found for the field 'live_mode_api_key' in your config file.
Livemode values from the config file will be redacted and will not be used.
panic: runtime error: slice bounds out of range [:8] with length 0

goroutine 1 [running]:
github.com/stripe/stripe-cli/pkg/config.RedactAPIKey({0x0?, 0xc0001ae008?})
        /Users/runner/work/stripe-cli/stripe-cli/pkg/config/profile.go:388 +0x25f
github.com/stripe/stripe-cli/pkg/config.(*Profile).redactAllLivemodeValues(0x1012d1580)
        /Users/runner/work/stripe-cli/stripe-cli/pkg/config/profile.go:375 +0x185
github.com/stripe/stripe-cli/pkg/config.(*Config).InitConfig(0x1012d1560)
        /Users/runner/work/stripe-cli/stripe-cli/pkg/config/config.go:170 +0x732
github.com/stripe/stripe-cli/pkg/cmd.init.0()
        /Users/runner/work/stripe-cli/stripe-cli/pkg/cmd/root.go:212 +0xb91
```

### Environment
_Select one of: macOS, Linux, Windows, Other_

macOS

**Comment by etsai-stripe** [comment]
issue is resolved in v1.13.11
