### ISSUE TITLE
Allow logs tail to show more detail on error responses

### ISSUE THREAD

**Issue by jwheare** [stripe/stripe-cli#103]
Showing more attributes on error requests would be great when tailing logs:
https://stripe.com/docs/api/errors#errors-type

The string attributes would be handy:

* type
* code (linking to doc_url)
* message
* param
* decline_code
* charge

But leaving out hash attributes (payment_intent, payment_method, setup_intent, source) probably makes sense.

**Comment by ob-stripe** [comment]
Sorry for the very late reply! That's a good suggestion, we'll look into it.

**Comment by ob-stripe** [comment]
Forgot to reply before, but this was implemented in [0.6.11](https://github.com/stripe/stripe-cli/releases/tag/v0.6.11)!
