### ISSUE TITLE
Stripe CLI listed as a virus or PUP by Windows 11

### ISSUE THREAD

**Issue by JBLorincz** [stripe/stripe-cli#1030]
### Issue
I attempted to use the Stripe CLI as documented by Stripe [in the webhook test doc](https://stripe.com/docs/webhooks/test) and the [install Stripe CLI doc](https://stripe.com/docs/stripe-cli). I downloaded the `stripe_1.13.9_windows_x86_64.zip` file [at the mentioned url](https://github.com/stripe/stripe-cli/releases/tag/v1.13.9) per the Windows instructions which contained a stripe.exe file. Upon downloading the zip, I got an error in chrome saying: "This file is not commonly downloaded and is dangerous." I clicked the "keep" button, and extracted the zip. I ran the CLI via a terminal command and logged in via browser. After I logged in, the stripe.exe file disappeared from my machine. I tried re-extracting stripe.exe from the downloaded zip again and I received this popup: 

![errorImage](https://user-images.githubusercontent.com/44126458/218549387-4b0c933e-87d0-4961-8a43-d65d7da3b5ed.png)

### Expected Behavior
_The ability to use Stripe CLI._

### Steps to reproduce

1. Download the Stripe CLI from the above link, as per the Windows Stripe CLI setup docs
2. Extract the zip file
3. open a terminal window and try to use the command `stripe login`
4. Log in
5. Stripe.exe should disappear from it's directory

### Traceback
_Inapplicable as stripe CLI won't even run_

### Environment
_Windows 11_

**Comment by tomer-stripe** [comment]
Hey @JBLorincz! This is unfortunately an issue with the golang compiler itself, check out https://go.dev/doc/faq#virus. We have another issue tracking this but I don't know if we'll actually be able to resolve this because it's at the compiler level https://github.com/stripe/stripe-cli/issues/692. 

Going to close this issue for now!
