### ISSUE TITLE
403 rate limit error seems to ignore when api-key is used

### ISSUE THREAD

**Issue by richardpickett** [stripe/stripe-cli#1031]
### Issue
I get issued a 403 API rate limit exceeded when passing valid api-key, resulting in the api limit itself

### Expected Behavior
Since I'm passing an api key, the server should acknowledge this is an authenticated request, instead of throwing the error that I'm rate limited.

It appears the higher rate limit check isn't being applied to api keys.

### Steps to reproduce
I'm not 100% what initially caused the error, but I don't have any transactions coming through this api key right now, I just set up the service a month ago and it's been running (lit doing nothing) the entire time.

Now when I restart the service, I'm slapped with a rate limit and an error indicating that I'm not authenticated, even though I'm passing a valid key (it connected for a month straight).

### Environment
Linux

### Traceback

```
stripe listen --log-level debug --api-key ${STRIPE_API_KEY} --forward-to http://localhost:3000/webhooks/stripe/
⣾ Checking for new versions...[Mon, 13 Feb 2023 23:15:49 UTC] DEBUG GET https://api.github.com/repos/stripe/stripe-cli/releases/latest: 403 API rate limit exceeded for 23.92.17.172. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 51m11s]
[Mon, 13 Feb 2023 23:15:49 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready...[Mon, 13 Feb 2023 23:15:50 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⢿ Getting ready...[Mon, 13 Feb 2023 23:15:51 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣟ Getting ready...[Mon, 13 Feb 2023 23:15:52 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣷ Getting ready...[Mon, 13 Feb 2023 23:15:53 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready...[Mon, 13 Feb 2023 23:15:54 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
[Mon, 13 Feb 2023 23:15:55 UTC] FATAL Error while authenticating with Stripe: Post "https://api.stripe.com/v1/stripecli/sessions": net/http: invalid header field value for "Authorization"
```

**Comment by Issalena2k23** [comment]
stripe listen --log-level debug --api-key ${STRIPE_API_KEY} --forward-to http://localhost:3000/webhooks/stripe/
⣾ Checking for new versions...[Mon, 13 Feb 2023 23:15:49 UTC] DEBUG GET https://api.github.com/repos/stripe/stripe-cli/releases/latest: 403 API rate limit exceeded for 23.92.17.172. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 51m11s]
[Mon, 13 Feb 2023 23:15:49 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready...[Mon, 13 Feb 2023 23:15:50 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⢿ Getting ready...[Mon, 13 Feb 2023 23:15:51 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣟ Getting ready...[Mon, 13 Feb 2023 23:15:52 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣷ Getting ready...[Mon, 13 Feb 2023 23:15:53 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready...[Mon, 13 Feb 2023 23:15:54 UTC] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
[Mon, 13 Feb 2023 23:15:55 UTC] FATAL Error while authenticating with Stripe: Post "https://api.stripe.com/v1/stripecli/sessions": net/http: invalid header field value for "Authorization"

**Comment by gracegoo-stripe** [comment]
Hi @richardpickett, the API limit error is a benign error from the CLI trying to check if there's a new version available on github. 

Can you try logging into the CLI `stripe login` and rerunning the command without the `--api-key` flag? I'm curious to see if this is an issue with the key. Running login with generate another restricted key for the CLI.

**Comment by richardpickett** [comment]
I'm closing the issue.  It turns out when the key was loaded in our environment, it's base64 encoded, and was accidentally encoded with the new-line character on the end, so the cli was technically using the wrong key when connecting.
