### ISSUE TITLE
[Docker] Striple CLI does not persist data between executions. (Possibly a question)

### ISSUE THREAD

**Issue by SmashingQuasar** [stripe/stripe-cli#1034]
### Issue
So the container is working just fine (props to you guys for making it this convenient), however we encounter an inconvenience with it.
Like many other companies, when we down a docker-compose project, we actually destroy all containers.
Because of that, every time we up our project, we need to re-authorize the Stripe CLI through the web interface. This is problematic because it creates a lot of unnecessary noise and work for our developers.

### Expected Behavior
I am not sure this is possible, hence the (Possibly a question) within the title.
We would like to persist the authorization between executions. I believe this can be achieved through a dynamic volume within our docker-compose.yml. I do not know however what to persist.
If this is not currently possible (e.g. the authorization is being stored in memory) then this is more of a bug report (in my opinion, feel free to classify it as you see fit).

### Steps to reproduce
The reproduction is pretty simple. All you need to do is up a Docker project with the stripe-cli attached as a service and down it. When re-uping it, you will need to authorize the CLI again.

### Environment
This has been tested with docker-compose v2.x, Docker 20.10.x on Debian 11.

Thanks again for providing a docker container for this CLI. It makes life much easier when working with Stripe.

**Comment by tomer-stripe** [comment]
Hey @SmashingQuasar! Sorry for the delay. So I think this isn't specific to the CLI itself but rather that Docker containers don't explicitly persist data inside of them.

You're on the right track here -- you want [volumes](https://docs.docker.com/storage/volumes/) or [bind mounts](https://docs.docker.com/storage/bind-mounts/) for Docker container. With that, you'd want to auth the CLI on your local device and point the container volume or mount to wherever that auth is stored. On your local device we generally store the config file with your auth in `~/.config/stripe/config.toml` (mentioned [here](https://stripe.com/docs/cli/login))

Here's some pseudocode for what I think it'd look like (apologies in advance if this doesn't work right):
```
services:
  stripecli:
    ...
    volumes:
      - ~./.config/stripe/config.toml:/app/stripe.toml
    command: stripe --config /app/stripe.com listen
```

The CLI has a global flag `--config` that you can use to override our defaults. Alternatively, you can also override the `XDG_CONFIG_HOME` if you want some extra control over the entire config directory.

Hope this helps!

**Comment by SmashingQuasar** [comment]
Thanks for the answer!

> So I think this isn't specific to the CLI itself but rather that Docker containers don't explicitly persist data inside of them.

Yep, that was my point, sorry if I didn't make it clear. I know Docker containers don't persist data without volumes. :)

> With that, you'd want to auth the CLI on your local device and point the container volume or mount to wherever that auth is stored. On your local device we generally store the config file with your auth in ~/.config/stripe/config.toml (mentioned [here](https://stripe.com/docs/cli/login))

Alright, I think that's what I actually need. That means the `.toml` file is what contains the authorization from the web ui, correct?

I noticed you wrote ` --config /app/stripe.com` in your Docker command. What is the `stripe.com` file? (I assume it's a file given the path)

**Comment by tomer-stripe** [comment]
Oops, the `stripe.com` file was a typo on my part, I meant for that to be `stripe.toml`. But yea, the `.toml` file is where all the auth from the UI login flow is stored.

Fixed here:
```
services:
  stripecli:
    ...
    volumes:
      - ~./.config/stripe/config.toml:/app/stripe.toml
    command: stripe --config /app/stripe.toml listen
```

**Comment by SmashingQuasar** [comment]
Ok, thanks, I'm going to give this a go!

I'll close this issue since it seems resolved and if I get into any more trouble I'll simply reopen it.

Thanks a lot for your help and your super fast response! 👍
