### ISSUE TITLE
Allow forwarding to endpoints with a self signed certificate

### ISSUE THREAD

**Issue by robertboloc** [stripe/stripe-cli#108]
### Problem
We use a self signed SSL certificate for our API when developing locally. When trying to forward requests to an endpoint on that API we get an error because the SSL certificate is not valid.

### Feature
It would be useful to have a flag that allows ignoring the certificate check. I suspect a lot of other developers use a similar setup.

### Examples
`ERROR Failed to POST event to local endpoint, error = Post https://api.local/stripe: x509: certificate signed by unknown authority`

**Comment by ob-stripe** [comment]
👍 Great suggestion! Will try to add it soon.

**Comment by cayman1066** [comment]
Thanks for the suggestion, @robertboloc.  I just installed the Stripe CLI and suspected even before I put it into listen mode that I'd have the same problem.  And thanks for taking this up, @ob-stripe

**Comment by ob-stripe** [comment]
I've just released 0.4.5, which adds a `--skip-verify` flag the `listen` command. When the flag is present, the CLI will no longer attempt to validate certificates when forwarding an event to an HTTPS endpoint.

**Comment by cayman1066** [comment]
Sweet!  That was quick.  Thanks, Olivier!  Upgrading now...

**Comment by cayman1066** [comment]
Works beautifully.  Thanks for the quick turn around, @ob-stripe !

**Comment by ob-stripe** [comment]
You're welcome! 🎉

**Comment by robertboloc** [comment]
Thank you @ob-stripe works as expected.

**Comment by archisvaze** [comment]
> I've just released 0.4.5, which adds a `--skip-verify` flag the `listen` command. When the flag is present, the CLI will no longer attempt to validate certificates when forwarding an event to an HTTPS endpoint.

Thanks!

**Comment by noelbank00** [comment]
> I've just released 0.4.5, which adds a `--skip-verify` flag the `listen` command. When the flag is present, the CLI will no longer attempt to validate certificates when forwarding an event to an HTTPS endpoint.

Thank you! 🙏🏻
