### ISSUE TITLE
stripe trigger charge.succeeded `--add` will not add metadata

### ISSUE THREAD

**Issue by ArbiterOfBuffoonery** [stripe/stripe-cli#1113]
### Issue
When I execute the command
```shell
stripe trigger charge.succeeded --add 'charge:metadata[is_something]=true' --add 'charge:metadata[anotherValue]=the_value'
```
The resulting webhook does not contain any metadata.

### Expected Behavior
When I was testing around the may/june timeframe, the above command would result in 2 metadata keys in the map.

### Steps to reproduce
- Run a local webhook listener
- Start `stripe listen --latest --forward-to <the local webhook listener>`
- trigger via `stripe trigger charge.succeeded --add 'charge:metadata[is_something]=true' --add 'charge:metadata[anotherValue]=the_value'`
- listener fires, but the metadata field is empty.

### Traceback
_Share any debug output that was given by the CLI_

### Environment
Linux (Ubuntu 22.04.3 LTS)

**Comment by etsai-stripe** [comment]
i just ran the same command and was able to see the two added keys in the map
could you please try again?

**Comment by ArbiterOfBuffoonery** [comment]
When I view the dashboard I still don't see an entries for the metadata

**Comment by etsai-stripe** [comment]
@ArbiterOfBuffoonery 
ah! the api has been changed here https://github.com/stripe/stripe-cli/pull/1106/files
please change your command to 
`$ stripe trigger charge.succeeded --add 'payment_intent:metadata[is_something]=true' --add 'payment_intent:metadata[anotherValue]=the_value'`

i have verified this on v1.18.0
