### ISSUE TITLE
stripe listen issues get request

### ISSUE THREAD

**Issue by bodgerbarnett** [stripe/stripe-cli#114]
When I use stripe listen locally, it works fine.

But when I use it on our test server, the webhooks seem to call GET, rather than POST and my webhook is not set up to serve GET requests:-

    [Fri, 16 Aug 2019 16:49:56 BST]  INFO Received event: evt_1F87geDLZTy5tB2lWSjs3aI0 [type: checkout.session.completed]
    [Fri, 16 Aug 2019 16:49:56 BST]  INFO Got response from local endpoint, status=405

and in my internal logs:-

    [pid: 1091|app: 0|req: 3/9] 192.168.100.52 () {44 vars in 875 bytes} [Fri Aug 16 16:49:56 2019] GET /prices/payment_received/ => generated 0 bytes in 4 msecs (HTTP/1.1 405) 5 headers in 159 bytes (2 switches on core 0)

Is this expected behaviour and I should handle the GET requests? Or is something else going on?

**Comment by ob-stripe** [comment]
Hi @bodgerbarnett, thanks for the report. That's really surprising though, the CLI is only supposed to send POST requests to local endpoints, not GET. There must be something else going on here, but I'm not sure what that could be.

**Comment by tomer-stripe** [comment]
@bodgerbarnett that's pretty odd... out of curiosity, what version are you running in both systems? Could you also share the exact commands you're running to invoke the CLI? I want to see if I can reproduce it.

**Comment by bodgerbarnett** [comment]
@tomer-stripe Apologies, for some reason, it didn't occur to me at all that I could just the Stripe test site's webhooks to send data to my test site and therefore don't really need the Stripe CLI for this.

If you still want to try and reproduce it, here is the info you need:-

stripe version 0.5.1 (beta)
stripe listen --forward-to <test site url>

This was all running on the test site server itself.

**Comment by ob-stripe** [comment]
@bodgerbarnett Can you check if any of the following environment variables is set?

- `HTTP_PROXY`
- `http_proxy`
- `HTTPS_PROXY`
- `https_proxy`

**Comment by bodgerbarnett** [comment]
@ob-stripe No, none of those are set.

**Comment by ob-stripe** [comment]
I'm closing this thread as we were never able to reproduce the issue. Event forwarding by the CLI should always be done as POST requests: https://github.com/stripe/stripe-cli/blob/4d6778bd806c828612462d9dfcd421231bfe60f7/pkg/proxy/endpoint.go#L83

Something in your environment must be proxying as GET, but I really don't know what it could be.

Feel free to reply if you can provide more information to help us reproduce the issue and we'll reopen.

**Comment by tomer-stripe** [comment]
@bodgerbarnett out of curiosity, what was the forward url you were using?
