### ISSUE TITLE
Can't install via homebrow due to Github password request

### ISSUE THREAD

**Issue by stevage** [stripe/stripe-cli#1146]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue

```
$ brew install stripe/clipe-cli/stripe
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
helm-docs                                                                                                    sui
==> New Casks
lunarbar

You have 15 outdated formulae installed.

==> Tapping stripe/clipe-cli
Cloning into '/opt/homebrew/Library/Taps/stripe/homebrew-clipe-cli'...
Username for 'https://github.com': stevage
Password for 'https://stevage@github.com':
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/stripe/homebrew-clipe-cli/'
Error: Failure while executing; `git clone https://github.com/stripe/homebrew-clipe-cli /opt/homebrew/Library/Taps/stripe/homebrew-clipe-cli --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

### Environment

macOS Ventura 13.6.3 on 2023 MBP

Git is otherwise setup fine with SSH keys for Github, and I can do this for instance:

```
$ git clone https://github.com/stripe/stripe-cli
Cloning into 'stripe-cli'...
remote: Enumerating objects: 5690, done.
...
```

I don't know what else to report. It seems a bit unnecessary to even require a `git clone` here - aren't there ways to download the code that don't require a Github user account?

**Comment by tomer-stripe** [comment]
Hey @stevage! Sorry for the delay -- are you still having issues? This generally surfaces if you have a specific git configuration or login setup for GitHub. Homebrew clones from git under the hood so that part is standard. We aren't seeing any requirements for passwords on our side.

**Comment by stevage** [comment]
Sorry, I was able to resolve it somehow, but I don't remember how!

**Comment by tomer-stripe** [comment]
All good, glad it's working now!

**Comment by tps-80** [comment]
I had the same error and figured out that we both mistyped the command.  
In your code posted above you have 

> brew install stripe/clipe-cli/stripe
where it should be 
> brew install stripe/stripe-cli/stripe
