### ISSUE TITLE
Offer a commit and rollback for events triggered by stripe cli in test 

### ISSUE THREAD

**Issue by VaZark** [stripe/stripe-cli#1147]
### Problem

When running automated E2E tests, elements created (customer, subscription, etc) persist after the tests and make the test dashboard extremely noisy when the non-dev users wish to test features or ideas in the test environment (related : #707)

### Feature

There could be multiple ways to do this, 

1. Having a unique key generated for each "TestSession" that is attached for the elements so it can be bulk deleted by passing something like `clear_test_data(test_session_id)`
2. Something that imitates the SQL transaction rollback so that the elements created during a test are deleted after a run ( `start_test_transaction` & `rollback_test_transaction` ) or after a fixed period for events triggered by cli directly(1-24hrs)

**Comment by tomer-stripe** [comment]
Hey @VaZark! This is a good idea and I'll pass it on to the team that owns these flows. I'm going to close this issue since it's outside of our scope (we'd need a lot of support from the API itself).
