### ISSUE TITLE
Can't run apps plugin

### ISSUE THREAD

**Issue by rampion** [stripe/stripe-cli#1149]
### Issue

After installing the `apps` plugin via `stripe plugin install apps`, I can't run it via `stripe apps`.

### Expected Behavior

Just following [the instructions to get set up as a developer per the documentation](https://stripe.com/docs/stripe-apps/create-app#install-stripe-apps-cli), I expected to be able to see the version.

### Steps to reproduce and traceback

Looking at the debug logs reveals that it can't find the `~/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps` file:

```
➤ docker run --rm --entrypoint /bin/sh -it stripe/stripe-cli:latest
/ # stripe login
Your pairing code is: XXX-XXX-XXX-XXX
This pairing code verifies your authentication with Stripe.
To authenticate with Stripe, please go to: https://dashboard.stripe.com/stripecli/confirm_auth?t=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Done! The Stripe CLI is configured for your account with account id acct_XXXXXXXXXXXXXXXX
Please note: this key will expire after 90 days, at which point you'll need to re-authenticate.
/ # stripe plugin install apps
✔ installation complete.
/ # stripe apps -v || echo "uh-oh"
uh-oh
```

The file exists and is executable:

```
/ # apk add file
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libmagic (5.45-r1)
(2/2) Installing file (5.45-r1)
Executing busybox-1.36.1-r15.trigger
OK: 16 MiB in 18 packages
/ # ls -l /root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps 
-rwxr-xr-x    1 root     root      33955733 Feb 12 19:36 /root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps
/ # file /root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps 
/root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=xN-u73T
H6e0AuaVgqGzM/XRL0NIpJtoTGP-x-GwUX/jqkxgmE8kUMDaJRm8Ajz/I7Us6muVU6PWmYWcFH1Z, with debug_info, not stripped
```

Trying to run it directly recreates the "not found" error reported in `stripe apps`'s debug log:

```
/ # /root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps
/bin/sh: /root/.config/stripe/plugins/apps/1.5.14/stripe-cli-apps: not found
```

### Environment

I'm on linux machine running NixOS 23.11. In addition to using the docker container, I've run into this same issue when using `stripe` 
- installed via the system package manager
- installed from the github tarfile

The issue doesn't seem to be account-specific, as I can successfully install and run `stripe apps -v` on my OSX box.

### See also

[Support thread on discord](https://discord.com/channels/841573134531821608/841573134531821616/1206637541923749988).

**Comment by fkuo-stripe** [comment]
Hi @rampion, we've identified an issue where the Stripe Apps plugin binary was being built as a dynamic binary for amd64 architectures and would fail to start. Version 1.5.16 of the plugin should resolve the issue, please give it a try and let us know if you run into problems.

**Comment by rampion** [comment]
Works perfectly with 1.5.16, thanks!
