### ISSUE TITLE
[trigger] [payment_intent.succeeded] No Invoice and Subscription Fixtures 

### ISSUE THREAD

**Issue by aress31** [stripe/stripe-cli#1211]
Does anyone know why essentials `invoice` and `subscription` are not yet supported when triggering the `payment_intent.succeeded` event with the `cli` for testing purposes, see:

- `payment_intent:invoice`:

  ```bash
  ❯ .\stripe.exe trigger payment_intent.succeeded --add payment_intent:invoice=foo
  Setting up fixture for: payment_intent
  Running fixture for: payment_intent
  Trigger failed: Request failed, status=400, body={
    "error": {
      "code": "parameter_unknown",
      "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
      "message": "Received unknown parameter: invoice",
      "param": "invoice",
      "request_log_url": "https://dashboard.stripe.com/test/logs/req_REDACTED?t=1719355447",
      "type": "invalid_request_error"
    }
  }
  ```

- `payment_intent:subscription`:

  ```bash
  ❯ .\stripe.exe trigger payment_intent.succeeded --add payment_intent:subscription=foo
  Setting up fixture for: payment_intent
  Running fixture for: payment_intent
  Trigger failed: Request failed, status=400, body={
    "error": {
      "code": "parameter_unknown",
      "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
      "message": "Received unknown parameter: subscription. Did you mean description?",
      "param": "subscription",
      "request_log_url": "https://dashboard.stripe.com/test/logs/req_REDACTED?t=1719355476",
      "type": "invalid_request_error"
    }
  }
  ```

**Comment by karlr-stripe** [comment]
Hi @aress31 , the `trigger` command just makes some calls to the Stripe API which have the side effect of producing the requested event type. The [`-add` parameter ](https://docs.stripe.com/cli/trigger#trigger-add)is used to add an additional parameter to those API requests. So if you add something that the API does not support(there's so much thing as passing `invoice=in_xxx` to the [PaymentIntent Create API](https://docs.stripe.com/api/payment_intents/create) you just get an error.

If you want a PaymentIntent with the `invoice` field set, the **only** way to do that is to create and finalize a non-zero Invoice. So the easiest option really is just to do `stripe trigger invoice.paid` as that also has the side effect of emitting a `payment_intent.succeeded` event. 

On the other point, there is not such thing as a `subscription` field on the PaymentIntent object so I'm unsure what you're aiming for there.

**Comment by aress31** [comment]
That’s why I reported this as a bug. The invoice object/ID is fully supported by the `paymentIntent` object, as clearly stated in the documentation. See the details here:

- https://docs.stripe.com/api/payment_intents/object

![image](https://github.com/stripe/stripe-cli/assets/11601622/4cee988e-7b27-47ea-a76f-6163f4e01c84)

**Comment by karlr-stripe** [comment]
@aress31 It's supported as a _field_ , not a _parameter_. A PaymentIntent can have a field `invoice` which is the ID of the invoices it's related to. It does not have a parameter that can be set to assign a value to that field. The only way that field can be set is by having the PaymentIntent get created by an Invoice, as described in my reply. Stripe-CLI can not set that field in any way except by what the public API supports.

If you have more questions about how the Stripe API works I'd suggest reaching out to to https://stripe.com/go/developer-chat or https://support.stripe.com/?contact=true.

**Comment by aress31** [comment]
That is exactly my point. This should be supported because the normal `checkout flow` generates a `paymentIntent` with an `invoice` set - so for development purposes this behaviour should ideally get replicated with the `trigger`.

Also, to avoid confusion, it would be helpful if the documentation explicitly distinguished between fields and parameters.

**Comment by karlr-stripe** [comment]
It depends what you mean by the "normal" Checkout flow, there are multiple ways of integrating payments in Stripe. There's really only two or three that actually set `invoice` on PaymentIntent(creating Subscriptions, using the Invoicing integration, using post-payment invoices on Checkout), while all of the default one-time integrations of https://stripe.com/docs/payments/accept-a-payment for instance , do not create Invoices at all.

so for development purposes this behaviour should ideally get replicated with the trigger.

I mentioned that `stripe trigger invoice.paid` will generate a `payment_intent.succeeded` event that does have `invoice` set, I hope that helps as a workaround!

Again, this is less about stripe-cli so I'd suggest reaching out to to https://stripe.com/go/developer-chat or https://support.stripe.com/?contact=true for any further clarification.

**Comment by aress31** [comment]
@karlr-stripe, I am trying your workaround and the fixtures still do not seem to apply, see:

- Triggering an `invoice.paid` event with a set `customer` and `invoice`:

  ```powershell
  ./stripe.exe trigger invoice.paid --add payment_intent:customer=cus_QMPm8fmp1p6Xgf --add payment_intent:invoice=in_1PVgxNAotHECEdB6z8ZLO0c6
  ```

- On the handler side, you can observe discrepancies in the id.

  ```js
  console.log({ customerId: customer.id, invoiceId: invoice.id });
  
  {
    customerId: 'cus_QMdQGtGKb5kHD3',
    invoiceId: 'in_1PVuA1AotHECEdB6eFwtQ21t'
  }
  ```

**Comment by karlr-stripe** [comment]
Please reach out to https://stripe.com/go/developer-chat or https://support.stripe.com/?contact=true for usage questions.

To unblock you for now:
It's just `trigger invoice.paid  --override invoice:customer=cus_QMPm8fmp1p6Xgf`
because:
- To set fields on the PaymentIntent, you set them on the _Invoice_ not the PaymentIntent, since the Invoice 'creates' the PaymentIntent and the values inherit down.
- `-add`  is to add _additional parameters_ to the [requests that fixture makes](https://github.com/stripe/stripe-cli/blob/8b81e5834d325ab137144b084fd9e433e3e43db4/pkg/fixtures/triggers/invoice.paid.json#L34-L41), but it _already_ includes a `customer` parameter so `-add` is ignored. So instead you want `--override` to change the value it passes.
- `--add payment_intent:invoice=in_1PVgxNAotHECEdB6z8ZLO0c6` doesn't make sense, since you can't control the Invoice ID here. What happens is the fixture calls the API to create a new Invoice(which will have a new random ID), that Invoice creates a PaymentIntent, and that PaymentIntent has the `id` of that invoice for it's `invoice` field.
