### ISSUE TITLE
stripe listen does not log when it cannot create a websocket connection

### ISSUE THREAD

**Issue by danielpeach** [stripe/stripe-cli#156]
### Issue
I'm not sure why `stripe listen` isn't working - maybe the endpoint is down or I've made a mistake (it was working earlier with no changes on my end). 

Regardless, it's super confusing that the CLI says "Ready! Your webhook signing secret..." when in fact the CLI is silently dialing the websocket endpoint and repeatedly failing.

### Expected Behavior
I expected the `stripe listen` to log its connection failures / retries (without having to run the command with `--log-level=debug`).

### Steps to reproduce
Run `stripe listen` in such a way that it authenticates properly but can't create a websocket connection to stripe-cli.stripe.com.

### Traceback
```
stripe listen --forward-to localhost:4000/webhooks/stripeaccountupdated --print-json --log-level debug
⣾ Getting ready... [Tue, 10 Sep 2019 20:42:17 EDT] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⡿ Getting ready... [Tue, 10 Sep 2019 20:42:27 EDT] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe display_connect_filter_warning=false reconnect_delay=36 websocket_authorized_feature=webhook-payloads websocket_id={ws-id}websocket_url=wss://stripe-cli.stripe.com/subscribe/{account}
[Tue, 10 Sep 2019 20:42:27 EDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
> Ready! Your webhook signing secret is {secret} (^C to quit)
[Tue, 10 Sep 2019 20:42:27 EDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/{account}?websocket_feature=webhook-payloads
[Tue, 10 Sep 2019 20:42:37 EDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Tue, 10 Sep 2019 20:42:37 EDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
[Tue, 10 Sep 2019 20:42:47 EDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/{account}?websocket_feature=webhook-payloads
[Tue, 10 Sep 2019 20:42:57 EDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Tue, 10 Sep 2019 20:42:57 EDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
^C[Tue, 10 Sep 2019 20:43:00 EDT] DEBUG proxy.Proxy.Run: Ctrl+C received, cleaning up...
[Tue, 10 Sep 2019 20:43:00 EDT] DEBUG proxy.Proxy.Run: Bye!
```

### Environment
macOS

**Comment by tomer-stripe** [comment]
@danielpeach thanks for this! I started looking into a better way to display the status without completely filling your screen with reconnect attempts (which happen a lot, we didn't want to drown out the webhooks data). I don't have anything solid at the moment but I'm going to keep working on this.

I'm not sure why you can't connect to the websocket though, let me see if I can find the errors on our side.

**Comment by ob-stripe** [comment]
Hey @danielpeach, sorry for the late reply here. We've made some improvements to the CLI, and as of v0.7.6 it should no longer display the "Ready" message before the websocket connection is actually established.

**Comment by danielpeach** [comment]
awesome, thank you!
