### ISSUE TITLE
Password needed to run Stripe CLI ?

### ISSUE THREAD

**Issue by mo** [stripe/stripe-cli#157]
```
$ docker run --rm -it stripe/stripe-cli version
Unable to find image 'stripe/stripe-cli:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/stripe/stripe-cli/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

Why do I need a password to fetch the Stripe CLI image? What kind of password do I need? Can you add some instructions around this to the readme? Thanks.

**Comment by mo** [comment]
hmm, seems I had an expired docker hub auth token in ~/.docker/config.json (after changing the password via their web UI when there were hacked in april this year) ... anyway, after running ```docker logout``` it worked again.

**Comment by ob-stripe** [comment]
Glad you were able to fix it :)
