### ISSUE TITLE
please add customer_id to customer.source.expiring event

### ISSUE THREAD

**Issue by rotorboy** [stripe/stripe-cli#163]
While I understand the appeal of ONLY sending the "leaf element" object id of the event,  as a "best practice" principle, any "element" included the event type path should have its corresponding ID included in the object sent. So in this event case, the event object would ideally include a cus_id AND a src_id included. Currently, only a src_id is being sent. 

Our service doesn't hold or track src_id's in our database (no reason to), only a cus_id. The lack of a cus_id in the object prevents me from being able to determine WHICH of our customers has a source expiring, so I'm unable to send them an alert, so this event serves no purpose as I’m unable to determine without going through each customer I have to see which customers source is expiring. 

Please add the ID of each enclosed object element. Thanks

**Comment by ob-stripe** [comment]
Hi @rotorboy. The object nested in [`customer.source.expiring`](https://stripe.com/docs/api/events/types#event_types-customer.source.expiring) events is a [`card`](https://stripe.com/docs/api/cards) object, and cards should always have a non-null [`customer`](https://stripe.com/docs/api/cards/object#card_object-customer) attribute.

In any case, we can't help you here -- events are formatted by Stripe's backend API, not the CLI. If you have questions or suggestions about event formatting, you should reach to Stripe's support at https://support.stripe.com/email.

Closing, but feel free to reply if you believe there's something the CLI could do here!
