### ISSUE TITLE
NCBKSAJE

### ISSUE THREAD

**Issue by 0506569966** [stripe/stripe-cli#164]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
_Describe what happened and what you were trying to do_

### Expected Behavior
_Tell us what you expected to happen_

### Steps to reproduce
_What are the steps we can take to reproduce this and verify it's fixed?_

### Traceback
_Share any debug output that was given by the CLI_

### Environment
_Select one of: macOS, Linux, Windows, Other_

**Comment by ob-stripe** [comment]
I'm assuming this issue was opened by mistake. Feel free to reply if that's not the case.
