### ISSUE TITLE
Trigger request

### ISSUE THREAD

**Issue by clavaque** [stripe/stripe-cli#196]
### Problem
_What are you trying to do?_

I'm trying to test a webhook endpoint's event handlers. The plugin I'm updating to the latest API has only a few of them, but just one is supported in the current CLI: 

- invoice.payment_succeeded

### Feature
_What would help you accomplish your original task_

I was wondering if you are planning to add any of these soon? 

- invoice.payment_failed
- customer.deleted
- customer.subscription.deleted
- charge.refunded
- charge.dispute.created

Or is there any way for the "Send Test Webhook" tool in the dashboard, to use actual objects from previous tests or made-up ones, that the handler could then retrieve or update? 

Thanks for all your work! :)

**Comment by tomer-stripe** [comment]
Hey @clavaque! I'm going to ticket these on our side and see if we can do some of these quick (I think a few might be easy to do).

Out of curiosity, which plugin are you working on?

**Comment by tomer-stripe** [comment]
@clavaque was able to add all of them! They're in v0.6.8 if you want to upgrade to that.
