### ISSUE TITLE
charge.refunded webhook support

### ISSUE THREAD

**Issue by tdarnett** [stripe/stripe-cli#198]
### Problem
Trying to test `charge.refunded` webhooks with the CLI but it is not supported as of now. 

### Feature
Support for `charge.refunded` events in the CLI. Providing a way to specify the charge_id you want it to attach to, and a refund amount to test it with would be amazing.

**Comment by tomer-stripe** [comment]
Hey @tdarnett! #196 will add a `charge.refunded` trigger but not the ability to set the charge_id to refund or the amount.

You could use the `stripe refunds create` commands to do that though:

```
$ stripe refunds create charge=ch_1EOA8IByst5pquEteSXgXjj0 amount=100
```
