### ISSUE TITLE
ERROR read error: websocket: unexpected reserved bits 0x40

### ISSUE THREAD

**Issue by bz-stripe** [stripe/stripe-cli#217]
### Issue
When listening to webhooks, there's occasional error messages

### Expected Behavior
Expect to only see messages related to webhook events

### Steps to reproduce
`$ stripe listen`

### Traceback
`ERROR read error: websocket: unexpected reserved bits 0x40`

### Environment
macOS 10.14.6

**Comment by ob-stripe** [comment]
This specific error is a known issue when using the CLI against our devboxes (I think one of the proxies between the CLI and the service running on the devbox might not fully websocket-compliant), but I agree we shouldn't be reporting these non-fatal errors (or just reporting them as debug messages).

**Comment by tomer-stripe** [comment]
Just merged a branch that will move these to debug statements. Since it doesn't seem like it's impacting functionality I'm leaning on closing this for now. What do you think?

**Comment by bz-stripe** [comment]
Yup, closed
