### ISSUE TITLE
Creating issuing_authorization.* events 

### ISSUE THREAD

**Issue by alucic** [stripe/stripe-cli#218]
### Problem
I'd like to use `stripe-cli` to help me with end to end testing of `issuing` webhooks.

I'd like to be able to trigger issuing events:
- `issuing_authorization.request`
- `issuing_authorization.created`
- `issuing_authorization.updated` 

### Feature
I'd like to be able to trigger hooks on a connected account so I can test different use cases like:
- approving/declining authorizations
- reversed authorization in USD and non-USD currency
- updated authorization when a business reduces the amount of funds requested 
- authorizations that are not USD

I'm not sure if this is the right way to approach it, any help is appreciated.

I was thinking of creating a new authorization but the API doesn't have an endpoint to do so
https://stripe.com/docs/api/issuing/authorizations

I guess a simple test case would be:
1. create a new authorization
2. `issuing_authorization.request` event gets triggered 
3. event is forwarded using `stripe-cli` to a local instance
4. authorization gets approved and I do check my expectations

Thanks!

### Examples
```
➜  stripe trigger issuing_authorization.updated
event issuing_authorization.updated is not supported.
```

Just an example to show cli is setup correctly
```
➜  stripe get /issuing/cardholders --stripe-account acct_***
{
  "object": "list",
  "data": [

  ],
  "has_more": false,
  "url": "/v1/issuing/cardholders"
}
```
```
➜  stripe trigger payment_intent.created
Trigger succeeded! Check dashboard for event details.
```

**Comment by tomer-stripe** [comment]
Hey @alucic! What you've suggested is the direction we want to head in and I shared the feedback with the Issuing team. I'm going to sync up with them to try to come up with a path forward but because some of the webhooks from issuing work in a synchronous manner (instead of async like most of our other webhooks) we'll need to rework some of the CLI's forwarding capability to handle those correctly. I'll post updates in the ticket as we come up with a plan!

**Comment by AndrewTBaird** [comment]
@tomer-stripe Any updates so far on this issue? I have a nearly identical use case to @alucic, and would love the ability to end to end test my issuing webhook handling implementation

**Comment by helenamerk** [comment]
@tomer-stripe any update on the `issuing_authorization.*` events? 

From the guide (https://stripe.com/docs/issuing/controls/real-time-authorizations) it looks as if these triggers exist, but after running the ones provided at the bottom, the handler in the sample code provided never is fired. 

According to the doc I'd expect  ```stripe trigger issuing_authorization.request ``` to work, but it creates only a ```issuing_authorization.created``` request.

It would be helpful to have the guide clarified until the triggers are actually built!

**Comment by robnewton** [comment]
@tomer-stripe Any update on this?

I'm unable to find a good way to test partial authorizations as they are described in the documentation here: [https://stripe.com/docs/issuing/purchases/authorizations](https://stripe.com/docs/issuing/purchases/authorizations). The fuel dispenser use case it describes includes the triggering of an issuing_authorization.updated but there appears no way to reliably trigger it in test.

**Comment by localpathcomp** [comment]
I was only able to send synchronous events via an ngrok tunnel so far, specifically the authorization request event

**Comment by parsnips** [comment]
Any progress on this?

**Comment by cjavilla-stripe** [comment]
Just following up that this should work now. Be sure that you only have one webhook endpoint listening for `issuing_authorization.request` event types.

**Comment by HichameMoriceau** [comment]
What about the 2 other event types ☝️ ☝️  ?
- `issuing_authorization.created` and 
- `issuing_authorization.updated`

Could support for trigger `issuing_authorization.updated` be added ?

**Comment by Joshandrews43** [comment]
I am not getting any `issuing_authorization.request` webhooks requests to my local server-- just `issuing_authorization.created` and the `issuing_authorization.updated`, is there a way to get these?
