### ISSUE TITLE
Support of "payment_intent.canceled" event

### ISSUE THREAD

**Issue by bakurin** [stripe/stripe-cli#228]
### Problem
`payment_intent.canceled` event is not supported at the moment

### Feature
Support of `payment_intent.canceled`.

### Examples
Running `stripe trigger payment_intent.canceled` leads to `event payment_intent.canceled is not supported.`

Pull request stripe/stripe-cli#229

**Comment by ob-stripe** [comment]
Available as of v0.7.3. Thanks again for the PR @bakurin, we appreciate the contribution! :)
