### ISSUE TITLE
Add support for listening to only certain events

### ISSUE THREAD

**Issue by amiratak88** [stripe/stripe-cli#230]
It'd be nice to be able to listen for certain events only. Currently It sends listens for all events. Something like this:
```
stripe listen --events checkout.session.completed customer.created
```

**Comment by ob-stripe** [comment]
Hi @amiratak88. Good news, the CLI already supports this! If you want to listen for more than one event type, you can either:

1. separate event types with a comma:

```
$ stripe listen --events checkout.session.completed,customer.created
```

2. repeat the `--events` (or `-e`) flag:

```
$ stripe listen --events checkout.session.completed --events customer.created
```

Closing since this feature is already implemented, but feel free to reply!

**Comment by amiratak88** [comment]
awesome, thank u
