### ISSUE TITLE
Installation in a firewalled Ubuntu VM throws error: "gpg: keyserver receive failed: Server indicated a failure"

### ISSUE THREAD

**Issue by JackWH** [stripe/stripe-cli#231]
### Issue
I am using [Laravel Homestead](https://github.com/laravel/homestead), an Ubuntu-based development VM — which I would assume many people would want to use with stripe-cli, given the popularity of [Laravel Cashier](http://github.com/laravel/cashier).

But trying to install stripe-cli by following the [installation instructions](https://stripe.com/docs/stripe-cli) for Debian and Ubuntu-based distributions fails at step 1 when run inside a firewalled VM.

The docs instruct to run the following command to add Bintray's GPG key to the apt sources keyring:

```
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 379CE192D401AB61
```

However, when running the commands from within a firewalled virtual machine, this may result in the following vague error:

```
Executing: /tmp/apt-key-gpghome.mA57CDqXT9/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: Server indicated a failure
```

### Solution
Specifying that port 80 should be used for the keyserver URL seemed to allow the command to run successfully for me:

```
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 379CE192D401AB61
```

It may be worth updating the [installation docs](https://stripe.com/docs/stripe-cli) to account for this.

**Comment by ob-stripe** [comment]
Thanks for the detailed report and the solution @JackWH! I've updated the README file accordingly. The docs on stripe.com will be updated as well soon.

**Comment by JackWH** [comment]
Thanks for a swift response! I'll close this issue now.

**Comment by ob-stripe** [comment]
The docs on stripe.com have been updated. Thanks again!

**Comment by nazwa** [comment]
Not sure if this is relevant, but the updated command didn't actually work for me.

Running the **new** command on Ubuntu produced an error: **gpg: keyserver receive failed: No data** 

`sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 379CE192D401AB61` 

While running the original (without port specified) worked just fine 😄 

`sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 379CE192D401AB61`

**Comment by ob-stripe** [comment]
Thanks for the feedback @nazwa! So weird that specifying the port produces different results for different people. 🤔

**Comment by nazwa** [comment]
I know, right?! Ubuntu 18.04, running in WSL2, in case that makes a difference, which I doubt.

**Comment by mearafGitHub** [comment]
None of the solutions resolved the issue for me. I'm using Ubuntu 20.04 and running the same command discussed above.
