### ISSUE TITLE
Authorization failed when running stripe listen with --livemode flag

### ISSUE THREAD

**Issue by philippemiguet** [stripe/stripe-cli#234]
### Issue
When running `stripe listen -p segment --livemode --forward-to https://localhost:3000/stripe_webhook` I got the following error
```
you have not configured API keys yet. To do so, run `stripe login` which will configure your API keys from Stripe
```

I then generated a restricted key from the Stripe dashboard with the write rights for CLI, and added the missing `live_mode_api_key` in `~/.config/stripe/config.toml` for the "segment" project.

When running again the same command, I get the following error:
```
FATAL Error while authenticating with Stripe: Authorization failed, status=400, body={
  "error": {
    "message": "Cannot create StripeCLI session with a live API key. Try again with a test API key.",
    "type": "invalid_request_error"
  }
}
```

### Expected Behavior
My initial need was to use `stripe trigger` to replay production events locally and debug our webhook.

If I use the `stripe listen` command without the flag `--livemode` and use `stripe  trigger --event production_event_id`, then the listen command doesn't seem to catch the Stripe event. That is why I thought of using the --livemode.

I expected the listen command to run and be able to listen for production events I would trigger using `stripe trigger -p segment --event production_event_id`.

### Steps to reproduce
1. Run `stripe listen -p segment --livemode` without the entry `live_mode_api_key` in `~/.config/stripe/config.toml`.
2. Create restricted key and add it to `~/.config/stripe/config.toml`.
3. `stripe listen -p segment --livemode`

### Traceback
```
⣾ Getting ready... [Mon, 14 Oct 2019 14:21:42 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready... [Mon, 14 Oct 2019 14:21:44 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣻ Getting ready... [Mon, 14 Oct 2019 14:21:46 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣽ Getting ready... [Mon, 14 Oct 2019 14:21:48 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⡿ Getting ready... [Mon, 14 Oct 2019 14:21:49 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣟ Getting ready... [Mon, 14 Oct 2019 14:21:51 CEST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
[Mon, 14 Oct 2019 14:21:53 CEST] FATAL Error while authenticating with Stripe: Authorization failed, status=400, body={
  "error": {
    "message": "Cannot create StripeCLI session with a live API key. Try again with a test API key.",
    "type": "invalid_request_error"
  }
}
```

### Environment
macOS

**Comment by ob-stripe** [comment]
Hi @philippemiguet, thanks for the detailed report.

This is expected, though you'd have no way of knowing that. We're still in the process of rolling out live mode support for the CLI. Stripe accounts that have access to this feature automatically get a live mode restricted API key when running `stripe login`, and can then use that key to listen for live mode events with `stripe listen --livemode`. (Though what you did here, i.e. manually set the key in the configuration file, would work too.)

If you want, I can enable this feature for your Stripe account. I just need to know your account's ID (`acct_...`).

**Comment by philippemiguet** [comment]
Hi @ob-stripe, thanks for the speedy and clear answer!

I have another question related to this issue/feature. **Will it allow to use `stripe trigger` to replay specific production events?**

At the moment, the `stripe trigger` command doesn't have a `--livemode` flag, so I passed the restricted production api key using `--api-key` to force using that key. I then got the following error:
```
Request failed, status=400, body={
  "error": {
    "message": "You can only retry Events in test mode",
    "type": "invalid_request_error"
  }
}
```

I guess it is all tied to not having the livemode feature enabled?

> If you want, I can enable this feature for your Stripe account. I just need to know your account's ID (acct_...).

We would love that, though I've been looking around in the Stripe dashboard and I'm not able to find our account's ID. Would you know where I can find it?

**Comment by philippemiguet** [comment]
> That's definitely our intent, but there's a bit more work needed on our end before we can enable event replay in live mode through the CLI. We're actively working on it!

That's great to hear, can't wait to test that feature!

> You can find your account's ID by clicking on the icon in the top right corner then on "Profile" in the dropdown menu. At the bottom of the profile page, you can find the IDs of all the Stripe accounts to which you are a member.

Ah thanks I've found it! @ob-stripe, would you be able to provide an email address where I can send you our account ID. Even though it is not a super sensitive information we would like to not share it on a public repository 😄

**Comment by ob-stripe** [comment]
@philippemiguet Actually, we've just rolled out the ability to use the CLI in live mode to all accounts.  `stripe listen --livemode` should work now.

**Comment by ob-stripe** [comment]
As of v0.7.5, you can use the `stripe events resend` to resend past events.

The command expects the event ID as its argument. By default, it will resend the event to connected CLI clients (i.e. CLI instances running `stripe listen`). You can use the `--webhook-endpoint we_123` flag to resend the event to a specific webhook endpoint instead.

The command also accepts a `--livemode` flag to resend a livemode event.

Closing, but feel free to reply if you're having trouble with this!
