### ISSUE TITLE
Connect Webhooks not POSTed to URL after being received

### ISSUE THREAD

**Issue by warksit** [stripe/stripe-cli#242]
### Issue
Connect webhooks are received by stripe cli but not POSTed to my url when I just set a `--forward-connect-to url`. If I set both `--forward-connect-to` and `--forward-to` then they all get POSTed to my url correctly. [Screenshot of stripe-cli output](https://www.dropbox.com/s/rxxe5n6rhofcpxg/Screenshot%202019-10-17%2015.37.28.png?dl=0) notice the lack of POST lines at the bottom. Same checkout flow for both 

### Expected Behavior
I expect all connect webhooks to be POSTed to the url I specify with `--forward-connect-to` after they have been received. Even if `--forward-to` is not set.

### Steps to reproduce
Run `stripe listen  --forward-connect-to <URL>` (without `--forward-to`) and trigger a connect webhook

### Environment
macOS

**Comment by tomer-stripe** [comment]
@ob-stripe was there a reason we made them both be required? I can't remember if that was an intentional decision or not.

**Comment by ob-stripe** [comment]
Not that I can remember. It makes sense to enable the use `--forward-connect-to` without passing `--forward-to`, we should fix it.

**Comment by ob-stripe** [comment]
This should be fixed in v0.8.0.
