### ISSUE TITLE
Support "payment_intent.amount_capturable_updated" event

### ISSUE THREAD

**Issue by jdewells** [stripe/stripe-cli#251]
### Problem
At the moment, we can't test the manual capture flow with the Stripe CLI because `payment_intent.amount_capturable_updated` isn't supported.

### Feature
For `payment_intent.amount_capturable_updated` to be fired when capturing a payment intent with a manual capture, once it's authorised.

**Comment by tomer-stripe** [comment]
@jdewells looking into this, asking the team now!

**Comment by tomer-stripe** [comment]
I think I have an idea for how to do this but am going to wait until I get #244 merged since that's redoing the entire interface for that. I'll keep posting updates here

**Comment by ob-stripe** [comment]
Support for the `payment_intent.amount_capturable_updated` event type was added in v1.2.0.
