### ISSUE TITLE
Windows: Use ZIP file archive format for GitHub releases

### ISSUE THREAD

**Issue by jlnostr** [stripe/stripe-cli#260]
Because Windows is not able to unpack `.tar.gz` files by default, it would be nice if the GitHub release for Windows could be packed as `.zip`. This would allow an easier usage on Windows where the system is able to open ZIP archives natively.

**Comment by ob-stripe** [comment]
Very good suggestion, thanks @jlnostr! We'll look into that ASAP.

**Comment by ob-stripe** [comment]
Well that was an easy fix :) As of v0.8.3, Windows binaries will be released as `.zip` instead of `.tar.gz`.

**Comment by jlnostr** [comment]
That was quick, holy cow. Thanks!
