### ISSUE TITLE
Update intro text and remote beta warning

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-cli#263]
We should remove the beta warning and update the intro text to:

`The official command-line tool to interact with Stripe.`

Formatting like:
<img width="1188" alt="Screen Shot 2019-10-31 at 6 11 10 PM" src="https://user-images.githubusercontent.com/53238203/67995841-d6ca5400-fc09-11e9-9e8e-b45477540c2d.png">

**Comment by tomer-stripe** [comment]
🎉 

Should sync this up with the docs too: stripe.com/docs/stripe-cli
