### ISSUE TITLE
`stripe trigger customer.subscription.updated` fails with 404s

### ISSUE THREAD

**Issue by benekastah** [stripe/stripe-cli#266]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue

I was trying to test my webhook, so I ran `stripe trigger customer.subscription.updated` and got 404 responses. The webhook never was hit with the event type `customer.subscription.updated`.

### Expected Behavior
On the previous version, no 404s happened and the webhook was hit with the event as expected.

### Steps to reproduce
Ensure you are using stripe version `stripe version 0.9.0 (beta)`. Run a webserver locally to take webhook requests and run `stripe listen --forward-to localhost:8000`. Then, run `stripe trigger customer.subscription.updated`.

### Traceback
Full command output:

```
Setting up fixture for: customer
Setting up fixture for: plan
Setting up fixture for: subscription
Trigger failed: Request failed, status=404, body={
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: ${customer.id}",
    "param": "customer",
    "type": "invalid_request_error"
  }
}

Request failed, status=404, body={
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: ${customer.id}",
    "param": "customer",
    "type": "invalid_request_error"
  }
}

```

### Environment
macOS

**Comment by ob-stripe** [comment]
Hi @benekastah, thanks for the report and sorry for the inconvenience.

@tomer-stripe Can you take a look? This is likely related to #244.

**Comment by tomer-stripe** [comment]
Yep!

**Comment by auchenberg** [comment]
Same case for `stripe trigger payment_intent.succeeded` on 0.9.0

```
stripe trigger payment_intent.succeeded
Setting up fixture for: payment_method
Setting up fixture for: payment_intent
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_method: ${payment_method.id}",
    "param": "payment_method",
    "type": "invalid_request_error"
  }
}
```

**Comment by tomer-stripe** [comment]
Actively working on a fix for this! Hope to get it resolved soon.
