### ISSUE TITLE
Completion command generates bash script for ZSH

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-cli#269]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
Completion command generates bash script for ZSH

### Expected Behavior
Completion command generates to generate ZSH script.

### Steps to reproduce

Running `stripe completion` gives you:

```
➜  ~ echo $0
/bin/zsh
➜  ~ stripe completion
Generated bash completion file: stripe-completion.bash
➜  ~ 
```

### Environment
Stripe CLI version `0.9.0`
macOS

**Comment by tomer-stripe** [comment]
@auchenberg-stripe you might need to run it with the `--shell` flag: `--stripe completion --shell zsh`

**Comment by auchenberg** [comment]
Aren't we supposed to detect the current shell automatically and help the user?

**Comment by tomer-stripe** [comment]
I had some hesitation about `exec`ing out to do that but you're right that we should try to do it automatically.

Let me put a PR together and see what other people think.
