### ISSUE TITLE
Typo in official documentation

### ISSUE THREAD

**Issue by metuan** [stripe/stripe-cli#276]
### Feedback
When you go through the official doc: [Building a webhook endpoint - Listening and forwarding events](https://stripe.com/docs/webhooks/build#listening-and-forwarding) there is a typo in the following command:
- `stripe listen --foward-to localhost:4242/webhook` 
and it results in: 
- `unknown flag: --foward-to`. 

It should be changed to `stripe listen --forward-to localhost:4242/webhook`.

**Comment by tomer-stripe** [comment]
Thanks @metuan! Will get that fixed

**Comment by tomer-stripe** [comment]
Fixed :D
