### ISSUE TITLE
Installation of 1.0 release fails on macOS with homebrew

### ISSUE THREAD

**Issue by MaxDesiatov** [stripe/stripe-cli#279]
### Issue
I've tried to install the CLI with `brew install stripe/stripe-cli/stripe` command. An error always occurs during the process, which wasn't reproducible for 0.9 release:

```% brew install stripe/stripe-cli/stripe    
==> Installing stripe from stripe/stripe-cli
==> Downloading https://github.com/stripe/stripe-cli/releases/download/v1.0.0/stripe_1.0.0_mac-os_x86_64.tar.gz
Already downloaded: /Users/maxd/Library/Caches/Homebrew/downloads/11ebe7db00b98a40af8b09923b0f67596db30f658264a963a434ccf38f97f629--stripe_1.0.0_mac-os_x86_64.tar.gz
==> /usr/local/Cellar/stripe/1.0.0/bin/stripe completion
==> /usr/local/Cellar/stripe/1.0.0/bin/stripe completion --shell zsh
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - stripe-completion.bash
```

### Expected Behavior
The package is installed without any issues.

### Steps to reproduce
Run `brew install stripe/stripe-cli/stripe` on macOS with Homebrew installed.

### Traceback
Listed above.

### Environment
macOS 10.14.6 (18G1012)

**Comment by ob-stripe** [comment]
Hi @MaxDesiatov, thanks for the report and sorry for the trouble. I just released 1.0.1 which should fix the brew installation issue. It will be available in a few minutes. Please let me know if you're still observing the issue after updating!
