### ISSUE TITLE
Instillation link for linux leads to 404

### ISSUE THREAD

**Issue by TechTeam12** [stripe/stripe-cli#283]
Your [linux install section](https://github.com/stripe/stripe-cli#linux) has a dead link for the instillation wiki link. 
Your wiki can be found at: https://github.com/stripe/stripe-cli/wiki/installation#linux not the link https://github.com/stripe/stripe-cli/blob/master/wiki/installation#linux that your readme has.

### Issue
On the repo home space if you go to the linux download and attempt to navigate to the instillation wiki the link is a dead link.

### Expected Behavior
The link should take you to the instillation wiki.

### Steps to reproduce
Go to the repo home page, find the instillation wiki link under the linux tab, and click it.

### Environment
Ubuntu 16 with Firefox 70.0

**Comment by tomer-stripe** [comment]
Fixing!

**Comment by TechTeam12** [comment]
Thanks!

**Comment by TechTeam12** [comment]
Nice fixes!

**Comment by tomer-stripe** [comment]
@TechTeam12 GitHub's being a little slow to merge, sorry about that :(
