### ISSUE TITLE
--color off not working

### ISSUE THREAD

**Issue by PhilETaylor** [stripe/stripe-cli#286]
### Issue
`--color off` flag not honoured 

### Expected Behavior
raw JSON 

### Steps to reproduce

run command with `--color off`

```
stripe subscriptions list \
    --color off \
    --live \
    --status past_due 
```

See that the output is still colourized in the terminal output - it should not be?

### Environment
v1.0.1 on mac in iTerm

**Comment by ob-stripe** [comment]
Thanks for the report! This should be fixed in v1.1.0.
