### ISSUE TITLE
Attempting to tail LIVE logs 

### ISSUE THREAD

**Issue by PhilETaylor** [stripe/stripe-cli#287]
### Issue
Idiots like me dont read - and try to append `--live` to `logs tail` and the command does something, but no live logs are ever received...

documentation only talks about tailing test mode logs - but im an idiot and do not read, maybe live logs are impossible to tail? maybe they should be able to be tailed with --live?

### Expected Behavior

Error saying you cannot tail live logs OR the live logs are shown

### Steps to reproduce

`stripe logs tail --log-level debug --live`

### Environment
v1.0.1(docker) on mac in iTerm2

**Comment by tomer-stripe** [comment]
Yep, live log tailing isn't quite supported yet, sorry for the confusion! We're still evaluating that on our side but we'll track any updates in #101.

**Comment by PhilETaylor** [comment]
Cool - but maybe the command when called with --live should actuall SAY its not doing anything :) instead of giving a false impression it is :)

**Comment by ob-stripe** [comment]
To clarify, this feature is implemented, but most Stripe accounts currently don't have access to it (we will roll out support for this progressively in the future). I agree that we could do a better job of reporting when the account isn't enabled for tailing live mode logs instead of connecting and waiting for logs that will never come though :) We'll look into improving the experience here.

**Comment by PhilETaylor** [comment]
Its all about managing expectations :-) If Im told 

- This feature is implemented, but most Stripe accounts currently don't have access to it, your account doesnt; exit; 

then as a user I would be "oh ok, thats cool, at least I know" :-)

**Comment by ob-stripe** [comment]
> Its all about managing expectations :-)

Fully agreed :)

We've just rolled out a backend change to make this clearer. Trying to use the `logs tail` command with the `--live` flag when your account does not yet have access to this feature will now display a hopefully clearer error message:

```sh
$ stripe logs tail --live
[Wed, 06 Nov 2019 14:15:29 PST] FATAL Error while authenticating with Stripe: Authorization failed, status=400, body={
  "error": {
    "message": "Your account is not allowed to tail logs in live mode at this time. This feature will be rolled out progressively in the future.",
    "type": "invalid_request_error"
  }
}
```

Closing the issue, but feel free to reply. We'll post an update once this feature is fully "live" ;)

**Comment by PhilETaylor** [comment]
Awesome - that’s much better and manages the expectation great! Thanks.
