### ISSUE TITLE
docs in places has --livemode instead of --live

### ISSUE THREAD

**Issue by PhilETaylor** [stripe/stripe-cli#288]
docs in places has `--livemode` instead of `--live`

eg at the bottom of https://github.com/stripe/stripe-cli/wiki/Open-command

```
 stripe open dashboard/apikeys --livemode
```

which gives 

`unknown flag: --livemode`

Furthermore, `--live` is very sparsely referred to throughout the stripe-cli project documentation/examples. Took me ages to find how to use live mode instead of test :) but then im an idiot.

**Comment by tomer-stripe** [comment]
Fixed that specific instance, I'll do another pass to see if we missed any more.

The `--live` flag is something we're slowly rolling out which is why it's not as heavily documented. Where are you trying to use it?

**Comment by PhilETaylor** [comment]
It was mentioned in the tweet https://twitter.com/patrickc/status/1191773489486655488 :-) so I thought I would give it a go

**Comment by tomer-stripe** [comment]
Oh yea, that use case should work! It works across all the resource and request commands right now, it's more around the real-time features that we're still rolling out.

**Comment by PhilETaylor** [comment]
`--live`  does work in that example, listing subscriptions. 

Once you have done a quick sweep for any `--livemode` then feel free to close this

**Comment by ob-stripe** [comment]
Just did a pass over the repository, the wiki and the docs on stripe.com and I think we removed all mentions of `--livemode`.

Closing this, though I agree we can do a better job of documenting the `--live` flag. We'll try to improve this soon.
