### ISSUE TITLE
customer.subscription.created support

### ISSUE THREAD

**Issue by kypalmer** [stripe/stripe-cli#292]
### Problem
Testing subscription creation (with metadata) webhooks in a local dev environment.

### Feature
A trigger for `customer.subscription.created` with customizable fields like metadata, email and plan. 

### Examples
`stripe trigger customer.subscription.deleted --metadata:{prop: "value"}` would seem to work well (JavaScript style object property syntax). It could also be json style, if that works better ({"prop": "value"}).

Love this CLI guys! thanks!

**Comment by ob-stripe** [comment]
We can add support for triggering `customer.subscription.created` events.

However, customizable fields would be more difficult to implement. I've opened a separate issue to discuss this feature specifically: #295.

**Comment by ob-stripe** [comment]
Support for `customer.subscription.created` (without customization) was added in v1.2.0.

Closing this issue, but please feel free to reply in #295 to discuss the customization feature.

**Comment by kypalmer** [comment]
Awesome! Thanks for such a quick response on `customer.subscription.created`. FYI docs @ https://github.com/stripe/stripe-cli/wiki/trigger-command still don't have it listed as a supported event.
