### ISSUE TITLE
When dumping output, additional blank lines are added

### ISSUE THREAD

**Issue by PhilETaylor** [stripe/stripe-cli#303]
### Issue

2 additional lines in output

### Expected Behavior
a text file called output.txt that contains nothing but the JSON

### Actual Behavior
a text file called output.txt that contains nothing but the JSON **+ two additional blank lines at the end**

![Screenshot 2019-11-07 at 15 57 16](https://user-images.githubusercontent.com/400092/68405009-4b0b7700-0177-11ea-9aa0-17daf029820b.png)

### Steps to reproduce
run example command

```
stripe subscriptions list --status past_due > output.txt
```
inspect the file output.txt

### Environment
mac docker 1.2.0

**Comment by tomer-stripe** [comment]
Opening a PR to remove one of the extra new lines. It looks like our API actually returns a new line at the end of json responses on its own and I'm hesitant to have the CLI manually remove that (I'd like to avoid making specific changes on the API CLI-side).

Asking some people internally but not sure if that'll happen.

**Comment by tomer-stripe** [comment]
Sorry, looked like my shell actually added an extra one. The API's doing the right thing and the PR should remove the extra one you're seeing.
