### ISSUE TITLE
stripe open not appropriate in docker image

### ISSUE THREAD

**Issue by PhilETaylor** [stripe/stripe-cli#304]
### Issue

When running in a docker image, there is no concept of a web browser on the docker host, and therefore the `open` command makes no sense and just gives an error.

I dont have all the answers, but mayeb detect if running in docker, and show a "Doh you cannot open a browser from a docker image ran stripe command" message instead of `exec: "xdg-open": executable file not found in $PATH` error that is shown. 

Also... you might want to visit other commands like the samples create as well, as they cannot be used in docker.

### Expected Behavior

Managed expectation :) tell me Im an idiot for wanting to open a browser from a docker image

### Steps to reproduce

run `stripe open docs` from the stripe docker image 

```
docker run -v /path/to/my/.config:/root/.config --rm -it stripe/stripe-cli open docs
```

### Actual Behavior

`exec: "xdg-open": executable file not found in $PATH`

### Environment
mac docker stripe 1.2.0

**Comment by tomer-stripe** [comment]
Was there a reason you tried to run `open` from inside docker?

I don't know if I want to make too many assumptions about what people are trying to do inside docker. `samples` could definitely work from there and someone might be developing inside of a docker container.

**Comment by PhilETaylor** [comment]
Because like most docker users I alias docker run commands to something shorter and I accidentally ran that alias which launched in a docker contain (all of my use is just testing and reporting issues, nothing serious!)

**Comment by tomer-stripe** [comment]
Cool :D

I'm inclined to leave this as-is to avoid limiting functionality for people in Docker containers (plus it's entirely possible someone might have and use a text-based browser like [Lynx](http://lynx.browser.org/))

**Comment by PhilETaylor** [comment]
Awesome. Thats cool.
