### ISSUE TITLE
'stripe trigger invoice.payment_failed' not working

### ISSUE THREAD

**Issue by kareemcoding** [stripe/stripe-cli#316]
### Issue
When running ```stripe trigger invoice.payment_failed``` on my terminal, it returns ```event invoice.payment_failed is not supported.``` even though you list this as a supported event.

### Environment
macOS installed via brew

**Comment by tomer-stripe** [comment]
@kareemcoding what version of the CLI are you running? It appears to be working for me running version`1.2.2`

**Comment by kareemcoding** [comment]
I seem to be running ```stripe version 0.2.7 (beta)```

How do I upgrade? I downloaded it through homebrew?

**Comment by tomer-stripe** [comment]
On homebrew, could you run `brew update` and then `brew upgrade`?

**Comment by kareemcoding** [comment]
Success @tomer-stripe 🎉

Thanks!
