### ISSUE TITLE
Trigger checkout webhook with custom data

### ISSUE THREAD

**Issue by rinu** [stripe/stripe-cli#317]
### Problem
_What are you trying to do?_
I'm testing my webhook which depends on `client_reference_id`. It seems testing checkout webhooks is still a new feature and is incomplete.

### Feature
_What would help you accomplish your original task_
Triggering checkout webhooks should have options to override fixture data. I specifically would like a `--client-reference-id` option but all data should be overwritable somehow.

**Comment by Freezystem** [comment]
seems like a duplicate of https://github.com/stripe/stripe-cli/issues/295

**Comment by AndrewFreemantle** [comment]
I'm wondering if the ability to pass a custom `client-reference-id` from the command line might satisfy the majority of setup and testing use cases? It would certainly be enough for me

**Comment by ob-stripe** [comment]
Closing as a duplicate of #295.
