### ISSUE TITLE
--color on not work on piping

### ISSUE THREAD

**Issue by acomagu** [stripe/stripe-cli#320]
```
$ stripe charges list --color on | less -SR
```

don't color.

**Comment by tomer-stripe** [comment]
Will look into this!

**Comment by tomer-stripe** [comment]
I'm having trouble reproducing this, running your command colors the output for me. Do you have any environment variables for `CLICOLOR_FORCE` or `STRIPE_COLOR`?

**Comment by acomagu** [comment]
Oh, sorry. I was using old version CLI(The Arch package is outdated).
v1.2.2 works correctly. Thank you!
