### ISSUE TITLE
Using --load-from-webhooks-api removed trailing slash from url

### ISSUE THREAD

**Issue by DannyAziz** [stripe/stripe-cli#322]
When using the `--load-from-webhooks-api` argument for the `listen` command, all urls have their trailing slash removed even if I pass a url with a trailing slash to `--forward-to`

This happens from both webhooks trigged from app use and from `stripe-cli trigger`
This doesn't happen when removing the `--load-from-webhooks-api` arg

### Environment
macOS

**Comment by tomer-stripe** [comment]
Hey @DannyAziz! Could you give an example of what you're seeing and what you're expecting?

It sounds like the endpoints defined in the dashboard are losing their slash on something like `/webhooks/` right? How is that interacting with the `--forward-to` flag?

**Comment by ob-stripe** [comment]
Should be fixed in v1.2.6.
