### ISSUE TITLE
Error on checkout.session.completed Billing address needed for India

### ISSUE THREAD

**Issue by zifahm** [stripe/stripe-cli#340]
### Issue
Trying to trigger checkout.session.completed and getting the following error
```
 "message": "As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports",

```

### Steps to reproduce
trigger checkout.session.completed from India

### Environment
Linux Mint

**Comment by tomer-stripe** [comment]
Hey @zifahm! For this you'll probably want to create your own fixture with the extra information. While not `checkout.session.completed` you can see general steps for how to do it from #327 and use the [triggers/checkout.session.completed.json](https://github.com/stripe/stripe-cli/blob/master/triggers/checkout.session.completed.json) file as a base.

**Comment by zifahm** [comment]
alrighty Thanks
