### ISSUE TITLE
Custom fixtures for webhook triggers?

### ISSUE THREAD

**Issue by stephencelis** [stripe/stripe-cli#341]
Is it possible to run, e.g., `invoice.payment_failed`, where `plan` and `subscription` are present, or would this require feature work?

**Comment by tomer-stripe** [comment]
Hey @stephencelis! You'd probably want to create a custom fixture for this. We've got some instructions in #295 for how you could do that on your own. You could then use the `invoice.payment_failed` trigger as a base and make modifications:  https://github.com/stripe/stripe-cli/blob/master/triggers/invoice.payment_failed.json

**Comment by johnpitchko** [comment]
Hello, is using fixtures for firing event triggers still possible @tomer-stripe ? I am testing integration with Segment, but it just rejects the `charge.failed` test received from the Stripe webhook because all the key fields (e.g. customer_id) are null.
