### ISSUE TITLE
Support triggering account.updated event

### ISSUE THREAD

**Issue by maxrothman** [stripe/stripe-cli#345]
### Problem
I'm trying to build a webhook endpoint to detect when Connect accounts reach a threshold that changes their verification requirements

### Feature
Support the account.updated event in stripe CLI

**Comment by Andrewangeta** [comment]
This is one that's really needed. Any updates on this one or a workaround to trigger Webhooks?

**Comment by the-timoye** [comment]
The account.update event still doesn't get logged. Is there anyway to go about this?

**Comment by prascuna** [comment]
Hi there, any update on this one? I'm trying to test the Connected Account creation, as suggested here:
https://stripe.com/docs/connect/enable-payment-acceptance-guide

**Comment by JamesTPF** [comment]
Duplicated by
https://github.com/stripe/stripe-cli/issues/407
https://github.com/stripe/stripe-cli/issues/546

**Comment by richardg-stripe** [comment]
Whilst the `account.updated` events fired in Stripe testmode aren't quite the same as in livemode, they do get fired. stripe-cli prints and forwards them correctly for me (I just tested it myself). It can take 2-3 minutes for the `account.updated` event to fire.

If you'd like to see events inside the dashboard they're a little tricky to find. You can find them at: https://dashboard.stripe.com -> 'Connected accounts' on the left hand side -> Click an account -> Click the three dots in the top right -> click 'View dashboard as {Name}' -> Developers (left hand side) -> Events.

To test it out yourself you can run: `stripe listen --print-json --events account.updated --forward-to http://localhost:3000`

There are some good docs about testing our verification flow with test data here: https://stripe.com/docs/connect/testing

**Comment by pepin-stripe** [comment]
Please follow up on this issue if you are still facing issues following @richardg-stripe 's comment.

**Comment by maxrothman** [comment]
I’m aware of the workaround of using test mode or live mode events. This request is to add `account.updated` to the list of events that the CLI can trigger, eg with `stripe cli trigger account.updated`

**Comment by maxrothman** [comment]
Why has this issue been closed?

**Comment by pepin-stripe** [comment]
@maxrothman sorry, probably closed by mistake 🙃 I'll file a task internally and get that event added to the CLI!

**Comment by Wharley01** [comment]
Is there anything being done on this 🥺

**Comment by pascuflow** [comment]
For those of us not using the CLI, my https://dashboard.stripe.com/test/webhooks is not showing any account.update event even though I see it in https://dashboard.stripe.com/acct_BLAH/test/events, where can I raise this issue?
