### ISSUE TITLE
–-color option is confusing

### ISSUE THREAD

**Issue by auchenberg** [stripe/stripe-cli#349]
From friction log:

## Configure dev environment including Stripe CLI
- I’ve heard that Stripe has this great CLI that I can use while building
[install steps - have done this previously]
- Now, where do I start? I’ll try `stripe help` → I get a useful list of commands, though `login` is kind of buried. Think this should sit up top, below `Usage` as `Getting Started`.
- So I try`stripe login` and pop open the window to confirm my login.
- I play around a little… it says I can change the color output. That’s cool! So I try `stripe --color on` and the response is to pop up the `--help` menu. Did the color output change? I try `stripe --color auto` and get the same, and likewise for `stripe --color --help`. This just seems like a bug / bad design because 1/ I don’t know if the command works, and 2/ the response is confusing / off topic. In particular the `--color --help` command should be giving me more refined / specific help menu.
- One command that looks interesting is `samples` so I try `stripe samples` and see that `list` is an option, so I try that. This gives me a list of all of the sample integrations with links to the repos. That is really fantastic. As a nit, the titles aren’t super clear if I’m coming with a particular API / product in mind (e.g. which payment samples are using PaymentIntents versus Checkout or Charges?)
- Maybe I’ll see what it looks like to bootstrap a sample using the CLI. I try `stripe samples create` - I guess this will ask me to provide one of the sample names as an argument, but I’m not sure. - The result is `Creating a sample requires at least 1 argument, received 0`. This squarely seems like a bug - the pattern elsewhere is to tell me what extra argument is needed / what the usage is.
Okay, that’s enough for now. I’m going to go consult the docs and the sample integration, and I’ll come back later.

**Comment by richardm-stripe** [comment]
The problem is the user didn't make the distinction between *commands* and *flags*. Maybe the best UX here is

- `stripe` without commands or flags still displays the full usage information
- `stripe --color on` etc. that specify flags but not commands, displays something like "You provided flags but did not specify any command. Type `stripe help` for a list of commands".

**Comment by richardm-stripe** [comment]
Reclassifying as enhancement, also
