### ISSUE TITLE
Support getting Connect accounts

### ISSUE THREAD

**Issue by axelfran** [stripe/stripe-cli#353]
### Problem
I am trying to use the CLI to fetch information about my Connect accounts. This returns an `"invalid_request_error"` as the key is restricted and it is not possible to get Connect data with it.

### Feature
It would be helpful if it was possible to get Connect accounts and have relevant events such as the `account.updated` webhook event emulated and from the Stripe platform in the CLI. 

### Examples
`stripe get acct_*****`

**Comment by jgadbois** [comment]
Along the same lines, I would like to be able to do `stripe events resend <event_id>` for an event originated from a Connect account

**Comment by sebastienpeek** [comment]
Upvoting this, we're currently working on implementing Custom Connect account creation/verification and would love to be able to capture `account.updated` events via the cli so that we can test the functionality of the webhooks locally.

**Comment by tomer-stripe** [comment]
For a number of commands we have a `--stripe-account` flag available that'll let you set the connected account. For both `stripe get` and `stripe events resend` you should be able to provide the Connect account through the header.

@sebastienpeek the CLI should support connected webhook events, were you having issues with that?

**Comment by tomer-stripe** [comment]
One other thing to note: the CLI generates a restricted access key when you login but, unfortunately, restricted access keys don't have access to make connect requests.

To test Connect features you'll want to grab your testmode secret key and use that with the CLI (either using using the `--api-key` flag or overwriting the key in the CLI config file).

**Comment by ob-stripe** [comment]
> restricted access keys don't have access to make connect requests.

More precisely, restricted access keys cannot use the `/v1/accounts` endpoint. They can be used to make requests on behalf of connected accounts using the `Stripe-Account` header (as long as they have the necessary permissions -- restricted access keys created for the CLI during the `stripe login` flow have all permissions by default).

The fact that they cannot use the `/v1/accounts` is a technical limitation on our end that will hopefully be fixed at some point, but it has not been prioritized so far.

**Comment by axelfran** [comment]
@tomer-stripe @ob-stripe Thank you for your suggestions. Using the `--stripe-account` and/or `--api-key` flags should be sufficient for our use case.

**Comment by sebastienpeek** [comment]
@tomer-stripe this should provide us with enough information, thanks for the update!
