### ISSUE TITLE
Stripe listen stuck on getting ready

### ISSUE THREAD

**Issue by nathanbrnrd** [stripe/stripe-cli#359]
### Issue
When trying to listen with `stripe listen`, the terminal shows that the cli is checking for new versions and then tries to connect. But it gets stuck on `Getting ready...`
The login is working fine as well as a `stripe trigger...` but nothing for the stripe listen.
Do you have a solution or any other workarounds to develop locally and test some webhooks?

### Expected Behavior
Ready...

### Steps to reproduce
`stripe listen`

### Traceback
```
⣽ Getting ready... 
```
### Environment
On mac Mojave 10.14.6
Stripe-cli version: 1.2.9

**Comment by ob-stripe** [comment]
Hi @nathanbrnrd. Can you post the output when you run `stripe listen --log-level=debug`?

**Comment by nathanbrnrd** [comment]
Hi Olivier,
This is the output:
```
$ stripe listen --log-level=debug
A newer version of the Stripe CLI is available, please update to: v1.3.0
⣾ Getting ready... [Thu, 30 Jan 2020 00:53:57 EST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⡿ Getting ready... [Thu, 30 Jan 2020 00:54:07 EST] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe display_connect_filter_warning=false reconnect_delay=53 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{22078}_3DNNGSNU1xWWBCNj5DtY7Ck0H6SwhVQrVWsTvTmuTZmupfdIiA websocket_url=wss://stripe-cli.stripe.com/subscribe/acct_18idRuA90TuG5Dx1
[Thu, 30 Jan 2020 00:54:07 EST] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Thu, 30 Jan 2020 00:54:07 EST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_18idRuA90TuG5Dx1?websocket_feature=webhook-payloads
⡿ Getting ready... [Thu, 30 Jan 2020 00:54:17 EST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 30 Jan 2020 00:54:17 EST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⡿ Getting ready... [Thu, 30 Jan 2020 00:54:27 EST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_18idRuA90TuG5Dx1?websocket_feature=webhook-payloads
⣟ Getting ready... [Thu, 30 Jan 2020 00:54:37 EST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 30 Jan 2020 00:54:37 EST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⣯ Getting ready... [Thu, 30 Jan 2020 00:54:47 EST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_18idRuA90TuG5Dx1?websocket_feature=webhook-payloads
⣷ Getting ready... [Thu, 30 Jan 2020 00:54:57 EST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 30 Jan 2020 00:54:57 EST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⣾ Getting ready... [Thu, 30 Jan 2020 00:55:07 EST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_18idRuA90TuG5Dx1?websocket_feature=webhook-payloads
⣾ Getting ready... [Thu, 30 Jan 2020 00:55:17 EST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 30 Jan 2020 00:55:17 EST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
```

**Comment by ob-stripe** [comment]
Strange 🤔 

Is it possible you're behind a proxy or firewall that blocks websocket connections?

**Comment by nathanbrnrd** [comment]
Hi @ob-stripe,
I work from home and i am not behind a proxy or firewall for what I know (I don't know much about that).

But I added google dns (8.8.8.8) to my network on my Mac and now it is working..
If you have an explanation, I'll take it :)

Thanks.

Nathan

**Comment by ob-stripe** [comment]
I don't have an explanation... Networking issues can be quite [mysterious](https://www.xkcd.com/2259/).

Closing, but feel free to reply or open a new issue if this happens again.

**Comment by risurina** [comment]
I have encountered this issue. I think there are some networking issues.
But after using VPN, it was fixed.

**Comment by nathanbrnrd** [comment]
Hi there,

Very old issue.
If I remember correctly, I added 8.8.8.8 in my DNS servers (on MacOS) and
this was fixed .

Hope this will help others.

Nathan

**Comment by davidhicks980** [comment]
Also MacOS, 8.8.8.8 worked. Wifi button > Network Preferences > Advanced > DNS > Add 8.8.8.8. Using an M1 Pro, not sure if there is a difference between Intel and M1.

**Comment by CaptainLazarus** [comment]
In case you're looking at this in 2022 (or in the future), for PopOS and Ubuntu you can use the following steps to add google's open DNS to make it work.

Open **/etc/resolv.conf** and edit the file and add the following lines 
1. nameserver 8.8.8.8
2. nameserver 8.8.4.4

Save the file and it should work now.

**Comment by adetch** [comment]
Also had the same issue, but note that Apple changed things around to make it more confusing in Ventura 13.0.1. This article (in spanish!) was helpful: https://www.pressapple.com/cambiare-server-dns-su-macos-ventura/

Basically search for `DNS` in the Settings App and add the `8.8.8.8` DNS server - it's not discoverable otherwise!

**Comment by DashBarkHuss** [comment]
> Also MacOS, 8.8.8.8 worked. Wifi button > Network Preferences > Advanced > DNS > Add 8.8.8.8. Using an M1 Pro, not sure if there is a difference between Intel and M1.

this worked for me

**Comment by piyush-saurabh** [comment]
I had the same issue on Ubuntu 22.4. I was able to resolve the issue by changing the nameserver to 8.8.8.8 in /etc/resolv.conf

**Comment by itpaulin** [comment]
Hi, the same problem here, I'm all the day stuck in this

**Comment by Redskinsjo** [comment]
I had the same issue. Actually my mac was running Cloudflare Warp, deactivating it made it work.
