### ISSUE TITLE
Authenticating and then listening fails with 500

### ISSUE THREAD

**Issue by paulca** [stripe/stripe-cli#36]
Hi,

This is great! I literally requested this in a Stripe engineering session and here it is. Thank you! I literally paid for ngrok today, and then this. Magic!!

I installed the cli via homebrew as instructed on macOS (Mojave)

Running `stripe login` works great ... browser opens and I get an authenticated message.

```bash
$ stripe login
Your pairing code is: nifty-reform-solid-excite
Press Enter to open up the browser (^C to quit)
> Done! The Stripe CLI is configured for Tito with account id user_...```

but when I run `stripe listen`, I just get a 500 every time:
```bash
$ stripe listen --forward-to https://checkout.dev.tito.io/incoming_webhooks
⣽ Getting ready... [Tue, 16 Jul 2019 23:22:58 IST] FATAL Error while authenticating with Stripe: Authorization failed, status=500, body={
  "error": {
    "message": "An unknown error occurred",
    "type": "api_error"
  }
}
```

Not much more I can do from here!

**Comment by paulca** [comment]
(I tried removing the contents of `~/.config/stripe` and re-authenticating, but still not working.

**Comment by paulca** [comment]
(I also tried adding a key manually, but same result)

**Comment by ob-stripe** [comment]
Hey @paulca! I'm fairly sure this is a backend issue. I'm looking into it, will update once I figure out what's going on.

**Comment by ob-stripe** [comment]
It is indeed a backend issue. We'll push a fix ASAP.

**Comment by paulca** [comment]
Much obliged!

Paul Campbell
paul@hypertiny.ie
- - - - - - - - - - - - - - - - - - -
web http://hypertiny.ie
blog http://www.pabcas.com
twitter http://www.twitter.com/paulca
github http://www.github.com/paulca
phone +353 87 914 8162
- - - - - - - - - - - - - - - - - - -

**Comment by ob-stripe** [comment]
The issue should be fixed, please try running `stripe listen ...` again.

(Closing the issue, but let me know if it doesn't work!)

**Comment by PietroLodiRizzini** [comment]
i am encountering the same issue:

```
(base) pietrolodirizzini@Pietro-MBP % stripe listen --forward-to localhost:8000/stripe/webhook
[Fri, 06 Jun 2025 23:56:29 CEST] FATAL Error while authenticating with Stripe: Authorization failed, status=500, body={
  "error": {
    "message": "An unknown error occurred",
    "type": "api_error"
  }
}

```

i have tried to logout and log bak in a couple of times but with no luck
