### ISSUE TITLE
Webhook signing secret changes too often

### ISSUE THREAD

**Issue by wwahammy** [stripe/stripe-cli#361]
### Issue
Every few days, the Stripe CLI webhook signing secret changes. I haven't noticed an obvious pattern to it. I wouldn't expect it to since my CLI is properly logged in and its login hasn't expired.

### Expected Behavior
The CLI's webhook secret shouldn't change until the CLI's login expires or the CLI is logged out.

### Steps to reproduce
Wait a few days? It's not clear to me when it's happening.

### Environment
Linux

**Comment by ob-stripe** [comment]
@wwahammy Thanks for the report! This is an unforeseen side-effect of a recent change on our end. I'll see what we can do to fix it.

**Comment by tomer-stripe** [comment]
Hey @wwahammy, we disabled the secret rotation for the CLI! Let us know if you still hit any issues with that

**Comment by zachsents** [comment]
Did something cause a regression of this? It rotates
