### ISSUE TITLE
stripe -v Support

### ISSUE THREAD

**Issue by fishcharlie** [stripe/stripe-cli#37]
I think it'd be awesome to see a shortcut to run `stripe -v` and have the same behavior as `stripe --version`.

**Comment by homemadePopcorn** [comment]
stripe.exe was labelled as a suspicious file by my anti-virus software.  I can add an exception to that file on my firewall but just thought I would write the issue down.

**Comment by tomer-stripe** [comment]
@fishcharlie we'll take a look at adding that!

@homemadePopcorn I'm going to create a separate issue for that to see if there are any changes we should make to handle that better.

**Comment by tomer-stripe** [comment]
@fishcharlie just opened a PR for this! Sorry this took so long to get to, the whole time has been really focused on adding a bunch of cool new features :D
