### ISSUE TITLE
Play nice when output is piped to a pager such as `less`

### ISSUE THREAD

**Issue by fred-stripe** [stripe/stripe-cli#370]
### Problem

Sometimes the output from `stripe` is long, and I want to page through it with `less` rather than grab the mouse. I also like color highlighting, so I have an alias that always passes `--color=on` and pipes the output to `less -R` (this is how I use [Silver Searcher](https://github.com/ggreer/the_silver_searcher), etc).

However, it seems that stripe-cli still outputs the animation even when the output is not a tty, which results in a bunch of extra fluff at the top:

![Screen Shot 2020-02-11 at 11 45 30 AM](https://user-images.githubusercontent.com/23065173/74259720-59ad8100-4cc6-11ea-9f4e-af7ce7b3b69b.png)

### Feature

Minimal solution: detect if the output's a tty and disable animation when writing to a pipe.

Fancy solution: like some other Unix utilities, stripe-cli could detect PAGER and use that if the output is longer than the terminal's number of rows (or some threshold like 40 rows).

This is tricky, though, because you can't know a priori whether or not a pager supports color control sequences like less -R (-R is the "Raw" option to less), since you can't use the usual mechanisms to detect TTY features. The approach I've seen other tools take is to disable color when writing to a pipe unless explicitly asked for on the command line with --color=yes (`ls` and `ag` ~work like this for example).

Thanks as always for a great tool—this seems a bit self-congratulatory coming from another Stripe, but this tool genuinely makes my day of creating, running, and testing Stripe integrations easier—and for that I am grateful. Cheers!

**Comment by polybuildr** [comment]
Hi @fred-stripe, I've taken a stab at this in #479 if you're interested! :)

**Comment by bwang-stripe** [comment]
#479, which disables animation for pipes, is merged in v1.4.6, so I'm marking this as closed. Thanks @polybuildr!
