### ISSUE TITLE
Stripe doesn't stop listening after quitting

### ISSUE THREAD

**Issue by andris-sevcenko** [stripe/stripe-cli#39]
After quitting stripe CLI using `^C`, it still remains in the process list, listening and polluting output on receiving webhook. (This also explains the duplicate lines in the output of #38)

```
~: stripe listen --forward-to http://<REDACTED>
[1] 14685
 ~: > Ready! Your webhook signing secret is whsec_<REDACTED> (^C to quit)
[^C]
 ~: ps
  PID TTY           TIME CMD
<REDACTED>
14685 ttys001    0:00.15 stripe listen --forward-to <REDACTED>
 ~:
```

**Comment by andris-sevcenko** [comment]
Just realized that it immediately goes into the background. If I bring it back using `fg` and then hit `^C` it ends, as expected.

Not sure if it's the intended behavior, though? If it is, it is probably worth mentioning in the docs.

**Comment by andris-sevcenko** [comment]
Also, for posterity, I'm an idiot. I had an ampersand in the target URL, causing the link to be invalid and, of course, for the stripe CLI app to go into the background.

Sorry.

**Comment by ob-stripe** [comment]
No worries at all! Thanks for giving the CLI a try :)
