### ISSUE TITLE
Stripe CLI: Add account.updated event

### ISSUE THREAD

**Issue by ilken** [stripe/stripe-cli#407]
### Problem
_What are you trying to do?_

As part of the Stripe Capabilities upgrade, we are testing the new ID verification but account.updated webhook is not listed on the supported events (https://github.com/stripe/stripe-cli/wiki/trigger-command#supported-events)

**Comment by jefcoserrca** [comment]
did you resolve it?

**Comment by vahidvdn** [comment]
+1

**Comment by JamesTPF** [comment]
Duplicate of https://github.com/stripe/stripe-cli/issues/345

**Comment by pepin-stripe** [comment]
closed since duplicate for #345
