### ISSUE TITLE
Add logout command

### ISSUE THREAD

**Issue by hdoupe** [stripe/stripe-cli#408]
### Problem
I'm trying to clear the credentials for my local stripe cli install, but there doesn't appear to be a logout command.

### Feature
A stripe logout command seems like it would be very helpful. Many other cli's offer this option:

```
$ heroku logout
Logging out... done
```
```
$ stripe logout
```

### Examples
My current use case is that I set up the stripe cli account and it automatically linked my pc up with a client's test webhooks. I would like to remove my device from the webhooks page.

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-cli/releases/tag/v1.4.0, in #430

**Comment by hdoupe** [comment]
Thanks for implementing this @richardm-stripe!

**Comment by richardm-stripe** [comment]
Ha, credit goes to @ianjabour-stripe! I'm just closing issues.
