### ISSUE TITLE
Installation issue - Scoop

### ISSUE THREAD

**Issue by afalzon** [stripe/stripe-cli#416]
Hi,
I am a bit of a noob with scoop.
When I tried to install I got this: "Can't shim 'stripe.exe.exe': File doesn't exist"

Verbose:
`PS C:\Windows\system32> scoop install stripe
Installing 'stripe' (1.3.9) [64bit]
stripe_1.3.9_windows_x86_64.zip (6.0 MB) [====================================================================] 100%
Checking hash of stripe_1.3.9_windows_x86_64.zip ... ok.
Extracting stripe_1.3.9_windows_x86_64.zip ... done.
Linking ~\scoop\apps\stripe\current => ~\scoop\apps\stripe\1.3.9
Creating shim for 'stripe.exe'.
Can't shim 'stripe.exe.exe': File doesn't exist.`

Any thoughts or tips how to get this resolved?

**Comment by tomer-stripe** [comment]
Looks like it's adding an extra `.exe` to it. I'll file a ticket internally on our side to check this out.

**Comment by mortenoc** [comment]
How do you install a previous version of stripe CLI with scoop? 
`scoop install stripe@1.3.8` does not work

Stripe CLI is broken right now with scoop on Windows

**Comment by tomer-stripe** [comment]
@afalzon @mortenoc sorry about that, merged a PR to fix the scoop issues here: https://github.com/stripe/scoop-stripe-cli/pull/2

**Comment by tomer-stripe** [comment]
Looks like it was an issue upstream with goreleaser so hopefully this won't reoccur: https://github.com/goreleaser/goreleaser/commit/dec22cf0c8a6464390ea26b42086d242e396ecda
