### ISSUE TITLE
Unable to run stripe login command behind company proxy server

### ISSUE THREAD

**Issue by osparamatrix** [stripe/stripe-cli#421]
### Issue
I have been integrating stripe connect separate charges and transfers way to charge customers. I was able to charge the customer successfully. Then I implemented the webhook that would transfer amounts after the platform would have balance. So I installed stripe cli to receive events of successful pay. But after installation, I tried running the stripe login command and it gives a timeout error.
Also I have given the test secret api key for the stripe account.

### Expected Behavior
I expect the cli to login and then make it listen on the events by running the listen command.

### Steps to reproduce
Install stripe cli on windows.
Ensure all requests go through your company proxy server

### Traceback

stripe login -i
Enter your API key:
Your API key is: sk_test_********************syFs
How would you like to identify this device in the Stripe Dashboard? [default: PTW10SPSD146]
> Error verifying the CLI was setup successfully: Get "https://api.stripe.com/v1/account": dial tcp 13.228.126.182:443: i/o timeout

### Environment
Windows 10

Kindly direct me in the direction of docs that help me configure stripe cli to work behind proxy.

**Comment by tomer-stripe** [comment]
Hey @osparamatrix are you able to make any request with the CLI on your device? The interactive login doesn't make any kind of special request to Stripe.

Could you try `stripe customers create --api-key=sk_test_...`?

**Comment by osparamatrix** [comment]
Hi @tomer-stripe , I have tried only the login and listen commands of stripe-cli like I mentioned before on my device and they both gave the timeout errors.
Also when I tried the login command on a machine that wasn't behind a proxy at home, it worked without errors displaying the account id.

> Could you try stripe customers create --api-key=sk_test_...?

Also could you elaborate on the reason why I should run the customers create command? I read the docs and cli wiki and could not find much explanation.

**Comment by ob-stripe** [comment]
@osparamatrix `stripe customers create` is just a quick way of testing an API request.

The CLI should respect the `HTTP_PROXY` / `HTTPS_PROXY` environment variables. Can you try setting one of those to point to your corporate proxy, and test the CLI again?

**Comment by osparamatrix** [comment]
Hi @ob-stripe , I tried your suggestion this morning and the login was successful. But then when I tried running the listen command to forward the events to my server, it gave the below error:-

> >stripe listen --log-level debug --forward-to localhost:9009/hooks
> . Checking for new versions... [Fri, 17 Apr 2020 10:14:30 IST] DEBUG Get "https://api.github.com/repos/stripe/stripe-cli/releases/latest": EOF
> [Fri, 17 Apr 2020 10:14:30 IST] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
> . Getting ready... [Fri, 17 Apr 2020 10:14:30 IST] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe display_connect_filter_warning=false reconnect_delay=77 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{42}_KRlrZZZfG54DhJcRmpUPZJbiHUI5dirytQ5jEMYmSldcxvlj5h websocket_url=wss://stripe-cli.stripe.com/subscribe/acct_1A7KNuDF6gFniY52
> [Fri, 17 Apr 2020 10:14:30 IST] DEBUG websocket.client.Run: Attempting to connect to Stripe
> [Fri, 17 Apr 2020 10:14:30 IST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1A7KNuDF6gFniY52?websocket_feature=webhook-payloads
> o Getting ready... [Fri, 17 Apr 2020 10:14:32 IST] DEBUG websocket.Client.connect: Websocket connection error error=websocket: bad handshake
> [Fri, 17 Apr 2020 10:14:32 IST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
> . Getting ready... [Fri, 17 Apr 2020 10:14:42 IST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1A7KNuDF6gFniY52?websocket_feature=webhook-payloads
> o Getting ready... [Fri, 17 Apr 2020 10:14:43 IST] DEBUG websocket.Client.connect: Websocket connection error error=websocket: bad handshake
> [Fri, 17 Apr 2020 10:14:43 IST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
> . Getting ready... [Fri, 17 Apr 2020 10:14:53 IST] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1A7KNuDF6gFniY52?websocket_feature=webhook-payloads
> o Getting ready... [Fri, 17 Apr 2020 10:14:54 IST] DEBUG websocket.Client.connect: Websocket connection error error=websocket: bad handshake
> [Fri, 17 Apr 2020 10:14:54 IST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
> @ Getting ready... [Fri, 17 Apr 2020 10:14:57 IST] DEBUG proxy.Proxy.Run: Ctrl+C received, cleaning up...
> [Fri, 17 Apr 2020 10:14:57 IST] FATAL Aborting
> 

I see that the websocket connection is failing. But then what else do I need to configure on my end? Or is there any port that needs to be open? Any help would be appreciated.

**Comment by ob-stripe** [comment]
@osparamatrix Setting the environment variable should be the only thing that's needed. It's possible your proxy interferes with the websocket connection though.

Can you try going to https://www.websocket.org/echo.html (using a browser configured to use the firewall) and check if the websocket connection is working there? You would click "Connect", then "Send", and check if the log window displays "RECEIVED: Rock it with HTML5 WebSocket".

**Comment by osparamatrix** [comment]
Hi @ob-stripe ,
You were right about the fact that the websocket connection was not working. I coordinated with our infrastructure team and they configured the firewall to allow for websocket connections. Now I am able to both login and listen on stripe events in the test environment via stripe cli. 
Thank you very much for your help and patience. 👍

**Comment by ob-stripe** [comment]
Awesome, glad you were able to make it work! 🎉
