### ISSUE TITLE
Unable to run stripe listen

### ISSUE THREAD

**Issue by charlie632** [stripe/stripe-cli#422]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
I followed the instructions to setup and use the CLI. I managed to login correctly and so, but when I run `stripe listen` it is stuck on "Getting ready". I added  `--skip-verify --log-level=debug` flags and the response is the following:

![image](https://user-images.githubusercontent.com/8704336/79474993-bd0ca580-7fcc-11ea-9554-682c41cddb4c.png)

I tried also login by using 

`stripe login -i`

And same result

I can use commands like `stripe customers create` without any problem.

### Expected Behavior

To be able to use stripe listen
### Steps to reproduce

`stripe login`

`stripe listen`

### Environment

OS: MAC Catalina
CLI version: 1.3.10

**Comment by tomer-stripe** [comment]
Hmm, do you know if you're running behind a firewall? Are you running through docker?

Does running `stripe listen` with the `--no-wss` flag work?

**Comment by charlie632** [comment]
@tomer-stripe I'm not sure about the Firewall. I will check.

I'm not running through docker.

This is the response from the `--no-wss` flag:

`DEBUG websocket.Client.connect: Websocket connection error error=websocket: bad handshake`

**Comment by charlie632** [comment]
I disabled Firewall on my Mac and I get the same error as above.

**Comment by tomer-stripe** [comment]
@charlie632 how did you install the CLI? The same issue came up in #423 and they said that compiling from source resolved the issue. Wondering if something's happening with our CI process.

**Comment by Chucky122** [comment]
Hello Tomer strip I go with intuition ha ha. Good luck on your developing 

Envoyé de mon iPhone Charles

**Comment by charlie632** [comment]
@tomer-stripe I installed it via `brew install stripe/stripe-cli/stripe`. I will try building it from source

**Comment by charlie632** [comment]
No luck. Same error 😭

**Comment by ob-stripe** [comment]
@charlie632 Are you using a home/personal connection, or are you on a corporate network?

**Comment by nilaeus** [comment]
I installed the Stripe CLI from Homebrew, and got the same error. I uninstalled that and installed it from source, same error.
This issue suggests `--no-wss` but that was the same as running without it for me.
The error is always `Websocket connection error error=dial tcp: i/o timeout`, which is different.
I'm running this on my mac at home, without any firewalls.

**Comment by tomer-stripe** [comment]
@nilaeus to confirm, you're also seeing the `x509` certificate error? Could you let us know what CLI version you're running and what version of macOS you're on?

**Comment by nilaeus** [comment]
I'm running MacOS Catalina 10.15.4, `strive -v` 1.3.10
Logging in works fine, but connecting to the websocket times out.

![Screen Shot of commands](https://user-images.githubusercontent.com/32454680/80228606-dc32b500-8614-11ea-9be9-cbd32ea24b9b.png)

**Comment by ob-stripe** [comment]
@charlie632 Could you run `GODEBUG="x509roots=1" stripe listen` and share the output here?

@nilaeus This looks to be a different error, mind opening a new issue about it?

**Comment by nilaeus** [comment]
#433

**Comment by charlie632** [comment]
Upgrading to `1.4.0` solves this issue. Closing it. 

Thanks for all the support!
