### ISSUE TITLE
Webhooks testing inconsistencies whilst debugging using Stripe CLI and event triggers

### ISSUE THREAD

**Issue by scottynorris** [stripe/stripe-cli#429]
The problem is that if I trigger the same event multiple times, I get different results.

I provided a detailed report here:

https://stackoverflow.com/questions/61404353/webhooks-testing-inconsistencies-whilst-debugging-using-stripe-cli-and-event-tri

Thanks for looking.

**Comment by scottynorris** [comment]
A commenter on stack noticed this is caused by webhooks responding with 4xx. My be worth adding this to the docs? I wrongly assumed a 4xx was nothing to worry about because I wouldn't need it when live.

**Comment by tomer-stripe** [comment]
Hey @scottynorris! I'm not sure I understand. Triggering events makes real objects so some of the data will be different (like timestamps). Depending on the event itself, there might be additional objects too.

Looking at the php code in stackoverflow, it seems like the pasted code itself is raising the 400, not the CLI.

You should think about 400s in a live application, check out this page for some more info on error codes: https://stripe.com/docs/error-codes

**Comment by scottynorris** [comment]
Hey Tomer! It was the inconsistent events that was strange. Sometimes two would trigger, sometimes four. It would also play out as expected the first time after listening, however after that was a dice roll. It seemed the 4xx codes were preventing the whole series of events from running?

**Comment by ob-stripe** [comment]
Hi @scottynorris. It looks like you got your answer on StackOverflow, but to clarify, the way `stripe trigger <event_type>` works is that it sends regular API requests that will result in the event you request being generated.

Depending on the event type, other events might also be generated as side effects. For instance, triggering `payment_intent.succeeded` also triggers a `payment_intent.created` and a `charge.succeeded` events.

You can set the CLI to only forward specific event types with the `--events` (or `-e`) flag, e.g.:
```sh
$ stripe listen --forward-to localhost:8888/my-endpoint.php --events payment_intent.succeeded
```

This way, the other events would be filtered and not sent to your endpoint. This is equivalent to subscribing to only certain event types when creating a regular endpoint in the Stripe dashboard.

Closing this issue, but feel free to reply!
