### ISSUE TITLE
Environmental variables do not resolve in fixtures for "path"

### ISSUE THREAD

**Issue by FilmCoder** [stripe/stripe-cli#432]
### Issue
Environmental variables do not resolve in "paths" in fixtures

### Expected Behavior
The environmental variable should load properly.

### Steps to reproduce

1. Create a customer on the stripe dashboard
2. In your project, create a .env file, and add STRIPE_TEST_CUSTOMER=cus_1231231234 but use the actual customer id.

3.
Make this fixture:
```
{
    "_meta": {
        "template_version": 0
    },
    "fixtures": [
        {
            "name": "customer_updated",
            "path": "/v1/customers/${.env:STRIPE_TEST_CUSTOMER}",
            "method": "post",
            "params": {
                "source": "tok_visa"
            }
        }
    ]
}
```

4. Run it with `stripe fixtures path_to_fixture.json`
5. Notice error:

```$ stripe fixtures stripe/fixtures/invoice.payment_succeeded.json
Setting up fixture for: customer_updated
Request failed, status=404, body={
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: ${.env:STRIPE_TEST_CUSTOMER}",
    "param": "id",
    "type": "invalid_request_error"
  }
}
```

6. As you can see, the env variable is not resolving.

### Environment
Windows
Stripe CLI version 1.3.11

### Note
The env variable resolves properly for me when it's not in a "path" parameter.  For instance, it works fine in "params".  For now, I will have to hard code ids into my JSON fixtures in certain spots to get around this bug.

**Comment by tomer-stripe** [comment]
Thanks for filing the bug! @thorsten-stripe would you be able to take a look?

**Comment by ianjabour-stripe** [comment]
@tomer-stripe I took a look at this today. Should have a PR up soon.
