### ISSUE TITLE
Stripe connection failure with i/o timeout

### ISSUE THREAD

**Issue by nilaeus** [stripe/stripe-cli#433]
### Issue
I was trying to set up a local Websocket listener, but the `stripe listen` doesn't work.

### Expected Behavior
It should start listening.

### Steps to reproduce
1. `brew install stripe/stripe-cli/stripe`
2. `stripe login`
3. `stripe listen`

### Traceback
![80228606-dc32b500-8614-11ea-9be9-cbd32ea24b9b](https://user-images.githubusercontent.com/32454680/80428437-7d3c9c80-88af-11ea-945b-bde068d079c4.png)

### Environment
MacOS Catalina 10.15.4
Stripe version 1.13.11

**Comment by ob-stripe** [comment]
@nilaeus Can you go to https://www.websocket.org/echo.html (from the same machine that you're running the CLI from), click the "Connect" then "Send" buttons, and verify that the Log window displays "RECEIVED: Rock it with HTML5 WebSocket"?

**Comment by nilaeus** [comment]
It does

<img width="797" alt="Screen Shot 2020-04-27 at 6 59 36 PM" src="https://user-images.githubusercontent.com/32454680/80432253-44092a00-88b9-11ea-8fee-fa5c8189a9fa.png">

**Comment by ob-stripe** [comment]
Thanks. So this rules out a firewall that interferes with websocket connections.

Can you running `curl -v https://stripe-cli.stripe.com/`? (This should return a 404, but I want to check if the connection is established at least.)

**Comment by nilaeus** [comment]
404
![Screen Shot 2020-04-27 at 10 25 38 PM](https://user-images.githubusercontent.com/32454680/80443993-23030200-88d6-11ea-8754-b8d0486805b4.png)

**Comment by ob-stripe** [comment]
Very strange 🤔 

Just to be 100% sure:
- can you confirm you're not behind any kind of corporate proxy?
- can you confirm you're not using any kind of local firewall (e.g. Little Snitch)?
- can you check if any of the following environment variables is set?
    - `HTTP_PROXY`
    - `HTTPS_PROXY`
    - `http_proxy`
    - `https_proxy`

**Comment by nilaeus** [comment]
![Ran "env" command](https://user-images.githubusercontent.com/32454680/80547854-da535380-897e-11ea-9d69-aafce2ab7fa4.png)
<img width="754" alt="https://www.whatismyip.com/proxy-check/" src="https://user-images.githubusercontent.com/32454680/80547852-d9babd00-897e-11ea-9654-7eaa7a7a2974.png">
<img width="594" alt="My Mac's Firewall" src="https://user-images.githubusercontent.com/32454680/80547853-d9babd00-897e-11ea-9bb5-d7fbd8287762.png">
<img width="591" alt="My network firewall IPv6" src="https://user-images.githubusercontent.com/32454680/80547845-d7586300-897e-11ea-8c4b-c0918be91b8c.png">
<img width="581" alt="Network firewall IPv4" src="https://user-images.githubusercontent.com/32454680/80547849-d8899000-897e-11ea-84af-18717cdfb805.png">

**Comment by ob-stripe** [comment]
Thanks. Unfortunately I have no idea what's causing the websocket connection to time out on your laptop :(

If you're willing to debug this further, here's something else you can try:
1. Install [websocat](https://github.com/vi/websocat) (`brew install websocat`)
2. Run `stripe listen --log-level debug`, then Ctrl+C once it starts reporting timeouts
3. Run `websocat wss://stripe-cli.stripe.com/subscribe/acct_123 -H "Websocket-Id: cliws_{123}_456"`, replacing `acct_123` and `cliws_{123}_456` with the `websocket_url` and `websocket_id` values from `stripe listen`'s output

If the command just hangs without any output, it probably means the connection was established. You can verify this by generating some traffic, e.g. by running `stripe trigger payment_intent.created` in another terminal.

If this works, it would mean that it's the CLI binary specifically that cannot establish a websocket connection.

It it doesn't, it means that there's some networking issue prevening the websocket connection to stripe-cli.stripe.com.

I completely understand if this is too much trouble, and apologize for the inconvenience -- the primary goal of the CLI is to enable a better development experience, and this is anything but.

**Comment by nilaeus** [comment]
I'm more than happy to help, stripe is an awesome tool!
It worked, so I think that it's the CLI binary.

**Comment by ob-stripe** [comment]
Dang, I was hoping we could blame this on [ghosts](https://xkcd.com/2259/) or something.

I suppose the next step would be to try and compile the CLI from source yourself:
- install Go if you don't have it already: `brew install go`
- clone the repo: `go get -v -u github.com/stripe/stripe-cli/...`
- move into the cloned repo: `cd ~/go/src/github.com/stripe/stripe-cli`
- build the binary: `make build`

Then try running `./stripe listen --log-level debug` and see if it works any better.

**Comment by nilaeus** [comment]
It worked, and it was so much faster! Normally it took 30 seconds to get to the error, but now it works and listens instantly.
![Screen Shot 2020-04-29 at 1 32 00 PM](https://user-images.githubusercontent.com/32454680/80633383-4b961380-8a1e-11ea-9bc7-61aa6353a22d.png)

**Comment by ob-stripe** [comment]
Progress 🎉 

The main/only difference between installing from brew and compiling from source yourself is that the macOS binary from brew is cross-compiled from a Linux machine. This shouldn't make a difference, though I know of at least one case where it does (specifically, DNS resolution: https://github.com/golang/go/issues/12524).

I don't think the issue you're seeing with the brew-installed `stripe` binary is a DNS one, but just to make sure, can you try the following commands:

```
$ GODEBUG=netdns=go+1 ./stripe listen --log-level debug
$ GODEBUG=netdns=cgo+1 ./stripe listen --log-level debug
```

and see if one of them fails with the same timeout error as the brew-installed `stripe` binary?

**Comment by nilaeus** [comment]
`cgo+1` worked, but `go+1` had the same failure.

**Comment by ob-stripe** [comment]
Okay, so the time out error message was just very misleading and it was a DNS issue after all 😥 

You probably have something in your environment that causes the DNS resolution to fail when using the pure Go resolver (the `GODEBUG=netdns=go` one, the only available when using the brew-installed `stripe` binary due to cross-compiling) but succeed when using the native macOS resolver (the `GODEBUG=netdns=cgo` one).

I think I found a way to work around this cross-compiling issue, but do you mind sharing the output of these commands?

```
$ cat /etc/resolv.conf
$ ls -l /etc/resolver
```

**Comment by nilaeus** [comment]
🤔
![Screen Shot 2020-04-29 at 4 42 33 PM](https://user-images.githubusercontent.com/32454680/80649885-7725f780-8a38-11ea-83ff-cd52adc361f9.png)

**Comment by ob-stripe** [comment]
And these ones?

```
$ dig stripe-cli.stripe.com @192.168.0.1
$ dig stripe-cli.stripe.com @1.1.1.1
```

**Comment by nilaeus** [comment]
![Screen Shot 2020-04-29 at 4 58 31 PM](https://user-images.githubusercontent.com/32454680/80651004-afc6d080-8a3a-11ea-80e9-0f9990f0af18.png)

**Comment by ob-stripe** [comment]
Alright, thanks.

I just released v1.3.12 which should fix the issue. Can you upgrade via brew and confirm whether the new version works for you?

**Comment by nilaeus** [comment]
🎉 It works!
Thank you for your time.
I'll leave it to you to close the issue, but it's all good now.

**Comment by ob-stripe** [comment]
Awesome! Thanks a lot for your patience and your help getting to the bottom of this, much appreciated!

**Comment by deckeraa** [comment]
I'm hitting this issue with 1.4.0 and 1.4.1 of the pre-built binary.
Building from source results in it connecting eventually after hitting a couple of <code>DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
</code> messages.

Here's the result of <code>./stripe listen --log-level debug</code> after a few minutes:
```
aaron@aaron-ThinkPad-A475:~/go/src/github.com/stripe/stripe-cli$ ./stripe listen --log-level debug
[Thu, 28 May 2020 13:00:28 CDT] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⢿ Getting ready... [Thu, 28 May 2020 13:00:44 CDT] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe display_connect_filter_warning=false reconnect_delay=83 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{5569}_[REDACTED] websocket_url=wss://stripe-cli.stripe.com/subscribe/acct_[REDACTED] 
[Thu, 28 May 2020 13:00:44 CDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Thu, 28 May 2020 13:00:44 CDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cl⣯ Getting ready... [Thu, 28 May 2020 13:00:54 CDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
⣽ Getting ready... [Thu, 28 May 2020 13:01:04 CDT] DEBUG websocket.Client.connect: Dialing websocket > Ready! Your webhook signing secret is whsec_[REDACTED]  (^C to quit)
[Thu, 28 May 2020 13:01:18 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:01:18 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:01:27 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:01:27 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:01:36 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:01:36 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:01:45 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:01:45 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:01:54 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:01:54 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:02:03 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:02:03 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:02:12 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:02:12 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:02:21 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:02:21 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:02:30 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:02:30 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:02:32 CDT] DEBUG websocket.Client.Run: Resetting the connection
[Thu, 28 May 2020 13:02:32 CDT] DEBUG websocket.Client.writePump: stopWritePump
[Thu, 28 May 2020 13:02:32 CDT] DEBUG websocket.Client.readPump: stopReadPump
[Thu, 28 May 2020 13:02:32 CDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Thu, 28 May 2020 13:02:32 CDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_[REDACTED] ?websocket_feature=webhook-payloads
[Thu, 28 May 2020 13:02:42 CDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 28 May 2020 13:02:42 CDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
[Thu, 28 May 2020 13:02:52 CDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_[REDACTED] ?websocket_feature=webhook-payloads
[Thu, 28 May 2020 13:03:02 CDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout
[Thu, 28 May 2020 13:03:02 CDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
[Thu, 28 May 2020 13:03:12 CDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_[REDACTED] ?websocket_feature=webhook-payloads
[Thu, 28 May 2020 13:03:18 CDT] DEBUG websocket.client.connect: Connected!
[Thu, 28 May 2020 13:03:27 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:03:27 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:03:36 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:03:36 CDT] DEBUG websocket.Client.readPump: Received pong message
[Thu, 28 May 2020 13:03:45 CDT] DEBUG websocket.Client.writePump: Sending ping message
[Thu, 28 May 2020 13:03:45 CDT] DEBUG websocket.Client.readPump: Received pong message
```

I also took did the DNS debug steps from above:
```
aaron@aaron-ThinkPad-A475:~$ cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "systemd-resolve --status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0
aaron@aaron-ThinkPad-A475:~$ dig stripe-cli.stripe.com @127.0.0.53

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> stripe-cli.stripe.com @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64783
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;stripe-cli.stripe.com.         IN      A

;; ANSWER SECTION:
stripe-cli.stripe.com.  149     IN      CNAME   stripe.com.
stripe.com.             7       IN      A       54.187.119.242

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu May 28 12:55:49 CDT 2020
;; MSG SIZE  rcvd: 80

aaron@aaron-ThinkPad-A475:~$ 
```

**Comment by malbaugh** [comment]
> @nilaeus Can you go to https://www.websocket.org/echo.html (from the same machine that you're running the CLI from), click the "Connect" then "Send" buttons, and verify that the Log window displays "RECEIVED: Rock it with HTML5 WebSocket"?

Is there another method for testing this? Websocket.org is no longer in service.
