### ISSUE TITLE
Include Setup Instructions with `stripe completion` Command

### ISSUE THREAD

**Issue by ianjabour-stripe** [stripe/stripe-cli#446]
### Problem
Currently when a user runs `$ stripe completion` the CLI generates the completion file and then just prints:

```
Detected zsh, generating zsh completion file: stripe-completion.zsh
```
(or bash alternative)

At this point the user needs to do a bit more work to get the autocompletion moved and source properly. Unfortunately we don't provide any further instructions on what those steps are.

### Feature
It would be fantastic if we included the appropriate installation instructions  when `$ stripe completion` is run. We could pull the step by step guide from the new docs coming at `/docs/stripe-cli/configuration#autocompletion`.

### Examples
```bash
$ stripe completion
Detected zsh, generating zsh completion file: stripe-completion.zsh

Suggested next steps:
----------------------
1. Move `stripe-completion.zsh` to the correct location:
    mkdir -p ~/.stripe
    mv stripe-completion.zsh ~/.stripe

2. Add the following lines to your `.zshrc` enabling shell completion for Stripe:
    fpath=(~/.stripe $fpath)
    autoload -Uz compinit && compinit -i

3. Source your `.zshrc` or open a new terminal session:
    source ~/.zshrc
```

> The steps shown in this example are pulled from the docs @auchenberg is currently working on releasing. We'd want the suggested next steps to follow whatever the docs end up being at: `/docs/stripe-cli/configuration#autocompletion`

**Comment by richardm-stripe** [comment]
Fixed in #450, in 1.4.3.
