### ISSUE TITLE
Trigger webhook with with particular ID

### ISSUE THREAD

**Issue by karandeepSJ** [stripe/stripe-cli#447]
### Background
I have a website where I am using checkout to subscribe users to a plan. When the payment is completed, I want to catch the `checkout.session.completed` webhook to update the user table in my database so that the user can access the website's premium features. I store the checkout session id in my database with the logged in user when I create the session, so that I can find the user during the event using the id.

### Problem
I want to test this locally. After I redirect to the checkout URL, how can I use the session id to trigger the `checkout.session.completed`? `stripe trigger checkout.session.completed` always creates a new checkout session, but I want to trigger the webhook for an existing session, so that I can retrieve the user from my db using the session id successfully.

**Comment by ThomasLandauer** [comment]
@karandeepSJ I have the same problem. Did you close this cause you found a solution? Which? Or did you give up... ;-)
