### ISSUE TITLE
There are no inline links in stripe listen output when running in VS Code terminal

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/stripe-cli#457]
### Issue

There's are no inline links in `stripe listen` output.

### Expected Behavior
E.g. in iTerm, with working links: 

![image](https://user-images.githubusercontent.com/53238203/83690883-653ef380-a5a6-11ea-975d-206229cdecfe.png)

No links in VSCode terminal: 

![image](https://user-images.githubusercontent.com/53238203/83690968-86074900-a5a6-11ea-863f-63136ed1fd62.png)

### Steps to reproduce
_What are the steps we can take to reproduce this and verify it's fixed?_
1. Open VS Code
2. Run `stripe listen` in terminal

### Environment
MacOS

**Comment by auchenberg-stripe** [comment]
Seems to be a general xterm.js issue, as Hyper terminal doesn't render either:

<img width="1644" alt="Screen Shot 2020-06-03 at 2 33 04 PM" src="https://user-images.githubusercontent.com/53238203/83691532-2f4e3f00-a5a7-11ea-94b5-263231fc7899.png">

**Comment by tomer-stripe** [comment]
@auchenberg-stripe https://github.com/xtermjs/xterm.js/issues/1134 is still open and it doesn't seem like it's completely supported yet so I think this might be upstream of us.

**Comment by auchenberg** [comment]
You are right. Its still open, and upstream. @tomer-stripe

**Comment by richardm-stripe** [comment]
Closing as it doesn't represent a bug in the stripe-cli
