### ISSUE TITLE
bug for stripe_1.4.1.windows_86_64.34

### ISSUE THREAD

**Issue by LilianeM45** [stripe/stripe-cli#463]
I couldn't open the file because my computer is a windows 8.1 32bits.
Please send me a stripe CLI for windows 8.1 thanks.

**Comment by richardm-stripe** [comment]
Hello @LilianeM45, thanks for reporting this. We have not historically supported or provided binaries for 32-bit windows, so I am reclassifying this as a feature request.

There seem to be others #464, #460 recently reporting this for the first time, so I am curious: do you know if 32-bit Windows previously able to run the 64-bit binary somehow in previous versions? Is this your first time attempting to run the Stripe CLI?

**Comment by ob-stripe** [comment]
As of v1.4.2, we now provide 32-bit builds for Windows.

@LilianeM45 @victor-sarabia Can you try downloading https://github.com/stripe/stripe-cli/releases/download/v1.4.2/stripe_1.4.2_windows_i386.zip and report here whether it works for you or not?

**Comment by richardm-stripe** [comment]
Closing, as we have now added support. @LilianeM45 @victor-sarabia please reopen if the difficulty persists.

**Comment by ashiefk** [comment]
Hi I tried to run 32 bit stripe cli installation on my computer but it shows it should run on cmd.exe. I tried to run in cmd start stripe.exe but it doesn't show up. Can you please help?
![image](https://user-images.githubusercontent.com/13694089/232003513-c681af89-0844-4222-8514-8b37444031f9.png)
