### ISSUE TITLE
Products Create Unknown Flag Attributes

### ISSUE THREAD

**Issue by hatoro** [stripe/stripe-cli#474]
### Problem
I am trying to create a product with attributes

### Feature
Add attributes to list of request parameters for the command `stripe products create`

### Examples
Please add the ability to add metadata as well

**Comment by bwang-stripe** [comment]
You should be able to pass both `attributes` and `metadata` request parameters via the `--data`/`-d` flag, which you can use to set any writable request parameter by name.

The Stripe docs page [here](https://stripe.com/docs/api/metadata?lang=cli) shows how to use `-d` to add a metadata field to a `stripe charges create` command.

For your use case (creating a product with attributes and metadata), this might look like:
`stripe products create --name "myProduct" -d "attributes[]"="color" -d "attributes[]"="size" -d "metadata[myField]"="myValue"`
