### ISSUE TITLE
Virus reported in latest release

### ISSUE THREAD

**Issue by withinboredom** [stripe/stripe-cli#481]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

This is probably a false positive related to #379 but I'm not sure you all monitor old closed issues and would like to make sure you're aware of it.

### Issue
_Describe what happened and what you were trying to do_
Downloaded the latest release (1.4.5) with Windows Defender turned on. Windows Defender reported a virus in the zip.

### Expected Behavior
_Tell us what you expected to happen_
To download a clean executable.

### Steps to reproduce
_What are the steps we can take to reproduce this and verify it's fixed?_
Download the latest release for x64 or 32 bit. 

### Traceback
_Share any debug output that was given by the CLI_
![image](https://user-images.githubusercontent.com/1883296/87191515-dc2d8180-c2f4-11ea-8250-67de3ce0b25b.png)

### Environment
_Select one of: macOS, Linux, Windows, Other_
Windows 10

**Comment by ob-stripe** [comment]
Thanks for the report @withinboredom. We've submitted the latest version of the CLI to Microsoft for analysis. Hopefully the issue will be fixed in the next Defender signatures update.

**Comment by VladMstv** [comment]
Same here. After I've executed "scoop install stripe", windows defender says that it's detected Trojan:Win32/Occamy.C41

**Comment by skoggimord** [comment]
I'm getting the Trojan:Win32/Occamy.C41 report today.

**Comment by withinboredom** [comment]
Got the latest definitions and this appears to be fixed. Thank you for your awesome work!

**Comment by withinboredom** [comment]
And then I tried running it and it reports it in the executable. I didn't see @skoggimord's comment.

cc: @ob-stripe

**Comment by zsoldosp** [comment]
when downloading the [zip file](https://github.com/stripe/stripe-cli/releases/download/v1.4.5/stripe_1.4.5_windows_x86_64.zip) a few minutes ago, I still get the Trojan:Win32/Occamy.C41 warning

So I updated the windows defender database, and tried downloading again, and had the same result.

The latest / update to Windows Defender Security Intelligence version is 1.319.1637.0

**Comment by auchenberg-stripe** [comment]
Hi 👋 

Kenneth here from Stripe. 

We are in contact with Microsoft to get this issue resolved.

We'll provide updates as things progress.

/k

**Comment by skoggimord** [comment]
No worries, hope you get it cleared up soon.

**Comment by auchenberg** [comment]
Hi 👋 

We have been in contact with Microsoft, and it's our understanding that our Windows builds of the CLI have been removed from the warning list.

Please let us know if that's not true.

Thanks all for reporting this!

/k

**Comment by malmosands** [comment]
I switched from Mac to Windows today and Windows Defender says that it detected a Trojan. Anyone else?

**Comment by danielrjames** [comment]
> I switched from Mac to Windows today and Windows Defender says that it detected a Trojan. Anyone else?

I'm getting the same notice.

**Comment by danielrjames** [comment]
> I switched from Mac to Windows today and Windows Defender says that it detected a Trojan. Anyone else?

@malmosands I am getting the same notice.

@auchenberg is there any update to this? It's been over a month. At the very least, can you roll back to 1.5.0 so we can use the stripe cli on windows?

**Comment by Tmp2k** [comment]
I can confirm, as of today, it's still being listed as a Trojan.

**Comment by auchenberg-stripe** [comment]
We are in dialog with the Defender team at Microsoft. Stay tuned and sorry about the trouble.

**Comment by auchenberg-stripe** [comment]
Microsoft have informed us that the Incorrect detection of the 64bit builds of the Stripe CLI have been removed. 

Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
