### ISSUE TITLE
"the program contains a trojan"

### ISSUE THREAD

**Issue by Joe8000** [stripe/stripe-cli#482]
possible false positive but windows defender picked up Trojan:Win32/Occamy.C41 in the stripe.exe

**Comment by spelunka** [comment]
I'm seeing the same result on my windows machine too
![cli](https://user-images.githubusercontent.com/64932209/87255698-ee690600-c441-11ea-9566-c7d03327b505.png)

**Comment by auchenberg-stripe** [comment]
This is duplicate of https://github.com/stripe/stripe-cli/issues/481. We've submitted the latest version of the CLI to Microsoft for analysis.
