### ISSUE TITLE
Unknown flag: --object for `stripe cards list --object=card`

### ISSUE THREAD

**Issue by arnisjuraga** [stripe/stripe-cli#490]
Stripe CLI example at https://stripe.com/docs/api/cards/list?lang=cli#list_cards gives an example:

```bash
stripe cards list cus_HStymdD \
  --object=card \
  --limit=3
```

Stripe CLI releases 1.4.5 and 1.4.6 give an error:

```
unknown flag: --object
```

And Postman POST test gives:
URL: https://api.stripe.com/v1/customers/cus_HStymdD/sources?limit=3&object=card 

```
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameters: limit, object",
    "param": "limit",
    "type": "invalid_request_error"
  }
}
```

Is this correct behavior? Then error messages could be more explaining, if there is no such customer, source, obejct?

**Comment by tomer-stripe** [comment]
Could you try `stripe payment_methods list --type=cards`? This might be a problem with the documentation.

**Comment by arnisjuraga** [comment]
Same result.

```bash
$ stripe cards list cus_Hh6xtkLtwtn1ic --type=cards
unknown flag: --type

$ stripe cards
Usage:
  stripe cards <operation> [parameters...]

Available Operations:
  delete
  update
[..]

```

Curl method works "better", but result object data is "empty", although customer has valid test card attached.

```bash
$ curl https://api.stripe.com/v1/customers/cus_Hh6xtkLtwtn1ic/sources   -u sk_test_XX_KEY_XX:   -d object=card   -d limit=3   -G

{
  "object": "list",
  "data": [

  ],
  "has_more": false,
  "url": "/v1/customers/cus_Hh6xtkLtwtn1ic/sources"
}

```

**Comment by tomer-stripe** [comment]
Yea, that's a bug in the documentation, will file a ticket to get it fixed!

I don't entirely know what the difference between the request to customers is and payment methods though so not sure why that behavior is different.

**Comment by ctrudeau-stripe** [comment]
Hello @arnisjuraga, thank you for reporting. The docs are now updated on https://stripe.com/docs/api/cards/list. The empty data result from the curl command is because the card is added as a payment method from the [PaymentMethods API](https://stripe.com/docs/api/payment_methods). This curl below is for sources for the [Sources API](https://stripe.com/docs/api/sources)

`$ curl https://api.stripe.com/v1/customers/cus_Hh6xtkLtwtn1ic/sources   -u sk_test_XX_KEY_XX:   -d object=card   -d limit=3   -G`

**Comment by rickbanville** [comment]
It appears there maybe a second instance of this particular docs bug in an alternative location.

The `stripe-cli` command for listing all of a customer's payment methods results in an error.

The command-line example listed at https://stripe.com/docs/api/payment_methods/customer_list
indicates usage of 
```
stripe payment_methods list cus_KOIaWCTPFnwIqz \
  --type=card
```

Which results in
```
`stripe payment_methods list` requires exactly 0 positional arguments.
```

After reading this issue, I found the command to work if I add the `--customer` option prefix.
IE: 
```
stripe payment_methods list --customer=cus_KOIaWCTPFnwIqz \
  --type=card
```
