### ISSUE TITLE
Install Error macOS 11.0.0 Beta 4

### ISSUE THREAD

**Issue by Burnsy** [stripe/stripe-cli#495]
### Issue
When going to install the CLI tool through homebrew it crashes

### Expected Behavior
installs stripe-cli through homebrew

### Steps to reproduce
`brew install stripe`

### Traceback
```
==> Installing stripe from stripe/stripe-cli
==> Downloading https://github.com/stripe/stripe-cli/releases/download/v1.5.1/stripe_1.5.1_mac-os_x86_64.ta
Already downloaded: /Users/christopherburns/Library/Caches/Homebrew/downloads/3c6c34413a708c96847ae7d9d060c01637fb581691c139d1c7d570d86e1f3c11--stripe_1.5.1_mac-os_x86_64.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

### Environment
macOS 11.0.0 Beta 4

**Comment by tomer-stripe** [comment]
Hey @Burnsy, do you know if this is a homebrew error for Big Sur? The CLI itself installs as a binary and that error looks like a Ruby failure. Our homebrew recipe doesn't call `path` anywhere either: https://github.com/stripe/homebrew-stripe-cli/blob/master/stripe.rb

I'm going to try to get a laptop with Big Sur installed to see if I can repro but that might take a little bit (we can't install the betas on our devices yet).

**Comment by Burnsy** [comment]
thank you for getting back to me @tomer-stripe 

It looks like it was a problem with big sir/homebrew and the problem with the homebrew link.
Issue explaining how it can be fixed!
https://github.com/Homebrew/brew/issues/7803#issuecomment-648601678

Install the Command_Line_Tools_for_Xcode_12 will fix it :)
