### ISSUE TITLE
Login fails if xdg-open is installed but fails to open a web browser

### ISSUE THREAD

**Issue by nialldalton** [stripe/stripe-cli#499]
### Issue

When running the stripe cli in an environment such as a Github or Visual Studio Codespace, the following can happen to cause the tool to fail to start a web browser but also not print the URL for manual access:

- although remote, it is not an ssh session; SSH_TTY etc are not set, so the client attempts to open a web browser by choosing the `else` path: https://github.com/stripe/stripe-cli/blob/master/pkg/login/client_login.go#L58
- open.Browser uses Start() to spawn xdg-open: https://github.com/stripe/stripe-cli/blob/master/pkg/open/open.go#L17 and notably Start does not wait for it to complete (vs. Run, or doing a subsequent Wait)
- since the user had installed a package which caused xdg-utils to be installed in the codespace, xdg-open was found so Start did not return an error immediately
- xdg-open fails to start a web browser
- stripe client assumes it was successful, as xdg-open started, and polls for the completion of the remote work

### Expected Behavior

Note that xdg-open failed to start a web-browser and print the URL.

### Steps to reproduce

Install xdg-open but no web browsers and run `stripe login`. 

Alternatively based on https://linux.die.net/man/1/xdg-open we might fake out `xdg-open` returning 3 to indicate no browser was found and test it like this, where the URL should be printed but isn't.

```bash
$ cat ./xdg-open
#!/bin/bash
exit 3 

$ chmod +x ./xdg-open
$ PATH=. ./stripe login
Your pairing code is: scenic-poised-gains-swift
This pairing code verifies your authentication with Stripe.
Press Enter to open the browser (^C to quit)
⣟ Waiting for confirmation... 
⣷ Waiting for confirmation... 
⣻ Waiting for confirmation... 
```

### Environment

Linux (Ubuntu 20.04 LTS), stripe version 1.5.1

**Comment by tomer-stripe** [comment]
Thanks for the report! For Github or VS Codespace, would logging in with the `--interactive` flag help here? (https://stripe.com/docs/cli/login#login-interactive). That would let you provide the information manually.

**Comment by nialldalton** [comment]
Yes, that can be used to login in those environments. The user that reported the problem assumed that the normal flow would work. I didn't think to use that command when recreating this, and just convinced the normal login flow to work by setting a fake SSH_TTY variable for the invocation.

**Comment by richardm-stripe** [comment]
Could we print out the URL for manual access *in addition* to running xdg-open? I think that would probably solve this from a user perspective.
