### ISSUE TITLE
Events that should be triggered when using my site in local development do not reach the webhook.

### ISSUE THREAD

**Issue by asecondwill** [stripe/stripe-cli#504]
### Issue
I'm completing purchases on my site in local development, eg on localhost:3000 (rails app) . My webhook listens for payment_intent.succeeded.  

The webhook works in production.  Seems intermittent on localhost.

i have run 
 stripe listen --forward-to lvh.me:3000/webhook
 stripe logs tail 

### Expected Behavior
A call should be made to my webhook

### Steps to reproduce
 make a rails app, run the cli, complete a stripe elements purchase on localhost

### Traceback
none, nothing happens at all.

### Environment
macOS

**Comment by tomer-stripe** [comment]
@asecondwill can you run `stripe listen` with `--logs-level debug`? Also do you have specific times you were running the CLI? I want to reference our graphs and see if anything looks out of the ordinary.

**Comment by asecondwill** [comment]
I was having trouble with this last week, and a few days later support mentioned webhooks were down earlier that week, possibly coinciding. Then webhooks worked for a day.  It happened again yesterday around 10am BST

**Comment by tomer-stripe** [comment]
Looking at our graphs I think that might've been correlated to an upstream webhook delivery delay for testmode events. Sorry you keep hitting issues with that :(.

**Comment by tomer-stripe** [comment]
Didn't mean to close -- let me know if you hit issues again in the future and I'll check things again. I'll close this in a few days if things stay quiet.

**Comment by asecondwill** [comment]
this has happened again this week.  New project. 

as far as I know, there is very little for me to be getting wrong here? I just run 

stripe listen --forward-to localhost:3000/pay/webhooks/stripe      

and wait.  

Checking my "rails s" server output.  Nothing arriving.  

It has become quite a big issue.  90% of time working on anything stripe is spent investigating CLI issues.

**Comment by asecondwill** [comment]
ok, found what was happeneing this time whilst perusing the docs looking for log flags I noticed "login". Login.  Oh yes.  My CLI is  logged in as home Stripe account, not work account.   Logging in as the Stripe user with access to this project's Stripe account resolved the issue. 

Sorry to bother you.  Leaving this note for anybody else or future me to find.

W

**Comment by asecondwill** [comment]
Brian at stripe and I got this working again by running

stripe listen
stripe trigger payment_intent.created  

then stopping stripe listen and running
stripe listen --forward-to localhost:3000/pay/webhooks/stripe

## Checklist for future 
Make sure cli is logged in to correct account
Full path to webhook of course (but if it isnt there will be errors in stripe & rails console)
using correct signing secrect.

**Comment by nathanjo** [comment]
I just did experienced this today. For some reason it works for few triggers and then stops working. I need to restart the `stripe listen` and the triggers works again. But after few triggers I don't receive any response afterwards.
