### ISSUE TITLE
Unable to login - Confirmation token could not be loaded

### ISSUE THREAD

**Issue by patmisch** [stripe/stripe-cli#508]
### Issue
This just started today, although I have not tried to login in a while. After the browser window opens I am redirected to the following url: `https://dashboard.stripe.com/auth_stripecli`

![image](https://user-images.githubusercontent.com/722715/94305505-48f10900-ff3f-11ea-8007-5b7480cb2cdc.png)

I've tried logging out (in browser and in CLI), different browsers, clearing browser data, restarting terminal, etc but no luck.

### Environment
macOS

**Comment by richardm-stripe** [comment]
Hello @patmisch thank you for flagging. We've been able to reproduce this and are investigating this internally. In the meantime, you may be able to unblock yourself by using `stripe login --interactive`

**Comment by richardm-stripe** [comment]
@patmisch the issue should be resolved now. Please let us know if you experience any further issues.

**Comment by eyoeldefare** [comment]
I am seeing this issue in windows version `stripe_1.18.0_windows_x86_64`
