### ISSUE TITLE
A method to return the webhook signing secret

### ISSUE THREAD

**Issue by ianjamieson** [stripe/stripe-cli#520]
### Problem
As part of our CI workflow, we run Stripe CLI to listen for and trigger webhook requests, using:

`stripe listen --api-key KEY --load-from-webhooks-api --forward-to localhost`

And I get the output as:

```
Ready! Your webhook signing secret is whsec_1234 (^C to quit)
```

Our CI relies on knowing the value `whsec_1234` as we set this as an environment variable when running e2e tests.

I am having to now poll the docker logs to wait until I match a regex value of `whsec_[A-Za-z0-9]*`

### Feature
It would be nice to have something like:

```
stripe get-signing-key
```

So then I can 

```
stripe get-signing-key >> .env
```

And write the output to `.env` file

**Comment by ianjamieson** [comment]
I have created a workaround [here](https://stackoverflow.com/questions/64380586/listen-for-bash-command-output-and-when-matching-a-string-save-to-file-and-exit/64467044#64467044)

You will need to loop over the output of the `listen` command and then use `grep` to write the key to a file.

For example:

```
  echo -n 'STRIPE_WEBHOOK_SHARED_SECRET=' >> .env
  docker run --name="stripe-cli" --network="host" --rm -it stripe/stripe-cli listen --api-key YOUR_API_KEY --load-from-webhooks-api --forward-to localhost:1337 | while read -r line
  do
    if [[ $line =~ whsec_ ]]; then
      docker stop stripe-cli
      echo $line | grep -o 'whsec_[A-Za-z0-9]*' >> .env
    fi
  done
```

**Comment by richardm-stripe** [comment]
Hi @ianjamieson, I think `stripe listen --print-secret` should fit the bill. I just noticed this is missing from https://stripe.com/docs/cli so maybe we can add it there and make it easier to find.

**Comment by ianjamieson** [comment]
Exactly what I am looking for
