### ISSUE TITLE
Creation of subscription error

### ISSUE THREAD

**Issue by CanadaViet** [stripe/stripe-cli#536]
I use that command in cli for windows 1.5.4:
stripe trigger subscription_schedule.created

here is the  result in my command window 
Setting up fixture for: customer
Setting up fixture for: plan
Setting up fixture for: subscription_schedule
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}

Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}

Log of stripe for the webhook
Request POST body
{
  "phases": {
    "0": {
      "iterations": "1",
      "plans": {
        "0": {
          "plan": "plan_IMehqtvInYB0JS",
          "quantity": "1"
        }
      }
    },
    "1": {
      "iterations": "1",
      "plans": {
        "0": {
          "plan": "plan_IMehqtvInYB0JS",
          "quantity": "2"
        }
      }
    }
  },
  "customer": "cus_IMehEPUDqDB7Lf",
  "start_date": "now"
}
Response body
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: phases[0][plans]",
    "param": "phases[0][plans]",
    "type": "invalid_request_error"
  }
}

In my stripe, the client is created, the product. the price.. but of course no subscription

**Comment by pepin-stripe** [comment]
merging with #554
