### ISSUE TITLE
Trigger for connect account.updated event

### ISSUE THREAD

**Issue by khushwanth** [stripe/stripe-cli#546]
### Problem
Using stripe CLI to trigger account.updated. However, there is no such trigger supported for now.

### Feature
Adding Trigger account.updated for connected accounts when the users log in through Express Dashboard and update verification documents or other information that are updatable.

**Comment by JamesTPF** [comment]
Duplicate of https://github.com/stripe/stripe-cli/issues/345 with 29 up votes

**Comment by pepin-stripe** [comment]
closed since duplicate of #345
