### ISSUE TITLE
Your CLT does not support macOS 11.0

### ISSUE THREAD

**Issue by stronglee** [stripe/stripe-cli#548]
### Issue
Your CLT does not support macOS 11.0
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.

### Environment
 macOS 11.0

**Comment by tomer-stripe** [comment]
@stronglee what error are you seeing?

**Comment by shukla2009** [comment]
As suggested : 
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

Solved issue for me

**Comment by simonpoortman123** [comment]
API sleutel 
pk_test_5nDu72YGMKuHMqcsTJZE6il4008crKB0b1
Geheime sleutel 
est_NaiU8Au3u8K5ye7QVj0OxnHm00O50GJIqZ

**Comment by simonpoortman123** [comment]
> API sleutel
> pk_test_5nDu72YGMKuHMqcsTJZE6il4008crKB0b1
> Geheime sleutel
> est_NaiU8Au3u8K5ye7QVj0OxnHm00O50GJIqZ

**Comment by simonpoortman123** [comment]
> 
> 
> ### Issue
> 
> Your CLT does not support macOS 11.0
> 
> It is either outdated or was modified.
> 
> Please update your CLT or delete it if no updates are available.
> 
> 
> 
> ### Environment
> 
>  macOS 11.0
> 
>

**Comment by richardm-stripe** [comment]
Closing, as this seems to be an environmental issue.
