### ISSUE TITLE
Trigger account.application.deauthorized	

### ISSUE THREAD

**Issue by pauljcurtis** [stripe/stripe-cli#550]
### Problem
Using stripe CLI to trigger account.application.deauthorized. There is no such trigger supported.

### Feature
Adding Trigger account.application.deauthorized	for connected accounts for Stripe CLI

**Comment by pepin-stripe** [comment]
Hi @pauljcurtis, thanks for reporting. I've filed a task internally and will address this :)

**Comment by etsai-stripe** [comment]
addressed in https://github.com/stripe/stripe-cli/pull/967

**Comment by etsai-stripe** [comment]
released in v1.12.0!
