### ISSUE TITLE
Authenticating and then listening fails with 500

### ISSUE THREAD

**Issue by TianboZ** [stripe/stripe-cli#556]
Hi Stripe team, 

I am having a similar issue like this one [https://github.com/stripe/stripe-cli/issues/36](url) 
I've tried the methods mentioned in the above one but doesn't work

### Steps to reproduce

the difference is that I use localhost for testing, I followed Stripe CLI docs to 
1. log into Stripe `stripe login`
2. create a new customer `stripe customers create`

```
{
  "error": {
    "message": "An unknown error occurred",
    "type": "api_error"
  }
}
```

### Environment
macOS

**Comment by TianboZ** [comment]
Hmmm, seems like it gets fixed
PST 3:31 PM

**Comment by pepin-stripe** [comment]
Great thanks! Please feel free to reopen if you are facing this issue again.
