### ISSUE TITLE
identity.verification_intent.*

### ISSUE THREAD

**Issue by Sunhat** [stripe/stripe-cli#559]
### Problem
I'm trying to create a webhook for the identity.verification_intent.* events

They're listed in Stripe documentation as existing, but aren't supported in the Stripe Dashboard or Stripe CLI

### Feature
identity.verification_intent.* and identity.verification_report.* endpoints supported

**Comment by ctrudeau-stripe** [comment]
Hello @Sunhat, thank you for the issue. If you're part of the beta for identity you'll be able to see those in the dashboard now. The support for the CLI will come in the future when the product leaves invite only as we don't support beta events. If you have any questions about it you can reach out to the identity team at identity-beta@stripe.com. Closing for now as these will be supported in the CLI once the product comes out of beta.

**Comment by mishac** [comment]
Is there any timeline on this? the product is out of beta but CLI still isn't supporting it.

**Comment by Sunhat** [comment]
@ctrudeau-stripe Could you provide an update?
