### ISSUE TITLE
invoice update complains about rak_invoice_write permission

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-cli#570]
### Issue

Trying to use `stripe-cli` really for the first time, to update an existing invoice to add some custom fields (something that feels like it should be possible via the Dashboard, but isn't). When I try to issue `stripe invoice update ...` commands, I get this error:

```json
{
  "error": {
    "message": "The provided key 'rk_live_*********************************************************************************************xxxxxx' does not have the required permissions for this endpoint on account 'acct_yyyyyyyyyyyyyyy'. Having the 'rak_invoice_write' permission would allow this request to continue.",
    "type": "invalid_request_error"
  }
}
```

(The `xxxxxx` and `yyyyyyyyyyyyyyy` was the end of our actual identifiers, which I left off just to be safe.)

I've googled `rak_invoice_write`, but am not finding anything about this. The account I've used to authenticate stripe-cli is an admin of our account. It's definitely possible my command is wrong, but I've tried both updating the custom fields as well as just updating metadata, and both fail with the same error.

Examples:

```
stripe invoices update {my_invoice_number} --live -d "custom_fields"="[{name:\"P. O. Number\",value:\"12345\"}]"
```

```
stripe invoices update {my_invoice_number} --live -d "metadata[test]=foobar"
```

### Environment

macOS 11.1, stripe-cli 1.5.6

**Comment by ctrudeau-stripe** [comment]
Hello @winzig, when the Stripe CLI creates a session it creates a restricted key by default to interact with the API which prevents writing to live mode. If you open the dashboard to the [apikeys section](https://dashboard.stripe.com/apikeys) and scroll down you will see the key created by the CLI. There you can edit the permission and set Billing resources to write and the command above will work. 

<img width="1430" alt="Screen Shot 2021-03-02 at 3 04 21 PM" src="https://user-images.githubusercontent.com/49962232/109727186-bc3f1c80-7b68-11eb-8066-c98264585227.png">

**Comment by winzig** [comment]
Ahhh, thank you @ctrudeau-stripe. We've worked around this issue for now, but the next time I need to edit an invoice I'll try this out.
