### ISSUE TITLE
delete price returns invalid_request_error

### ISSUE THREAD

**Issue by lesterchoi-okta** [stripe/stripe-cli#571]
### Issue
Trying to delete price via CLI results in an "Unrecognized request URL" response. Other resources seem to work fine from CLI, e.g., products. Deleting price from dashboard seems to work as expected.

```sh
stripe delete price_somepriceid
```

### Expected Behavior
```json
{
  "id": "price_somepriceid",
  "object": "price",
  "deleted": true
}
```

### Traceback

Tried moving the `--log-level` flag to various places to see if it'd produce output, but no additional information was output.

```sh
stripe delete price_somepriceid --log-level debug 
```

```json
{
  "error": {
    "message": "Unrecognized request URL (DELETE: /v1/prices/price_somepriceid). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}
```

### Environment
macOS, stripe CLI installed via Homebrew
stripe version 1.5.6

**Comment by tomer-stripe** [comment]
Thanks for the heads up! You can't actually delete prices (https://stripe.com/docs/api/prices) so we need to add a mechanism to better handle the `delete` command on ids that don't support it.

**Comment by lesterchoi-okta** [comment]
@tomer-stripe Got it. Thanks!
