### ISSUE TITLE
Write permissions needed to use stripe logs tail

### ISSUE THREAD

**Issue by benwatsonnandos** [stripe/stripe-cli#572]
### Issue
1. I generate a restricted key that has read access to all data on my account.
1. I run `stripe login --interactive` to configure the Stripe CLI with this restricted key.
1. I run `stripe logs tail` but get the error:
     ```
     FATAL Error while authenticating with Stripe: Authorization failed, status=403, body={
       "error": {
         "message": "The provided key 'rk_live_***XXXXX' does not have the required permissions for this endpoint on account 'acct_XXXXXXX'.
                     Having the 'rak_stripecli_session_write' permission would allow this request to continue.",
         "type": "invalid_request_error"
       }
     }
     ```

### Expected Behavior
I should be able to run `stripe logs tail` without needing any write permissions.

### Environment
macOS

**Comment by tomer-stripe** [comment]
@benwatsonnandos what permissions did you select in the API key manage page? You need to enable `Stripe CLI Permissions` for `Debugging tools`. The write permission at the moment is needed to enable streaming to get forwarded to the CLI (we don't want to assume that reads for objects also means live streaming to the CLI).

**Comment by benwatsonnandos** [comment]
Thanks Tomer.
