### ISSUE TITLE
Upgrade/Install on linux is b0rken

### ISSUE THREAD

**Issue by dotnetCarpenter** [stripe/stripe-cli#573]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue

I can not upgrade or re-install stripe-cli.

### Expected Behavior
Normal upgrade...

### Steps to reproduce
1. `sudo apt install stripe`

### Traceback:
<details>
<summary>/var/lib/dpkg/info/stripe.postinst: 3: stripe: not found</summary>
<pre>
After this operation, 18.5 MB of additional disk space will be used.
Selecting previously unselected package stripe.
(Reading database ... 143233 files and directories currently installed.)
Preparing to unpack .../stripe_1.5.7_amd64.deb ...
Unpacking stripe (1.5.7) ...
Setting up stripe (1.5.7) ...
/var/lib/dpkg/info/stripe.postinst: 3: stripe: not found
dpkg: error processing package stripe (--configure):
 installed stripe package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 stripe
E: Sub-process /usr/bin/dpkg returned an error code (1)
</pre></details>

### Environment
Windows 10 WSL2
Distribution: Ubuntu 20.04.1 LTS (focal)
Kernel: 5.4.72-microsoft-standard-WSL2

**Comment by Honza-m** [comment]
I have the same issue, a fresh install on WSL2 fails with the same error message. The same error also appears for version 1.5.6, but I was able to successfully install and login on version 1.5.5

**Comment by cruzcraul** [comment]
I have the same issue: I can not install stripe-cli on linux

**Steps to reproduce**
sudo apt install stripe

**Traceback:**
/var/lib/dpkg/info/stripe.postinst: 3: stripe: not found

**Environment**
Distribution: Ubuntu 20.04.1 LTS (focal)
Linux version 5.8.0-38-generic (buildd@lgw01-amd64-060) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34)

**Comment by suz-stripe** [comment]
Hi there, thank you both for reporting this issue. We're releasing v1.5.8 shortly which should alleviate the installation problems. Thanks for your patience and let us know if there are any further problems you encounter!

**Comment by dotnetCarpenter** [comment]
no issue installing stripe version 1.5.8
