### ISSUE TITLE
`stripe listen` forwarding to wrong local URL

### ISSUE THREAD

**Issue by kylefox** [stripe/stripe-cli#584]
I run two instances of `stripe listen` because my application uses two different endpoints for Stripe and Stripe Connect events, and each endpoint accepts a different list of events:

1. `/webhooks/stripe` receives Stripe events for my account
2. `/webhooks/stripe/connect` receives Stripe events from connected accounts

I have noticed a sporadic issue where Stripe Connect events are sometimes delivered to my account endpoint URL (`/webhooks/stripe`) rather than my connect endpoint URL (`/webhooks/stripe/connect`).

I run the two `stripe listen` commands below in parallel with a `Profile` (using [Foreman](https://github.com/ddollar/foreman)):

### Stripe Events

```shell
stripe listen \
  --skip-verify \
  --forward-to https://api.lvh.me:5001/webhooks/stripe \
  --events \
customer.created,\
customer.deleted,\
customer.discount.created,\
customer.discount.deleted,\
customer.discount.updated,\
customer.source.created,\
customer.source.deleted,\
customer.source.expiring,\
customer.source.updated,\
customer.subscription.created,\
customer.subscription.deleted,\
customer.subscription.trial_will_end,\
customer.subscription.updated,\
customer.updated,\
invoice.payment_failed,\
plan.created,\
plan.deleted,\
plan.updated,\
product.created,\
product.deleted,\
product.updated
```

### Stripe Connect Events

```shell
stripe listen \
  --skip-verify \
  --forward-connect-to https://api.lvh.me:5001/webhooks/stripe/connect \
  --events \
account.application.deauthorized,\
charge.captured,\
charge.refunded,\
charge.succeeded,\
checkout.session.completed,\
coupon.deleted,\
coupon.updated,\
customer.created,\
customer.deleted,\
customer.subscription.created,\
customer.subscription.deleted,\
customer.subscription.updated,\
customer.updated
```

Is running two `stripe listen` commands in parallel like this unsupported?

I'm using `stripe version 1.5.8` on macOS 11.1.

Please let me know if there's any other debug/troubleshooting info I can provide. Thanks!

**Comment by ianjabour-stripe** [comment]
@kylefox thanks for reporting this, we're currently looking into the issue.

For the events that sporadically show up on your account endpoint URL (/webhooks/stripe) rather than your connect endpoint URL (/webhooks/stripe/connect) are they events that are listed in both commands (i.e `customer.updated`) or are they events that are unique to the Connect version of `stripe listen` (i.e `checkout.session.completed`)?

**Comment by ianjabour-stripe** [comment]
Following up here after looking into this.

When you run `stripe listen --forward-to` we automatically forward connect events to the URL provided if no `--forward-connect-to` flag is used.

This is specified in the [CLI Reference](https://stripe.com/docs/cli/listen#listen-forward-connect-to) docs and in the help text for `--forward-connect-to` when you run `stripe listen -h`, although the text is definitely unclear and will be updated.

In the case where you only use `--forward-connect-to` we do not have the same fallback behavior.

I believe this is why Stripe Connect events are sometimes delivered to your account endpoint URL but not the other way around.

**Comment by kylefox** [comment]
Thanks @ianjabour-stripe — that makes sense and I think explains the behavior I've seen.

>  are they events that are listed in both commands (i.e customer.updated) 

Now that you mention it, yes — the ones that were constantly giving me issues are `customer.created` and `customer.updated`.

> When you run stripe listen --forward-to we automatically forward connect events to the URL provided if no --forward-connect-to flag is used.

Is there an alternative/recommended approach for forwarding account and Connect events to different URLs _and_ specify different sets of events to listen for?

If not, I'll likely just run a single `listen` command with a combined list of events, i.e. something like:

```shell
stripe listen \
  --skip-verify \
  --forward-to https://api.lvh.me:5001/webhooks/stripe \
  --forward-connect-to https://api.lvh.me:5001/webhooks/stripe/connect \
  --events \
account.application.deauthorized,\
charge.captured,\
charge.refunded,\
charge.succeeded,\
checkout.session.completed,\
coupon.deleted,\
coupon.updated,\
customer.created,\
customer.deleted,\
customer.discount.created,\
customer.discount.deleted,\
customer.discount.updated,\
customer.source.created,\
customer.source.deleted,\
customer.source.expiring,\
customer.source.updated,\
customer.subscription.created,\
customer.subscription.deleted,\
customer.subscription.trial_will_end,\
customer.subscription.updated,\
customer.updated,\
invoice.payment_failed,\
plan.created,\
plan.deleted,\
plan.updated,\
product.created,\
product.deleted,\
product.updated
```

**Comment by ianjabour-stripe** [comment]
@kylefox unfortunately right now we do not support disabling this default behavior. For now we'd recommend just using a single command like the one you posted.

This is a very interesting use case however, and I'll bring it up with the team to see if there's something we can do to support this workflow.

**Comment by kylefox** [comment]
Cool, thanks @ianjabour-stripe !
