### ISSUE TITLE
"stripe fixtures" command raises "Invalid integer" when checkout amout exceeds 10K 

### ISSUE THREAD

**Issue by NathanRichard** [stripe/stripe-cli#585]
### Issue
I use stripe checkout in my application. I set up the following test for my backend :
- I generate a checkout session in my backend,
- I validate it using stripe fixture.
- I wait for the checkout completed event in my BE.

As long as the total order amount is below 10K, everything works fine.
If my the amount exceed 10K, stripe fixtures raise an error such as:
```
Request failed, status=400, body={
  "error": {
    "code": "parameter_invalid_integer",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-integer",
    "message": "Invalid integer: 1.0038e+06",
    "param": "expected_amount",
    "type": "invalid_request_error"
  }
}
```
Looks like to me that there is some string to float to int conversion going on that goes wrong with long integers (when the e+N format starts being used).

### Expected Behavior
The stripe docs says that amounts up to height digits including cents, I expect the "stripe fixture" command to do the same.

### Steps to reproduce
Not a full reproduction, but I set up [a gist with a fixture file that triggers the issue](https://gist.github.com/NathanRichard/de10f99cb334fb51d57e82f05dc5c7e8) and [another that is ok.](https://gist.github.com/NathanRichard/abc3e5e1801e9d43ed7799eb01d96b5e)

### Environment
Ubuntu 20.04
stripe version 1.5.8

**Comment by ianjabour-stripe** [comment]
@NathanRichard thank you for pointing this out. Like you mentioned it looks like it has to do with the float / int conversion logic we're using.

We should have a fix up for this real soon.

As a side note, I tested the failure case you linked but used a string instead (`"1003800"`) and that seemed to work.

**Comment by tomer-stripe** [comment]
Closing this since it should be resolved now!
