### ISSUE TITLE
Fire test events that have data on localhost

### ISSUE THREAD

**Issue by arepp23** [stripe/stripe-cli#591]
### Problem
Would like to be able to fire a test event from the CLI on localhost that includes data.

### Feature
Triggering events via the CLI with included data fields

### Examples
Firing an invoice.paid event with a customer id so I can test how my backend is going to provision services for that payment.

**Comment by tomer-stripe** [comment]
Hey @arepp23! I'm going to close this since I think it's the same as #295 (and #589 which I've slowly started to work on). If you have feedback on either please let me know! It sounds like the PR I've started should cover what you need.
