### ISSUE TITLE
stripe_1.5.12_windows_x86_64.zip .exe file triggers Windows Defender AV

### ISSUE THREAD

**Issue by ChrisCrossCrash** [stripe/stripe-cli#619]
### Issue
After downloading stripe_1.5.12_windows_x86_64.zip from this Github repo, I decompressed the executable file. It immediately triggered a warning from Windows Defender.

Here is the VirusTotal score for the .zip file:
![image](https://user-images.githubusercontent.com/40023417/113354098-4ab0e480-9347-11eb-860b-4d462900d6fe.png)

### Expected Behavior
It shouldn't trigger a warning from Windows Defender

### Steps to reproduce
1. On a Windows 10 PC with Windows Defender antivirus running, download stripe_1.5.12_windows_x86_64.zip from https://github.com/stripe/stripe-cli/releases/tag/v1.5.12
2. Drag the file out of the .zip folder into another folder. This should trigger a Windows Defender warning.

### Environment
Windows 10

**Comment by mhourig** [comment]
Same

**Comment by tomer-stripe** [comment]
Thanks for the report! We'll look into it.

**Comment by tomer-stripe** [comment]
Could you both try again and see if it's still happening? We just ran through and looks like it's not flagged anymore: https://www.virustotal.com/gui/file/7583ad0fdcdc8e56b7ed3957c384705c36e8dc5c3aa22f3d966772397289e87d/detection

**Comment by mhourig** [comment]
@tomer-stripe all good! Thank you.

**Comment by ChrisCrossCrash** [comment]
@tomer-stripe Works for me too. Thanks for fixing it!
