### ISSUE TITLE
Can't associate account ID with account.updated

### ISSUE THREAD

**Issue by rursteve2** [stripe/stripe-cli#620]
Triggering account.updated with a stripe account gives me this error 

> Setting up fixture for: account
Trigger failed: Request failed, status=403, body={
  "error": {
    "message": "Connect platforms cannot create new accounts on behalf of their connected accounts.",
    "type": "invalid_request_error"
  }
}

> Request failed, status=403, body={
  "error": {
    "message": "Connect platforms cannot create new accounts on behalf of their connected accounts.",
    "type": "invalid_request_error"
  }
}

I'm trying to trigger account.updated with an account ID I have in my database by doing `stripe trigger account.updated --stripe-account <account ID>` but it throws the error above. If I trigger it without a stripe account it auto generates a new customer ID. Am I approaching it wrong or is this a bug?

**Comment by vcheung-stripe** [comment]
Hello @rursteve2, I believe `stripe accounts update --stripe-account <account ID>` should work.

The `stripe trigger account.updated` command doesn't support the `--stripe-account` flag. It's intended to generate a new account ID. It uses [fixtures](https://stripe.com/docs/cli/fixtures) under the hood; see its [fixtures file](https://github.com/stripe/stripe-cli/blob/master/pkg/fixtures/triggers/account.updated.json) for what API calls it makes.

Please let us know if this helps!

**Comment by rursteve2** [comment]
Thank you! This is exactly what I was looking for!
