### ISSUE TITLE
unable to trigger requires_action event

### ISSUE THREAD

**Issue by lalit97** [stripe/stripe-cli#624]
### Problem

I wrote a view to handle stripe webhook events and I was testing it. 

So I have check for `event.type == "invoice.payment_failed"` and under that there are 2 cases possible which are either payment_intent’s status can be `requires_payment_method` or `requires_action`

I was triggering the event by command `stripe trigger invoice.payment_failed` but it is always generating the payment_intent's status as `requires_payment_method` but I want to test the event  where payment_intent's status is `requires_action` such as when the user needs to complete 3D authentication to complete the payment.

### Feature
This is one of the main events listed at subscription webhooks page (https://stripe.com/docs/billing/subscriptions/webhooks#action-required) so it will be really helpful if we can test this event with stripe cli. 

It will be cool if we can pass different cards while triggering webhook events from stripe cli from this list https://stripe.com/docs/billing/subscriptions/fixed-price#test or payment-method with cli command  

### Examples
`stripe trigger invoice.payment_failed --card 4000002500003155`
`stripe trigger invoice.payment_failed --pm pm_1IdsbnAmcRFdhqElnXTUHAzm`

**Comment by tomer-stripe** [comment]
Hey! I'm asking the product team that owns this if it's possible for us to do.

**Comment by lalit97** [comment]
cool! thanks
