### ISSUE TITLE
Stripe CLI appears to not receive all events

### ISSUE THREAD

**Issue by marnixhoh** [stripe/stripe-cli#631]
### Issue
Some events are received by the Stripe CLI and some of them are not. Which events are and are not received by the CLI appears to be pretty random. I did note though, that whenever I restart the Stripe CLI `listen` command, the first events appear to go through just fine. It is after some period of time, that events start to never reach the CLI.

Some other users appear to be having the same problem. See the latest comments on #487.

### Expected Behavior
I expected that all events would be received by the CLI as long as the `listen` command is running.

### Steps to reproduce
I wish I could give clear reproducible steps, but as I said above, which events do and don't make it to the CLI appears to be pretty random. But I'll give an outline of what I am doing:

1. run the stripe listen command, which looks as follows (created by the Stripe plugin for VSCode):
`/usr/local/bin/stripe listen --forward-to http://localhost:3000/api/endpoint --forward-connect-to http://localhost:3000/api/endpoint`
2. There are no specific events that do or do not work. But to give an example of an event that my endpoint is listening for, which is not always received: `checkout.session.completed`. I trigger this event, by completing a `Checkout Session` manually, while running my application locally - i.e. I don't trigger it using the Stripe CLI.

Note that for the events that are not received by the CLI, the Stripe Dashboard also says `No recent CLI responses` for that particular event on https://dashboard.stripe.com/test/events/{{evt_SOME_EVENT_ID}}. Whereas, it does list the response for events that are indeed reached.

### Environment
- macOS
- running locally (development)
- using test keys

**Comment by marnixhoh** [comment]
We just pushed an update to our staging environment and it is happening there too... So it appears like it has nothing to do with with running on localhost.

Note our staging environment also uses the same `test API key`

**Comment by pepin-stripe** [comment]
Thanks for reporting @marnixhoh. I'll merge with #600. 

We're currently investigating some possible leads on our side and think this might have to do with the reconnection logic we've got on the client and server. We're trying to confirm this as the problem and work on ways to improve it.
