### ISSUE TITLE
unexpected http status code: 500 when trying to Authorize with Stripe CLI

### ISSUE THREAD

**Issue by KramskoiSergei** [stripe/stripe-cli#633]
I try to authorize my stripe account in CLI and get 500 error.

### Steps to reproduce
1. Install stripe CLI using homebrew
2. Run "stripe login"
3. CLI will open browser
4. Insert correct credentials and login
5. Allow access for generated api-key by clicking "allow access"
6. Browser show "Done! You may now close this window and return to the CLI"

### Expected result:
CLI will authorize me and I can use it

### Actual result:
I see an error in CLI 
Waiting for confirmation... unexpected http status code: 500 <!DOCTYPE HTML>
with some HTML content:

### Traceback
`<html>
  <head>
    <meta charset="utf-8">
    <title>Stripe: Internal error</title>
    <meta name="robots" content="noindex, nofollow">
    <meta name="googlebot" content="noindex, nofollow, noarchive">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <style>
      body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Ubuntu', sans-serif;
      }

      a,
      a:hover,
      a:active,
      a:focus {
        color: inherit;
        outline: 0;
        text-decoration: none;
      }

      /** @define Flex */

      .Flex-flex {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
      }

      .Flex-inlineFlex {
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
      }

      .Flex-alignItems--center {
        -webkit-box-align: center;
            -ms-flex-align: center;
                align-items: center;
      }

      .Flex-direction--row {
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
            -ms-flex-direction: row;
                flex-direction: row;
      }

      .Flex-direction--column {
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
            -ms-flex-direction: column;
                flex-direction: column;
      }

      .Flex-justifyContent--center {
        -webkit-box-pack: center;
            -ms-flex-pack: center;
                justify-content: center;
      }

      /** @define Margin */

      .Margin-top--8 {
        margin-top: 8px;
      }

      .Margin-right--4 {
        margin-right: 4px;
      }

      .Margin-bottom--20 {
        margin-bottom: 20px;
      }

      /** @define Box **/

      .Box-background--surface {
        background-color: #e6ebf1;
      }

      /** @define Text */

      .Text-color--secondary {
        color: #6b7c93;
      }

      .Text-color--cyan {
        color: #3297d3;
      }

      .Text-display--inline {
        display: inline;
      }

      .Text-fontSize--14 {
        font-size: 14px;
      }

      .Text-fontSize--20 {
        font-size: 20px;
      }

      .Text-fontWeight--regular {
        font-weight: 400;
      }

      .Text-fontWeight--medium {
        font-weight: 500;
      }

      .Text-lineHeight--20 {
        line-height: 20px;
      }

      .Text-lineHeight--28 {
        line-height: 28px;
      }

      .Text-wrap--wrap {
        white-space: normal;
      }

      .Text-wrap--noWrap {
        white-space: nowrap;
      }

      /** @define ButtonLink **/

      .ButtonLink {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;

        background: transparent;
        border: 0;
        cursor: pointer;
        outline: none;
      }

      .ButtonLink:active .ButtonLink-label,.ButtonLink:focus .ButtonLink-label,.ButtonLink:hover .ButtonLink-label {
        color: #32325d;
      }

      .ButtonLink:active .ActionIcon svg,.ButtonLink:focus .ActionIcon svg,.ButtonLink:hover .ActionIcon svg {
        fill: #32325d;
      }

      /** @define ActionIcon **/

      .ActionIcon svg {
        fill: currentColor;
      }

      .ActionIcon--color--cyan {
        color: #3297d3;
      }

      /** @define Icon **/

      .Icon {
        background-repeat: no-repeat;
      }

      .Icon--size--64 {
        width: 64px;
        height: 64px;

        background-size: 64px 64px;
      }

      .Icon--warning {
        background-image: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHZpZXdCb3g9IjAgMCAyMCAyMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+ZGVmYXVsdDwvdGl0bGU+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBkPSJNMTkuNjA0IDE1LjMyTDExLjg2NCAxLjg1Yy0uODYtMS41NzYtMi44NjctMS41NzYtMy43MjcgMEwuMzk3IDE1LjMyMWMtMS4wMDQgMS43MiAwIDQuMDEyIDEuODYzIDQuMDEyaDE1LjQ4YzEuODY0IDAgMi44NjctMi4yOTMgMS44NjQtNC4wMTJ6IiBmaWxsLW9wYWNpdHk9Ii4yIiBmaWxsPSIjNDI0NzcwIi8+PHBhdGggZD0iTTkgOC40NjFDOSA3LjU4NCA5LjQgNyAxMCA3czEgLjU4NCAxIDEuNDYxdjMuNTA3YzAgLjg3Ni0uNCAxLjQ2LTEgMS40NnMtMS0uNTg0LTEtMS40NlY4LjQ2ek0xMCAxNmMtLjU4MyAwLTEtLjQwMi0xLS45NjQgMC0uNTYzLjQxNy0uOTY1IDEtLjk2NXMxIC40MDIgMSAuOTY1YzAgLjU2Mi0uNDE3Ljk2NC0xIC45NjR6IiBmaWxsPSIjNTI1RjdGIi8+PC9nPjwvc3ZnPg==');
      }

    </style>
  </head>
  <body>
    <div class="Box-root Box-background--surface Flex-flex Flex-alignItems--center Flex-direction--column Flex-justifyContent--center" style="height: 100vh; width: 100vw;">
      <div class="Box-root Margin-bottom--20">
        <div class="Icon Icon--warning Icon--size--64 Box-root Flex-flex"></div>
      </div>
      <span class="Text-color--secondary Text-display--inline Text-fontSize--20 Text-fontWeight--regular Text-lineHeight--28 Text-typeface--base Text-wrap--wrap">
        Sorry, but there was an internal error.
      </span>
      <div class="Box-root Margin-top--8">
        <a href="https://support.stripe.com" class="ButtonLink ActionIconParent Flex-justifyContent--center" type="button">
          <span class="ButtonLink-label Text-color--cyan Text-display--inline Text-fontSize--14 Text-fontWeight--medium Text-lineHeight--20 Text-typeface--base Text-wrap--noWrap">
            Contact support
          </span>
        </a>
        <a href="https://dashboard.stripe.com" class="ButtonLink ActionIconParent Margin-top--8" type="button">
          <div class="Box-root Flex-inlineFlex Flex-alignItems--center Flex-direction--row">
            <div class="SVGInline SVGInline--cleaned ActionIcon ActionIcon--color--cyan Box-root Flex-flex Margin-right--4">
              <svg class="SVGInline-svg SVGInline--cleaned-svg ActionIcon-svg ActionIcon--color--cyan-svg" style="width: 12px;height: 12px;" width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
                <g id="Icons" fill-rule="evenodd">
                  <g id="ActionIcon-previous">
                    <path d="M3.186 6.589L6.42 9.858a.675.675 0 0 1-.006.943.653.653 0 0 1-.933.006L1.189 6.47A.66.66 0 0 1 1 6a.66.66 0 0 1 .189-.469L5.48 1.193a.653.653 0 0 1 .933.006c.259.262.258.688.006.943L3.347 5.248h6.981a.67.67 0 0 1 .672.67c0 .37-.29.671-.672.671H3.186z" id="Arrow"></path>
                  </g>
                </g>
              </svg>
            </div>
            <span class="ButtonLink-label Text-color--cyan Text-display--inline Text-fontSize--14 Text-fontWeight--medium Text-lineHeight--20 Text-typeface--base Text-wrap--noWrap">
              Return to the Dashboard homepage
            </span>
          </div>
        </a>
      </div>
    </div>
  </body>
</html>
`

### Environment
macOS

**Comment by ianjabour-stripe** [comment]
Hello @KramskoiSergei , we apologize for that error. After looking into it and testing things on our end it seems to have been a a minor blip in authorization that we haven't seen since.

Please let us know if you continue to run into this issue.

**Comment by KramskoiSergei** [comment]
Unfortunately, I still have the same problem. I tried it on another Mac and also try to use throw docker - the same result. 
Could be a problem with my account?

**Comment by ianjabour-stripe** [comment]
@KramskoiSergei are you been able to manually log into the Stripe dashboard with this account?

**Comment by KramskoiSergei** [comment]
@ianjabour-stripe yes, of course
Do I understand right that u can't reproduce it on your side?

**Comment by ianjabour-stripe** [comment]
@KramskoiSergei correct, unfortunately we aren't able to reproduce this on our end. Being that it seems to be an issue with your account do you mind [contacting support](https://support.stripe.com/)?

That way we can get more information about your account and do a deeper investigation.

**Comment by AlexeyShalikWork** [comment]
I have the same problem!

**Comment by cacaodev** [comment]
Same here.
macOS 10.15.4, Chrome 91, stripecli installed via homebrew.
Stripe account with the Connect feature enabled.

**Comment by Cecilia-44** [comment]
Same here.
macOS 10.15.4, Chrome 91, stripecli installed via homebrew.
