### ISSUE TITLE
Problem starting the docker image

### ISSUE THREAD

**Issue by ukv001** [stripe/stripe-cli#634]
I have just downloaded the docker image for the cli, 
when I try to run it, it simply stops imidiately.
I have had no problems running the stripe mock.

I was expecting the image to be started, so I could attach a terminal and use the cli.
Similar to other cli's in a container.

ukv001$ docker run --rm -it stripe/stripe-cli:latest
The official command-line tool to interact with Stripe.

Before using the CLI, you'll need to login:

  $ stripe login

If you're working on multiple projects, you can run the login command with the
--project-name flag:

  $ stripe login --project-name rocket-rides

Usage:
  stripe [command]

Webhook commands:
  listen                        Listen for webhook events
  trigger                       Trigger test webhook events

Stripe commands:
  logs                          Interact with Stripe API request logs
  status                        Check the status of the Stripe API

Resource commands:
  get                           Quickly retrieve resources from Stripe
  charges                       Make requests (capture, create, list, etc) on charges
  customers                     Make requests (create, delete, list, etc) on customers
  payment_intents               Make requests (cancel, capture, confirm, etc) on payment intents
  ...                           To see more resource commands, run `stripe resources help`

Other commands:
  completion                    Generate bash and zsh completion scripts
  config                        Manually change the config values for the CLI
  feedback                      Provide us with feedback on the CLI
  fixtures                      Run fixtures to populate your account with data
  help                          Help about any command
  login                         Login to your Stripe account
  logout                        Logout of your Stripe account
  open                          Quickly open Stripe pages
  samples                       Sample integrations built by Stripe
  serve                         Serve static files locally
  version                       Get the version of the Stripe CLI

Flags:
      --api-key string        Your API key to use for the command
      --color string          turn on/off color output (on, off, auto)
      --config string         config file (default is $HOME/.config/stripe/config.toml)
      --device-name string    device name
  -h, --help                  help for stripe
      --log-level string      log level (debug, info, trace, warn, error) (default "info")
  -p, --project-name string   the project name to read from for config (default "default")
  -v, --version               Get the version of the Stripe CLI

Use "stripe [command] --help" for more information about a command.

### Environment
macOS

ukv001$ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS              PORTS             NAMES
50999ef8f358   stripemock/stripe-mock:latest   "/bin/stripe-mock -h…"   About a minute ago   Up About a minute   12111-12112/tcp   musing_franklin

**Comment by ianjabour-stripe** [comment]
Hello @ukv001 , when using the Stripe CLI via a Docker image you must append the commands and flags you wish to use on the end of `docker run --rm -it stripe/stripe-cli:latest`.

For example if you wanted to run `stripe customers list --limit=3` via Docker it would be: 

`docker run --rm -it stripe/stripe-cli:latest customers list --limit=3`

One thing to note is the `login` command cannot be used without defining a data volume for the container. A couple of alternatives to this would be:
* Add the [`--api-key`](https://stripe.com/docs/cli/flags#flags-api_key) flag to associate the account you wish to use
* Define the environment variable [`STRIPE_API_KEY`](https://stripe.com/docs/cli/api_keys)

You can find details on this in the [CLI reference docs](https://stripe.com/docs/cli/docker).

**Comment by ianjabour-stripe** [comment]
Closing this issue. If you continue to have issues with this please feel free to let us know and feel free to re-open.
