### ISSUE TITLE
stripe fixtures text.json --api-key xxxxx return some weird response

### ISSUE THREAD

**Issue by phani50** [stripe/stripe-cli#635]
Hi Team,

Till yesterday it was working fine. but all of sudden started returning below error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x40 pc=0x54d0fa]

Command  : stripe fixtures text.json --api-key xxxxx
response : 
Setting up fixture for: create_customer
Setting up fixture for: invoiceitem
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x40 pc=0x54d0fa]

goroutine 1 [running]:
github.com/thedevsaddam/gojsonq.(*JSONQ).reset(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/thedevsaddam/gojsonq@v2.3.0+incompatible/jsonq.go:550
github.com/thedevsaddam/gojsonq.(*JSONQ).Reset(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/thedevsaddam/gojsonq@v2.3.0+incompatible/jsonq.go:564
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).parseQuery(0xc00045d880, 0xc00017e390, 0xe, 0xc00017e390, 0xe)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:343 +0x17a
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).parseMap(0xc00045d880, 0xc0002ef200, 0x0, 0x0, 0xffffffffffffffff, 0xe3fde0, 0x0, 0x267bc23adb8)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:236 +0xacc
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).parseInterface(0xc00045d880, 0x7affe0, 0xc0002ef200, 0x0, 0x0, 0xc000089840)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:200 +0x3b8
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).createParams(0xc00045d880, 0x7affe0, 0xc0002ef200, 0x0)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:185 +0x6a
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).makeRequest(0xc00045d880, 0xc00017e340, 0xb, 0x0, 0x0, 0xc00017e350, 0x10, 0xc00017e34c, 0x4, 0x7affe0, ...)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:156 +0x1be
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).Execute(0xc00045d880, 0xe40108, 0xc0000e4000)
        D:/a/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:110 +0x179
github.com/stripe/stripe-cli/pkg/cmd.(*FixturesCmd).runFixturesCmd(0xc0000a7a20, 0xc000198f00, 0xc0005089c0, 0x1, 0x3, 0x0, 0x0)
        D:/a/stripe-cli/stripe-cli/pkg/cmd/fixtures.go:64 +0x105
github.com/spf13/cobra.(*Command).execute(0xc000198f00, 0xc000508990, 0x3, 0x3, 0xc000198f00, 0xc000508990)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xdf0540, 0x70d, 0x60, 0x1)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/stripe/stripe-cli/pkg/cmd.Execute()
        D:/a/stripe-cli/stripe-cli/pkg/cmd/root.go:64 +0xb1
main.main()
        D:/a/stripe-cli/stripe-cli/cmd/stripe/main.go:6 +0x27

Note : i have updated new release as well v1.5.14

Json file : 
-------
PFA
![test_json](https://user-images.githubusercontent.com/1286048/115451148-76cecf80-a23a-11eb-92a2-f44ddf08ddb9.PNG)

**Comment by ianjabour-stripe** [comment]
Hello @phani50 , I'm currently looking into why this error came up. I'll be sure to keep you updated here once I have a better idea of the failure.

Thank you for bringing this to our attention.

**Comment by ianjabour-stripe** [comment]
@phani50 we found that that issue is the fixture file is slightly misconfigured. The first fixture that creates the customer is named `create_customer` but later referenced as `customer`.

Here is an updated version of the fixture file that should work for you:

```json
{
  "_meta": {
    "template_version": 0
  },
  "fixtures": [
    {
      "name": "customer",
      "path": "/v1/customers",
      "method": "post",
      "params": {
        "name": "stripe test customer",
        "email": "stripe_test@gmail.com",
        "description": "(created by Stripe CLI)",
        "source": "tok_visa",
        "address": {
          "line1": "1 Planet Express St",
          "city": "New New York"
        }
      }
    },
    {
      "name": "invoiceitem",
      "path": "/v1/invoiceitems",
      "method": "post",
      "params": {
        "amount": 2000,
        "currency": "usd",
        "customer": "${customer:id}",
        "description": "(created by Stripe CLI)"
      }
    },
    {
      "name": "invoice",
      "path": "/v1/invoices",
      "method": "post",
      "params": {
        "customer": "${customer:id}",
        "description": "(created by Stripe CLI)"
      }
    },
    {
      "name": "invoice_pay",
      "path": "/v1/invoices/${invoice:id}/pay",
      "method": "post"
    },
    {
      "name": "delete_customer",
      "path": "/v1/customers/${customer:id}",
      "method": "delete"
    }
  ]
}
```

This brings up a great point though in that our validation should be better and clearer when references do not exist. We'll be sure to work on that.

If you have any other issues around this please let us know, thank you!

**Comment by phani50** [comment]
Ohh my bad, i have changed the name and forgot to change in other places. Thanks for the help.
Yes may be error message could have cleaner to understand easily.
