### ISSUE TITLE
Cannot Type Anything into cmd.exe After Stripe Listen Forward...

### ISSUE THREAD

**Issue by PostAlmostAnything** [stripe/stripe-cli#639]
After typing this:

stripe listen --forward-to 127.0.0.1:81/wordpress/wp-content/plugins/pluginname/webhook.php

into cmd.exe I receive the following feedback:
> Ready! Your webhook signing secret is whsec_<mysecret> (^C to quit)
_

After that I cannot type anything else into the cmd.exe window. I can't even quit by typing shift+6+C which is what you must type to convert the 6 key to the ^ character. Nothing goes in, so I cannot follow instructions to use things like curl to test events involving the webhook as instructed at https://stripe.com/docs/payments/checkout/fulfill-orders. On top of that the Stripe server never attempts to send anything to my webhook. The checkout.session.completed event says "No recent webhook attempts" so this thing that supposedly enabled webhooks appears to just freeze my cmd.exe program.

**Comment by tomer-stripe** [comment]
Hey @PostAlmostAnything! The `listen` command isn't interactive, we don't allow you to type anything in the command prompt after it's running.

We'll need to investigate the issue around quitting. Could you share which operating system and what terminal you're using?

**Comment by PostAlmostAnything** [comment]
It turned out to be a version conflict. Appears to be working fine now.
