### ISSUE TITLE
Cannot install on ubuntu 

### ISSUE THREAD

**Issue by Any28Flo** [stripe/stripe-cli#641]
### Issue
When I tried to install on ubunto nothing happen, 
I followed the steps in the Stripe page without succes. Also I tried to install via apt-get, but I don't have success. Any idea?
![Screenshot from 2021-04-22 10-13-01](https://user-images.githubusercontent.com/25911909/115740955-edf88680-a354-11eb-89ec-f2b2aa5b75f5.png)

### Expected Behavior
The steps to sucellfully install on Linux

### Steps to reproduce
Go to console in ubuntu 20.04

   1. Download the latest linux tar.gz file from https://github.com/stripe/stripe- cli/releases/latest
   2. Unzip the file: tar -xvf stripe_X.X.X_linux_x86_64.tar.gz
   3. Run the executable: ./stripe

### Environment
_Select one of: Linux,

**Comment by tomer-stripe** [comment]
Hey @Any28Flo! Unfortunately service we were using previously to have `apt-get` installs of the CLI has been deprecated. The CLI itself does not install into a specific location, if you want to execute it as a command you'll need to move it to your bin folder manually.

**Comment by makeshack** [comment]
@tomer-stripe 

I'm simply curious. Is there another easier way to install on WSL (other than the method above)? Or is that the only way to do it.

**Comment by codersaadi** [comment]
Worked for me . Ubuntu latest 
download the latest cli release `(source code tar.gz)` from [stripe-cli](https://github.com/stripe/stripe-cli/releases/latest)
Extract it :` tar -xvf stripe-cli-1.21.9.tar.gz `
`cd stripe-cli-1.21.9`  
 (you version may differ)
` sudo mv ./cmd/stripe/usr/local/bin/stripe`
