### ISSUE TITLE
not receıvıng payments from customers

### ISSUE THREAD

**Issue by SMAali02** [stripe/stripe-cli#651]
how can ı fınd out ıf ı m receıvıng any payments from customers, ı m tryıng to help a chıld who has SMA  and we dont have much tıme left, how can ı raıse money to help thıs nonprofıt charıty and where can ı check ıf some1 tryıng to gettıng contact wıth me or make a payment

**Comment by tomer-stripe** [comment]
Hey @SMAali02, please reach out to support@stripe.com, we're unable to help with this.
