### ISSUE TITLE
Bintray repository is broken

### ISSUE THREAD

**Issue by syslogic** [stripe/stripe-cli#656]
I'm not sure if this is/was an official repository, but if so - it is currently broken.

### Issue
I've tried to update the Stripe CLI with `dnf`.
### Expected Behavior
Bintray to provide `repomd.xml`.
### Steps to reproduce

File `/etc/yum.repos.d/stripe-cli.repo`:

    [stripe-cli]
    name=Stripe CLI
    baseurl=https://dl.bintray.com/stripe/stripe-cli-rpm
    gpgcheck=0
    repo_gpgcheck=0
    enabled=1

`sudo dnf update stripe-cli`

See https://bintray.com/stripe/stripe-cli-rpm/rpm

### Traceback
Errors during downloading metadata for repository 'stripe-cli':
  - Status code: 403 for https://dl.bintray.com/stripe/stripe-cli-rpm/repodata/repomd.xml (IP: 3.125.168.216)
Error: Failed to download metadata for repo 'stripe-cli': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
### Environment
Linux

**Comment by tomer-stripe** [comment]
Sadly bintray is being shutdown and we've not been able to find a suitable replacement: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Sorry about the trouble, for now the only alternative we have is to download the files for Linux manually from GitHub.

**Comment by syslogic** [comment]
With `rpmbuild` & `createrepo --update` (as build step) this is rather flexible
and such a repository could be hosted on just any web-server / subdomain.

**Comment by pentatonicfunk** [comment]
@syslogic did you successfully add rpm package to COPR ?
trying to find alternative / workaround, but not manual download / install

**Comment by mattfox** [comment]
I'd like to offer my service [Balto Repo](https://www.getbalto.com/) for hosting this repo, as I mentioned in #666 which I was aware of earlier than this issue. I went ahead and created an example repo with the most recent .rpm file. It's available here: https://stripe.baltorepo.com/stripe-cli/rpm/ 

Merge request https://github.com/stripe/stripe-cli/pull/673 shows how the README could be updated to reference the new repos.

**Comment by ctjlewis** [comment]
How do we prevent this from causing apt errors? It is effectively vandalism to not tell users how to prevent this from blocking their OS upgrades.

**Comment by dotnetCarpenter** [comment]
@syslogic, you might be interested in trying out [my bash script](https://github.com/dotnetCarpenter/dotfiles/blob/master/install-stripe-cli) to install the latest stripe-cli and I would be very interested to know how it works on a redhat system.

I wrote a lengthy presentation in https://github.com/stripe/stripe-cli/issues/666#issuecomment-1079704202, if you're interested.

cc @pentatonicfunk @ctjlewis

**Comment by etsai-stripe** [comment]
CLI linux binaries now migrated off bintray. installations steps updated at https://stripe.com/docs/stripe-cli

**Comment by dotnetCarpenter** [comment]
@etsai-stripe @suz-stripe `curl https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | apt-key add -` as advertised on https://stripe.com/docs/stripe-cli for `apt` does not work on Ubuntu 21.10.

```
$ curl https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | apt-key add -
(23) Failed writing body
```
