### ISSUE TITLE
Way to programmatically get webhook signing secret from Stripe listen?

### ISSUE THREAD

**Issue by mehagar** [stripe/stripe-cli#672]
### Feedback

When I spin up new (UAT or "staging") instances of my application, I want them to automatically connect to Stripe and listen for events via a webhook. Each new instance has a different domain name, so I would need to configure a separate webhook for it. With the Stripe CLI, I could do `stripe listen` from a container, but it seems like the tool is meant to be used interactively because the webhook signing secret returned is displayed so it can be manually copied to the application's configuration. Is there an easy way to parse the webhook signing secret from a docker container that runs `stripe listen`? That way when a new instance is automatically spun up, I could parse the webhook signing secret and add it to the app's config. This may not be the use case for stripe listen, though. 

I have thought of two other ways to do this:

1. Use the Stripe REST API to add a new webhook, and use the webhook signing secret returned in the JSON response. I would then have to clean up by removing the webhook endpoint when the instance is destroyed.
2. Inside the app itself, once the instance is created, let users add a webhook through the Stripe dashboard and then add the webhook signing secret for it themselves through the UI. I would prefer users not have to know about this, though.

Any thoughts on these approaches, or is there another way to do this?

**Comment by pepin-stripe** [comment]
Hello @mehagar,

This is currently not possible without parsing the logs.

We are actively developing a gRPC interface for the CLI, making it easier to programmatically interact with it, including getting the webhook signing secret back from calling `listen`.
If you are curious, here's a [PR](https://github.com/stripe/stripe-cli/pull/574/files) that adapts the `listen` command to work with the gRPC interface.

We don't have a set release date yet, but we're making good progress. More info and docs will be released once ready.

Closing this issue, but please feel free to reopen with additional questions.

Cheers
Jonathan

**Comment by pepin-stripe** [comment]
@mehagar also worth nothing that you can run `stripe listen --print-secret` and the Stripe CLI will only print the signing secret, which will make it easier to parse before running `stripe listen`.

**Comment by SrBrahma** [comment]
@pepin-stripe any update? Would be good if I could set an env var after getting it, in a cli way.

Like ~ `STRIPE_WEBHOOK_SECRET_DEV={stripe getDevSecret} && npm run startServer`
