### ISSUE TITLE
Thanks for the issue! Asking the payouts product team about this :)

### ISSUE THREAD

**Issue by giulianalembo** [stripe/stripe-cli#684]
Thanks for the issue! Asking the payouts product team about this :)

_Originally posted by @tomer-stripe in https://github.com/stripe/stripe-cli/issues/604#issuecomment-796870630_

**Comment by tomer-stripe** [comment]
Hey @giulianalembo! Going to close this in favor of #604 

We're still chatting with the team, trying to figure out how to do this with minimal side effects

**Comment by giulianalembo** [comment]
Ma il pagamento arriva ho anche chiamato il supporto stripe
