### ISSUE TITLE
How to test webhook locally without sending data to external server?

### ISSUE THREAD

**Issue by BizzyBob** [stripe/stripe-cli#685]
### Issue
I'm attempting to test the payment flow locally from web app form submission to webhook payment notification logic on local server.  I use the `stripe listen --forward-to=http://localhost:5001/webhook` command to send webhook payloads to my local back end server.  However, whenever I submit a payment form on my local web app, the webhook payload is sent both to my local server and the external server.

The same behavior is seen when using `stripe trigger`; both servers receive the payload.

### Expected Behavior
I would expect there is a way to work with the local dev environment without affecting other environments at all.  

Is there a way to prevent data from being pushed to external server when developing locally?

I understand use of `stripe.js` involves the stripe server to be involved in the process, but it seems like since the CLI is intercepting traffic, it could mark requests to indicate  as "local only" so that the notification is not posted to configured "external" endpoint. Or maybe there is a way to generate API keys for local testing, that the stripe server would recognize as such and not post to the configured "external" endpoint.

Any general info on a better local development flow would be appreciated.

### Steps to reproduce
 - create a webhook that sends payloads to some "external" server
 - run cli command: `stripe listen --forward-to={local server address}`
 - run cli command `stripe trigger payment_intent.succeeded`
     - notice the payload is received by both local dev server and external server

### Environment
 - macOS: 10.15.7
 - Stripe CLI: 1.6.1
 - Stripe JS: v3

**Comment by cjavilla-stripe** [comment]
I'm guessing you have a webhook endpoint configured in testmode that is pointing at a public web server. Running 'stripe listen' creates a second endpoint. 

When events happen on your Stripe account notifications for a given event are sent to all webhook endpoints. 

To avoid sending to production, you'd need to remove the webhook endpoint that's pointing to that production server. You can remove the endpoint from the Stripe dashboard. 

Since this is for development, be sure not to accidentally remove any live mode endpoints :)

**Comment by BizzyBob** [comment]
Hi @cjavilla-stripe, thank you very much for your response.

I didn't realize running CLI basically creates an additional webhook for an existing api key.

You are correct, I do have a webhook configured in testmode.  However, it is being used by my staging server; so if I remove it, that environment will no longer receive posts.  I do not want my local development to affect staging or production.

I'm trying to figure out good local dev workflow to make changes to the existing webhook code and test it locally.  I ended up using postman instead of Stripe CLI to dispatch events, but I prefer to be able to send them by interacting my web app.

My code is set up to load stripe credentials from environment variables, so my plan was to generate separate keys for different environments.  I'm brand new to Stripe API, so maybe that's not how it works.  It seems like what I need to do is create a completely different stripe account for local development vs staging/development.

Does that sound reasonable?

**Comment by cjavilla-stripe** [comment]
@BizzyBob I wanted to follow up to your last question about using a separate Stripe account for local vs staging. Having an account purely for development is common.
