### ISSUE TITLE
Unable to udpdate (then re-install) Stripe CLI on Ubuntu 

### ISSUE THREAD

**Issue by Pablolo** [stripe/stripe-cli#689]
**Problem**

I tried to update the Stripe CLI on ubuntu, downloading the .tar file manually from https://github.com/stripe/stripe-cli/releases/tag/v1.6.3

Trying to run the executable with the command ./stripe didn't provide me with any update, just this help message:

![caputra (1)](https://user-images.githubusercontent.com/4686010/121723505-84882f00-cade-11eb-8bb1-042c0e40357b.png)

So I tried to uninstall the CLI and now, I cannot re-install, because when I write ./stripe it shows the same previous message.

I write simply 'stripe' the terminal now says:

zsh: command not found

**Comment by tomer-stripe** [comment]
Hey @Pablolo! Did you previously install with the package manager? We had to remove our old one and are working on a new solution there but haven't gotten it deployed yet.

Downloading the `tar` wouldn't automatically put it in the executable path like previously, so you would either need to move it manually or keep running it as `./stripe`.

**Comment by Pablolo** [comment]
Thank you @tomer-stripe, yes I believe I previously installed it with the package manager, I saw you had some trouble with it. 

How can I move it manually? I've been searching for quite some time this same solution but so far I haven't had any success. 

Thank you very much

**Comment by holmberd** [comment]
@Pablolo you need to remove the repository from `apt`, either through the auto-updater settings, or using CLI.

```sh
$ cat /etc/apt/sources.list | grep stripe-cli-deb
deb https://dl.bintray.com/stripe/stripe-cli-deb stable main

$ sudo add-apt-repository -r ppa:<ppa to remove>
```

* https://help.ubuntu.com/community/Repositories

**Comment by Pablolo** [comment]
Thank you very much @holmberd
