### ISSUE TITLE
Windows blocking Stripe CLI - Trojan

### ISSUE THREAD

**Issue by germanolira** [stripe/stripe-cli#691]
Today June 15, 2021, Windows started blocking the Stripe CLI, (Trojan:Win32/email.A!cl), the problem started appearing today, Stripe 1.6.3

### Issue
Using the Stripe CLI `stripe listen --forward-to localhost:3000/api/webhooks`

### Expected Behavior
Stripe starts listening for events at the port 3000

### Steps to reproduce
`stripe listen --forward-to localhost:3000/api/webhooks`

### Traceback
![image](https://user-images.githubusercontent.com/25235170/122134548-32fcde80-ce15-11eb-8c31-633464370271.png)
![image](https://user-images.githubusercontent.com/25235170/122134587-4a3bcc00-ce15-11eb-8c79-67bff17e5764.png)

### Environment
Windows 10, version 21H1

**Comment by tomer-stripe** [comment]
Hey @germanolira, thanks for the report. This is a false positive that we don't have much control over at the moment. I created #692 as a heads up to users so I'll close this issue for now.
