### ISSUE TITLE
Clear data command

### ISSUE THREAD

**Issue by GrandSchtroumpf** [stripe/stripe-cli#697]
### Problem
I would like to clear all data from stripe before running my E2E tests.

### Feature
Add a command `stripe clear` that should clear all data from the test environment. Like the "Delete all test data" button from the [dashboard](https://dashboard.stripe.com/test/developers) is doing.

### Examples
Before running a E2E test I would do : 
```
stripe clear --confirm
stripe fixture fixture.json
```
Like that I'm sure I do not create side effect between two tests.

**Comment by GrandSchtroumpf** [comment]
As an intermediary feature it would be nice to be able to delete a whole collection.
For example to remove all accounts : 
```
stripe accounts delete --all
```

**Comment by pepin-stripe** [comment]
Thanks for the feedback @GrandSchtroumpf. We are currently looking into how to improve test environment, test data and its deletion. 

This is not possible with our current infrastructure, but I love the idea of being able to clear data from the CLI so I'll definitely keep that on the backlog for our new test environment products.

Cheers
Jon
