### ISSUE TITLE
Stripe CLI connection refused when testing stripe webhook locally

### ISSUE THREAD

**Issue by akinwol** [stripe/stripe-cli#703]
I am using the stripe CLI to test my stripe webhook locally.  I have already implemented the webhook in production it works. 
I recently updated the stripe CLI and the webhook does not work anymore. Also recently updated the mac os so not sure if it has anything to do with that. 

I use the CLI locally when I am testing any feature that has to do with payments. 

I run this command  
stripe listen --forward-to https://localhost:5000/webhook 

But when testing I get this error 
Failed to POST: Post "https://localhost:5000/webhook": dial tcp 127.0.0.1:5000: connect: connection refused  

I also tried the curl as per the comment in another thread and I get the following error 
   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 5000 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 5000 failed: Connection refused
* Failed to connect to localhost port 5000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 5000: Connection refused

Not sure what happened and why it does not work anymore. This is in my local environment on mac os 11.4

**Comment by akinwol** [comment]
This was not an issue with the CLI for me but with my local environment.

**Comment by suz-stripe** [comment]
@akinwol glad you figured it out! Also thanks for closing the issue once you solved the problem.
