### ISSUE TITLE
Clean up products created from webhook tests

### ISSUE THREAD

**Issue by davidbielik** [stripe/stripe-cli#707]
### Problem

I'm using Stripe CLI to test out webhooks, and in my test-mode Products, I see a _ton_ of `myproduct ($20.00 USD / Month)` products. This makes it difficult when comparing live/test mode and adds clutter to the testmode dashboard.

### Feature

Would it be possible to automatically delete objects created via CLI webhook tests?

![image](https://user-images.githubusercontent.com/7410770/126020938-eb5ffa6a-b54d-4c5a-9b52-5a80ddd7d3b9.png)

Thanks!

**Comment by pepin-stripe** [comment]
Thanks a lot for the feedback! Although you're mentioning products created through the CLI this feedback relates more to our API and how test data is managed instead. 
Github issues are limited to bugs or feature requests with the CLI itself so I recommend reaching out to our support team directly and they can help you better raise the feedback to our engineering team. You can contact them on https://support.stripe.com/contact/email

**Comment by awmcclain** [comment]
> Thanks a lot for the feedback! Although you're mentioning products created through the CLI this feedback relates more to our API and how test data is managed instead. Github issues are limited to bugs or feature requests with the CLI itself so I recommend reaching out to our support team directly and they can help you better raise the feedback to our engineering team. You can contact them on https://support.stripe.com/contact/email

I suppose that's technically correct, but it also has to do with the default fixtures that ship with the CLI. Is it possible to include delete calls after the event is sent? This makes any sort of testing really messy when using the CLI.

**Comment by pepin-stripe** [comment]
That's a good idea - can you share which CLI commands you're running in particular? 

Thanks!

**Comment by awmcclain** [comment]
`stripe trigger customer.subscription.created`. 

Every time you run that to test your webhook you generate a new:
* Customer
* Product
* Price
* Subscription

**Comment by pepin-stripe** [comment]
Yeah that makes sense, very noisy indeed!

I'll file a task internally for us to look at - there's a lot of effort
around testing being done right now, so thanks again for the feedback!

Meanwhile, are you aware you can have all your test data deleted? I
understand it's probably not what you are looking for, but in case you want
to be able to reset your test state once in a while, that might be useful!

**Comment by awmcclain** [comment]
> Meanwhile, are you aware you can have all your test data deleted?

oh! really? is that something I have to file a ticket for?

**Comment by pepin-stripe** [comment]
Not at all, it's self-serve and you can run it anytime!

If you log on the developer dashboard in test mode (
https://dashboard.stripe.com/test/developers), you should see a section
"Test Data" at the bottom of the page with a "Delete all test data..."
button.

**Comment by cecilphillip-stripe** [comment]
@pepin-stripe is it / will it be possible to to invoke this from the CLI?

**Comment by dirkesquire** [comment]
Hello, 
Two years later and I find myself in the exact same situation. I was happily testing with `stripe trigger checkout.session.completed`

All was fun at first, until I later released that on each run it had created hundreds of:

- products called: "my product"
- new customer: 'stripe@example.com'

Now I will never use this stripe_cli again, because of the mess it makes.

1) Why is there no stripe-cli command to cleanup this data?
2) Why doesn't the test reuse the same customer and product instead of creating duplicate named ones? That would at least be acceptable.

**Comment by MatthewDegtyar** [comment]
Is there at least a better flow to use while testing Stripe webhooks? Dealing with such obtuse sdk behavior is annoying when alternatives/work arounds are clumsy at best

**Comment by davidbielik** [comment]
I've learned to live with this, but for anyone else, it shouldn't be hard to write a script that looped through these created objects, filter by "myproduct" and delete in a cleanup hook in your tests.
