### ISSUE TITLE
Need EULA or License details for stripe-cli

### ISSUE THREAD

**Issue by titus-accenture** [stripe/stripe-cli#709]
Hello,

We need some details on stripe-cli license, I was able to find the license link from GitHub (https://github.com/stripe/stripe-cli/blob/master/LICENSE) but we cannot use it since its not hosted under your official stripe domain.

Kindly share link for stripe-cli EULA or License under any official stripe domain.

Note: I am not sure this is the correct place to raise this, but I send an Email to info@stripe.com and they redirected me to GitHub saying ` the Developer Products team there actively maintains this repository and should be able to help.`

I hope you can help me on this, Thanks

**Comment by tomer-stripe** [comment]
Hey @titus-accenture! Let me look into this, I don't have much familiarity here.

**Comment by tomer-stripe** [comment]
@titus-accenture so the CLI is licensed under Apache 2.0 and we are verified on GitHub as being Stripe: https://github.com/stripe

The repo itself is linked to from our official stripe.com docs too: https://stripe.com/docs/stripe-cli

Does any of that help? Is mentioning that the CLI is licensed under Apache 2.0 within our stripe.com docs help?

**Comment by titus-accenture** [comment]
@tomer-stripe Thanks, that helps :smile:

**Comment by tomer-stripe** [comment]
Happy to help! We also add a section on the CLI reference with the repo and a call out of the license: https://stripe.com/docs/cli/license
