### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by ycandrewkao** [stripe/stripe-cli#710]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
I was testing subscription webhook locally. Our webhook is running using Azure Function (which was running locally at the time). We used `stripe listen --forward-to <localhost>` command. However, are are seeing `Client.Timeout exceeded while awaiting headers` error seemingly randomly. What could be causing that? How do we fix it? Our server is using Azure Function, which has a 5 min timeout, which we are definitely not hitting.

### Expected Behavior
We expect it to work all the times.

### Steps to reproduce
It seems to happen randomly. 

### Traceback
See screenshot

### Environment
mocOS
![Screen Shot 2021-07-21 at 10 28 49 AM](https://user-images.githubusercontent.com/8906298/126548246-0e1412ca-04b9-4adf-8610-38d35b9f8344.png)

**Comment by pepin-stripe** [comment]
Hi @ycandrewkao,

The CLI has a timeout of 30 seconds when proxying events to another endpoint (in your case set with `--forward-to http://localhost:7071/stripewebhook`), so it seems like this is what we're seeing here. Would that make sense? Do you see the timeout error being logged ~30s after the event was received the CLI?

**Comment by pepin-stripe** [comment]
Closing this out but please feel free to re-open if you have additional questions!

**Comment by gabrielmsoptimalex** [comment]
I'm having the same issue. And yes the "FAIL" message does appear 30s after the request. 
<img width="1900" alt="Screen Shot 2022-12-14 at 12 15 20" src="https://user-images.githubusercontent.com/91923731/207634242-788770cc-c925-4155-8cc3-e1f760340bfb.png">

**Comment by banagale** [comment]
@pepin-stripe 
> Closing this out but please feel free to re-open if you have additional questions!

Mentioned this in #1010, but it would be cool if this could be configured. 

That way conditional logic on any given POST could be debugged for at least a few minutes without having to repeat checkout config and submission that triggered the issue.

**Comment by jpodpro** [comment]
This can't be configured? How is it useful to step through the code when you only get 30 seconds or else all subsequent webhooks fail?

**Comment by OveshTappN** [comment]
what is the solution for this..?
