### ISSUE TITLE
Fixture parameter value with environment variable is truncated

### ISSUE THREAD

**Issue by zmk-punchbowl** [stripe/stripe-cli#718]
### Issue
Using a Stripe fixture to set up a webhook, I'm using an environment variable to help build the `url` parameter. 

```
{
  "_meta": {
    "template_version": 0
  },
  "fixtures": [
    {
      "name": "create_webhook_endpoint",
      "path": "/v1/webhook_endpoints",
      "method": "post",
      "params": {
        "url": "${.env:BASE_API_URL}/hook/stripe",
        "enabled_events": [
          "customer.subscription.created",
          "customer.subscription.deleted",
          "customer.subscription.updated",
          "customer.subscription.pending_update_applied",
          "price.created",
          "price.updated"
        ]
      }
    }
  ]
}
```

The fixture succeeds, but the created webook `url` only includes the `BASE_API_URL` value (e.g. `https://myapi.example.com`) and not the `/hook/stripe` portion. It appears to truncate the text that comes after that environment variable.

### Expected Behavior
I expect the webhook `url` to reflect the full value defined in the fixture.

### Steps to reproduce
Run the above fixture (with that environment variable set)

### Traceback
(it succeeds)
```
Setting up fixture for: create_webhook_endpoint
```

### Environment
macOS
CLI version 1.7.0

**Comment by gracegoo-stripe** [comment]
Thanks for the bug report! I've merged a fix for it here: https://github.com/stripe/stripe-cli/pull/719
