### ISSUE TITLE
Trigger payment_intent.succeeded event associated with any Subscription

### ISSUE THREAD

**Issue by WaleedFarooq222** [stripe/stripe-cli#720]
### Problem
I'm trying to get the subscription id from payment_intent.succeeded event, as I'm triggering payment_intent.succeeded which is not associated with any current subscription in test mode, I'm unable to get the subscription id. 

### Feature
It will help me to update the data of the subscription associated in my website 

### Examples
I've a subscription system in my website, so when user buy the subscription it adds some installs in his account, and when subscription get renewal, it will update the installs in user account associated with that subscription

**Comment by pepin-stripe** [comment]
Thanks a lot for the feedback. Github issues are limited to bugs or feature requests with the CLI itself and it looks like you have feedback about our APIs instead. I recommend reaching out to our support team directly and they can help you better understand how to approach this and also raise the feedback to our engineering team. You can contact them on https://support.stripe.com/contact/email
