### ISSUE TITLE
Parameter missing

### ISSUE THREAD

**Issue by gurpreetcheemaji** [stripe/stripe-cli#722]
{ "error": { "code": "parameter_unknown", "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown", "message": "Received unknown parameters: object, limit", "param": "object", "type": "invalid_request_error" } }

$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/customers/cus_Jxgjdf4no6SpzLD/sources');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "object=card&limit=3");
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_USERPWD, 'sk_test_***' . ':' . '');

		$headers = array();
		$headers[] = 'Content-Type: application/x-www-form-urlencoded';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);

**Comment by pepin-stripe** [comment]
hello @gurpreetcheemaji,

it seems like you are passing the parameters to your request to add a source to your customer: `object=card&limit=3`.
The error is saying that both `object` and `limit` are invalid parameters.

To add a source to a customer, the source must be created first, and then the parameter you'd pass to your call is the source id.

You can see more details on our docs here: v1/customers/cus_Jxgjdf4no6SpzLD/sources
