### ISSUE TITLE
Stripe customer reconciliation with website user in webhooks

### ISSUE THREAD

**Issue by boberbober** [stripe/stripe-cli#724]
### Problem
When creating a new checkout session in `subscription` mode, it's not easy to reconcile the webhook data from events such as `invoice.paid` or `customer.subscription.updated` with my user entry that started the session.

e.g. a user on my website wants to pay for a subscription plan, I generate a new checkout session for them and send them to the Stripe checkout page, they finish paying and are redirected to my `success_url`, I then have to wait for an event from Stripe with the payment confirmation to confirm a successful subscription.

When I create a checkout session in `mode: 'payment'` I can add `client_reference_id: USER_ID` and that user id is returned to my webhook with the `payment_intent.succeeded` event. But not for subscriptions. I tried other event types but none of them have the necessary data to reconcile the newly created Stripe customer with my user.

So now I'm creating a new customer with `stripe.customers.create()` before, and only then create a payment session with `stripe.checkout.sessions.create({ customer: customerId, ... })`, which is an unnecessary step.

### Feature
It would be great if all the necessary data to confirm a successful payment and attach it to my user database entry came in one event for each action. It should contain my userId that I passed to `stripe.checkout.sessions.create()`, and the amount paid, and the `subscription.id`. Now it's kinda scattered between `invoice.paid` or `customer.subscription.updated` or `payment_intent.succeeded` events.

**Comment by pepin-stripe** [comment]
Thanks a lot for the feedback. 
Github issues are limited to bugs or feature requests with the CLI itself and it looks like you have feedback about our APIs instead. I recommend reaching out to our support team directly and they can help you better understand how to approach this and also raise the feedback to our engineering team. 
You can contact them on https://support.stripe.com/contact/email
