### ISSUE TITLE
stripe get [ID] does not work with SubscriptionSchedules

### ISSUE THREAD

**Issue by yched** [stripe/stripe-cli#737]
### Issue
`stripe get [ID]` does not seem to know how to map IDs of SubscriptionSchedules to an actual API endpoint

### Steps to reproduce
```
$ stripe get sub_sched_1JXMyfC1vOA06qh5UNJJMwcA
{
  "error": {
    "message": "Unrecognized request URL (GET: /v1/sub_sched_1JXMyfC1vOA06qh5UNJJMwcA). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}
```

I need to use the more verbose `stripe subscription_schedules retrieve [ID]` to be able to access the data

### Environment
Linux (Ubuntu), stripe CLI 1.7.0

**Comment by pepin-stripe** [comment]
Hey @yched thanks for reporting! I'll look into this and let you know when we make progress!

**Comment by pepin-stripe** [comment]
PR merged and will be part of the next CLI release!
