### ISSUE TITLE
No available formula or cask with the name "stripe/stripe-cli/stripe"

### ISSUE THREAD

**Issue by erhan-data** [stripe/stripe-cli#742]
Try to exec **brew install stripe/stripe-cli/stripe**
### Issue
No available formula or cask with the name "stripe/stripe-cli/stripe"

### Expected Behavior
Shall install the stripe cli

### Steps to reproduce
Try to exec **brew install stripe/stripe-cli/stripe**

### Traceback
Warning: No available formula or cask with the name "stripe/stripe-cli/stripe".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.

### Environment
macOS with Apple M1 Chip

**Comment by wakeuphate** [comment]
Ran into this issue while trying to upgrade, removed the package thinking it might've been my homebrew and now I get the same thing upon trying to reinstall.

Looks like the ARM64 build wasn't added to the releases for this version either: https://github.com/stripe/stripe-cli/releases/tag/v1.7.2 vs https://github.com/stripe/stripe-cli/releases/tag/v1.7.1

**Comment by tomer-stripe** [comment]
Weird, I'm not sure why this happened. Will look into this!

**Comment by tomer-stripe** [comment]
Fixed! ARM's been added back to the homebrew formula so everything should work now: https://github.com/stripe/homebrew-stripe-cli/blob/master/stripe.rb (just verified it on my device).

Closing but please re-open if you keep having problems

**Comment by Simonl9l** [comment]
still an issue 
```log 
~ % brew install stripe            
Warning: No available formula with the name "stripe". Did you mean strace?
==> Searching for similarly named formulae...
This similarly named formula was found:
strace
To install it, run:
  brew install strace
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by AlekseyMalakhov** [comment]
Got this issue
`aleksey.malakhov@nba-215-v2b-lt ~ % stripe -v
stripe version 1.14.7
aleksey.malakhov@nba-215-v2b-lt ~ % brew upgrade stripe/stripe-cli/stripe
Error: No available formula or cask with the name "stripe/stripe-cli/stripe".
Please tap it and then try again: brew tap stripe/stripe-cli
aleksey.malakhov@nba-215-v2b-lt ~ % brew tap stripe/stripe-cli
==> Tapping stripe/stripe-cli
Cloning into '/opt/homebrew/Library/Taps/stripe/homebrew-stripe-cli'...
remote: Enumerating objects: 499, done.
remote: Counting objects: 100% (331/331), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 499 (delta 108), reused 197 (delta 65), pack-reused 168
Receiving objects: 100% (499/499), 69.24 KiB | 908.00 KiB/s, done.
Resolving deltas: 100% (163/163), done.
Tapped 1 formula (13 files, 100.2KB).
aleksey.malakhov@nba-215-v2b-lt ~ % brew upgrade stripe/stripe-cli/stripe
Error: stripe/stripe-cli/stripe not installed
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/ca-certificates--2023-08-22... (125.2KB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/gh--2.31.0... (9.7MB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/redis--7.2.3... (924.0KB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/yarn--1.22.19... (1.2MB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/gh_bottle_manifest--2.30.0... (7.3KB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/yarn_bottle_manifest--1.22.19... (1.8KB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/gh_bottle_manifest--2.31.0... (7.4KB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/Cask/redis-stack--7.2.0-6... (0B)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/Cask/redis-stack-server--7.2.0-v6.zip... (18.2MB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/Cask/ngrok--3.5.0.zip... (8.4MB)
Removing: /Users/aleksey.malakhov/Library/Caches/Homebrew/Cask/dbeaver-community--23.1.0.dmg... (114.3MB)
Removing: /Users/aleksey.malakhov/Library/Logs/Homebrew/gh... (64B)
Removing: /Users/aleksey.malakhov/Library/Logs/Homebrew/openssl@3... (64B)
Removing: /Users/aleksey.malakhov/Library/Logs/Homebrew/ca-certificates... (64B)
Pruned 0 symbolic links and 2 directories from /opt/homebrew
aleksey.malakhov@nba-215-v2b-lt ~ % stripe -v                            
stripe version 1.14.7
aleksey.malakhov@nba-215-v2b-lt ~ % brew upgrade stripe/stripe-cli/stripe
Error: stripe/stripe-cli/stripe not installed
aleksey.malakhov@nba-215-v2b-lt ~ % `
