### ISSUE TITLE
Error/crash when specifying a top-level parameter override for stripe trigger

### ISSUE THREAD

**Issue by johnpitchko** [stripe/stripe-cli#755]
### Issue
Trying to fire a Stripe event `customer.subscription.deleted` from the CLI while specifying a valid customer in our test instance. I ran the following command: `stripe trigger customer.subscription.deleted --override customer=cus_K71blC10XyAGFf`.

Note this issues *does not* affect multilevel parameter, such as `plan:nickname` only top-level ones like `customer`.

### Expected Behavior
Expected the trigger to run successfully and include the customer id specified.

### Steps to reproduce
Run the command listed above.

### Traceback
```
goroutine 1 [running]:
github.com/stripe/stripe-cli/pkg/fixtures.buildRewrites({0xc00033bf60, 0x1, 0x17a58e0}, 0x0)
	/Users/runner/work/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:345 +0x5ab
github.com/stripe/stripe-cli/pkg/fixtures.(*Fixture).Override(0xc00024b8c0, {0xc00033bf60, 0xc0001e96a0, 0x17a58e0})
	/Users/runner/work/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:115 +0x38
github.com/stripe/stripe-cli/pkg/fixtures.NewFixture({0x1afb740, 0x20c3fd0}, {0xc0000c6980, 0x6b}, {0x0, 0x0}, {0x19156cd, 0x16}, {0x192c700, 0x2b}, ...)
	/Users/runner/work/stripe-cli/stripe-cli/pkg/fixtures/fixtures.go:102 +0x2b0
github.com/stripe/stripe-cli/pkg/fixtures.BuildFromFixture({0x1afb740, 0x20c3fd0}, {0xc0000c6980, 0xa}, {0x0, 0x114ecb4}, {0x19156cd, 0xc0002600c0}, {0x192c700, 0x2b}, ...)
	/Users/runner/work/stripe-cli/stripe-cli/pkg/fixtures/triggers.go:73 +0x108
github.com/stripe/stripe-cli/pkg/fixtures.Trigger({0x7ffeefbff817, 0x1d}, {0x0, 0x0}, {0x19156cd, 0x16}, {0xc0000c6980, 0x6b}, {0x20c3fd0, 0x0, ...}, ...)
	/Users/runner/work/stripe-cli/stripe-cli/pkg/fixtures/triggers.go:121 +0x17f
github.com/stripe/stripe-cli/pkg/cmd.(*triggerCmd).runTriggerCmd(0xc000251720, 0xc00029fc18, {0xc0003cd500, 0x1, 0x0})
	/Users/runner/work/stripe-cli/stripe-cli/pkg/cmd/trigger.go:79 +0x1ab
github.com/spf13/cobra.(*Command).execute(0xc00025ec80, {0xc0003cd4d0, 0x3, 0x3})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x2087120)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/stripe/stripe-cli/pkg/cmd.Execute()
	/Users/runner/work/stripe-cli/stripe-cli/pkg/cmd/root.go:64 +0xa5
main.main()
	/Users/runner/work/stripe-cli/stripe-cli/cmd/stripe/main.go:6 +0x17
```

### Environment
macOS v11.5.2
stripe cli v1.7.3

**Comment by pepin-stripe** [comment]
HI @johnpitchko,

Sorry for the docs not being super clear on that. I think I can see 2 issues here that are causing the crash:

1. The format for the `--override` option is `[param]:[path1].[path2]=[value]`  
So in your example, the command should be called as follow:
`stripe trigger customer.subscription.deleted --override customer:id=cus_K71blC10XyAGFf`
Notice "customer" is the name of the resource you want to override, followed by a `:`, then "id" being the resource's param you want to override, follow by a `=` and the value of the param. 

2. `--override`, `--add`, etc only support Stripe API's valid parameters  
When using `stripe trigger`, resources are being created with the Stripe API to be able to have the webhook event actually triggered, so in your example, the CLI actually creates a customer, a plan, a subscription and finally deletes that subscription for the `customer.subscription.deleted` event to be triggered.
Unfortunately, the Stripe API doesn't allow `id` to be passed as a param during creation, so what you are trying to achieve is invalid.

I think I understand that you are trying to trigger the `customer.subscription.deleted` event for an existing customer object, probably for automated tests - unfortunately this is not supported yet. If you really needed that to be possible, see my next comment on how to update/write your own fixture for trigger.

We're actively working on improving Stripe's testing experience, but can't offer any features or timeline yet.

Hope this helps - I'll close the task but please feel free to re-open if you have additional questions.

**Comment by pepin-stripe** [comment]
The way the `stripe trigger` command works is, it parses "fixture" files that provide the command a list of resources to create with the Stripe API to have the relevant event triggered.

In your case, `stripe trigger customer.subscription.deleted` uses the fixture here: https://github.com/stripe/stripe-cli/blob/master/pkg/fixtures/triggers/customer.subscription.deleted.json. We can see it
1. creates a customer
2. creates a plan
3. creates a subscription with the created customer's id
4. deletes the subscription, which triggers the `customer.subscription.deleted` event.

You could override this file locally to 
1. remove lines 6-14, to prevent the CLI from creating a new customer
2. update line 33 replacing `"${customer:id}"` with the id of the existing customer you the charge to be linked to

Hopefully we'll be able to support full object override for `stripe trigger` soon, but we don't have a timeline to offer.

Cheers
Jonathan

**Comment by AbdulkarimOgaji** [comment]
@pepin-stripe im im trying to overide the plan of the subscription but it doesnt seem to work. i have tried `--override subscription:plan.id=price_sfasfdadgf` and `--override subscription.plan:id=price_sasfdfsfgbsdfb`  if i cant modify id, how else can i specify the plan that will be subscribed to.
  the event im trying to test is `customer.subscription.created`
