### ISSUE TITLE
Wrong event send on stripe trigger balance.available

### ISSUE THREAD

**Issue by Ydrasil** [stripe/stripe-cli#757]
### Issue
I think that I've found an issue
When I try to trigger an event with balance available: `stripe trigger balance.available`
Stripe client setup a fixture for `payment_intent`

### Expected Behavior
By using the command `stripe trigger balance.available` I expect that an event is sent with the correct object, in this case a `Balance` 

### Steps to reproduce
- Download Stripe client version 1.7.3
- Run `stripe listen` in a terminal
- Run `stripe trigger balance.available` in another terminal

### Traceback
![stripe_issue](https://user-images.githubusercontent.com/10630464/135293253-1b9d5f56-1629-41be-88ff-ae7b4943092c.png)

### Environment
Environment: Linux
Stripe client version: 1.7.3

**Comment by pepin-stripe** [comment]
Hi @Ydrasil,

for a `balance.available` event to be triggered, we need to create a confirmed `payment_intent` so your account actually gets its balance updated and a `balance.available` event is triggered. 

When running `stripe trigger balance.available` it is expected that `stripe listen` would receive 4 events:
- `payment_intent.created`
- `payment_intent.succeeded`
- `charge.succeeded`
- `balance.avaiable`

Here is what I get when I run the command from my CLI (please note events order is not guaranteed):
```
--> charge.succeeded [evt_2JfWNp589O8KAxCG0xxxxxx]
--> payment_intent.succeeded [evt_2JfWNp589O8KAxCGxxxxxx]
--> payment_intent.created [evt_2JfWNp589O8KAxCxxxxxx]
--> balance.available [evt_2JfWNp589O8KAxCG0dxxxxxx]
```

I'm going to close this task, but please feel free to re-open if you are having trouble receiving all events as expected.

Cheers
Jon
