### ISSUE TITLE
"Invalid checkout.session id" when attempting to retrieve checkout session

### ISSUE THREAD

**Issue by AlexArendsen** [stripe/stripe-cli#761]
### Issue
After logging in, I run the following command

```
stripe checkout sessions retrieve ${SESSION_ID}
```

and get the following error:

```
{
  "error": {
    "message": "Invalid checkout.session id: ${SESSION_ID}",
    "type": "invalid_request_error"
  }
}
```

I attempt to fetch the session using cURL as well, but get the same result.

### Expected Behavior

I receive the session info, per these docs: https://stripe.com/docs/api/checkout/sessions/retrieve?lang=curl

### Steps to reproduce

1. Create a checkout session using API version `2020-08-27` and snag the checkout session ID.
2. `stripe login`
3. `stripe checkout sessions retrieve ${SESSION_ID}`

### Traceback

```
{
  "error": {
    "message": "Invalid checkout.session id: ${SESSION_ID}",
    "type": "invalid_request_error"
  }
}
```

### Environment

WSL

`Linux ${HOSTNAME} 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pepin-stripe** [comment]
Doesn't seem like it's a CLI issue since you are having the same error using cURL, but let's try to understand what is happening.

How are you creating and retrieving the checkout session id in step 1?

**Comment by AlexArendsen** [comment]
Hi! Another part of our system is using the .NET SDK to create the session, following this example: <https://stripe.com/docs/billing/subscriptions/checkout#create-session> (second code block)

```csharp
// Set your secret key. Remember to switch to your live secret key in production.
// See your keys here: https://dashboard.stripe.com/apikeys
StripeConfiguration.ApiKey = "{{API_KEY}}";

// The price ID passed from the front end.
// You can extract the form value with the following:
//   var priceId = Request.Form["priceId"];
var priceId = "{{PRICE_ID}}";

var options = new SessionCreateOptions
{
  // See https://stripe.com/docs/api/checkout/sessions/create
  // for additional parameters to pass.
  // {CHECKOUT_SESSION_ID} is a string literal; do not change it!
  // the actual Session ID is returned in the query parameter when your customer
  // is redirected to the success page.
  SuccessUrl = "https://example.com/success.html?session_id={CHECKOUT_SESSION_ID}",
  CancelUrl = "https://example.com/canceled.html",
  PaymentMethodTypes = new List<string>
  {
    "card",
  },
  Mode = "subscription",
  LineItems = new List<SessionLineItemOptions>
  {
    new SessionLineItemOptions
    {
      Price = priceId,
      // For metered billing, do not pass quantity
      Quantity = 1,
    },
  },
};

var service = new SessionService();
var session = await service.CreateAsync(options);

// Redirect to the URL returned on the Checkout Session.
//   Response.Headers.Add("Location", session.Url);
//   return new StatusCodeResult(303);
```

**Comment by pepin-stripe** [comment]
Alright, thanks for sharing this. I'm going to do some internal research to understand better what could happend, in the meantime could you

1. Make sure you're using the same API key between your .NET call and the CLI/cURL call? You might be using different keys and/or doing the session create in testmode but doing the retrieval with a livemode api key
2. Could you share a session id that you created and can't retrieve (a test mode one)? That would allow me to look into it and see if I can figure out why it's not retrievable.

Thanks!

**Comment by AlexArendsen** [comment]
Sure thing!

Digging a bit deeper, when I run `stripe checkout sessions list` it turns out I do get a list of test sessions, which I'm able to `retrieve`. I believe the issue was that I was trying to retrieve a live session; when I used our live key using the `--api-key` command, I was able to successfully fetch the live session data. I think the primary confusion was that `stripe login` only authorizes you to retrieve data for test-mode data; an advisory when using the `login` command would probably help stave off similar confusion in the future.

With that, I think we're good to go! If there's any other info I can provide please let me know-- thanks!

**Comment by pepin-stripe** [comment]
Glad I could help - and thanks for sharing the confusion with `login` not being clear that it defaults to test data - will make a task internally!
