### ISSUE TITLE
Specify project name via environment variable

### ISSUE THREAD

**Issue by i-am-david-fernandez** [stripe/stripe-cli#763]
### Problem
_What are you trying to do?_

I would like to leverage the existing "project" configuration feature (i.e., config sections for different projects coupled with the `--project-name` option), but avoid having to use the commandline option with every command. In particular, I'd like to leverage other tools (i.e., `direnv`) to manage the setting of the project, and have the stripe tool "just work" according to the environment.

### Feature
_What would help you accomplish your original task_

The tool currently supports setting the API key and/or the device name via environment variables (e.g., `STRIPE_API_KEY`). It also supports grouping configuration items into projects via the sections in the config file and associated use of the `--project-name` option. It would be useful if the project name could be specified as an environment variable.

### Examples
_Any example interaction you expect_

`$ export STRIPE_PROJECT_NAME=my-project`
then
`$ stripe something something`
would be equivalent to
`$ stripe --project-name my-project something something`

Using the `--project-name` option should override the environment variable, if so set.

**Comment by CillianFn** [comment]
@pepin-stripe Can I pick this up?
