### ISSUE TITLE
Trigger payment for a given customer

### ISSUE THREAD

**Issue by simon-tannai** [stripe/stripe-cli#773]
Hello ! 

I'm trying to test payment's event for a given customer from my Stripe test environment.
According to the documentation, I'm using the `trigger` command:
`stripe trigger payment_intent.payment_failed --add customer:id=cus_xxxxxxxxxxxx`.

The command response from my terminal:
```
⣻ Checking for new versions... Setting up fixture for: payment_intent
Running fixture for: payment_intent
Trigger succeeded! Check dashboard for event details.
```

But, from my Node.js webhook server, the given Customer ID does not exists into the Stripe's Event data:
```typescript
async function managePaymentFailed(stripeEvent: Stripe.Event): Promise<void> {
  console.log(`stripeEvent: ${JSON.stringify(stripeEvent, null, 2)}`);
}
```
The `console.log` output:
```javascript
{
  [...]
  "created": 1635517872,
  "data": {
    "object": {
      [...]
      "cancellation_reason": null,
      "capture_method": "automatic",
      "charges": {
        "object": "list",
        "data": [
          {
            [...],
            "captured": false,
            "created": 1635517871,
            "currency": "usd",
            "customer": null,
            "description": "(created by Stripe CLI)",
            "destination": null,
            [...]
          }
        ],
        [...]
      },
      [...]
      "confirmation_method": "automatic",
      "created": 1635517871,
      "currency": "usd",
      "customer": null,
      "description": "(created by Stripe CLI)",
      "invoice": null,
      "last_payment_error": {
        "doc_url": "https://stripe.com/docs/error-codes/card-declined",
        "message": "Your card was declined.",
        "payment_method": {
          [...]
          "created": 1635517871,
          "customer": null,
          "livemode": false,
          "metadata": {},
          "type": "card"
        },
        "type": "card_error"
      },
      [...]
    }
  },
  [...]
  "type": "payment_intent.payment_failed"
}
```

The `customer` field is always `null`.

How can I do it ?

**Comment by pepin-stripe** [comment]
Hi @simon-tannai,

Sorry the docs were not clear. The "param" the docs mention is the name of the fixture/resource you want to modify, so your call should be:

`stripe trigger payment_intent.payment_failed --add payment_intent:customer=cus_xxxxxxxxxxxx`

Because the `payment_intent` object takes a param `customer` which is the id of the customer.

Can you please try that and let me know if this works?

I've filed a task on our end to update the docs for this.

**Comment by simon-tannai** [comment]
Many thanks @pepin-stripe, it's working !

**Comment by LucasLaurens** [comment]
Hello, I think I still don't quite understand how this works. I've tried to follow the order below, but the information isn't right. The customer I specified subscribed for 5000 cents, however the invoice price in this targeted event is 2000 cents. Why does the Webhook set default values without taking my customer's values into account? 

```bash
tripe trigger invoice.payment_succeeded --add invoice:customer={CUSTOMER_ID}
```
