### ISSUE TITLE
support for charge.refund.updated

### ISSUE THREAD

**Issue by astears** [stripe/stripe-cli#828]
### Problem
Trying to test charge.refund.updated webhooks with the CLI but it is not supported as of now.

### Feature
Support for charge.refund.updated events in the CLI. Providing a way to specify the paymentIntent_id would be ideal.

**Comment by ianjabour-stripe** [comment]
Once #830 is merged you should also be able to use the `--skip / --add / --remove` flags on `stripe trigger` as well to accomplish the same effect provided you have the id of a confirmed payment intent:

```bash
stripe trigger charge.refund.updated \
  --skip charge \
  --remove refund:charge \
  --add refund:payment_intent=pi_xxx
```

**Comment by gd08xxx** [comment]
How to test a charge.refund.updated with a status of refund failed with paymentIntentId?
