### ISSUE TITLE
Support printing the completion file to stdout

### ISSUE THREAD

**Issue by chloe-the-catgirl** [stripe/stripe-cli#829]
### Problem
I'm am managing my dotfiles and my ZSH configuration across different devices through _chezmoi_.
One part of this is the generation of autocompletion scripts dynamically, like here for chezmoi: https://github.com/chloe-the-catgirl/dotfiles/blob/main/private_dot_config/zsh/suggestions/chezmoi.zsh

There are other examples in the same folder for different tools. The Stripe CLI however only writes the completion file. In case of an update, the completions are out of date.

### Feature
If the CLI could write the shell completion script to stdout, this would not be an issue anymore.

### Examples

How I'd like to see the integration.

```shell
# Autocompletion for stripe
#
if [ $commands[stripe] ]; then
  source <(stripe completion --shell zsh --write-to-stdout)
fi
```

Optionally, the `--write-to-stdout` parameter could be optional in case no TTY is attached.

**Comment by ianjabour-stripe** [comment]
👋  @chloe-the-catgirl , thank you for filing this issue!

I've created a PR which should resolve this for you once it gets merged / deployed:
https://github.com/stripe/stripe-cli/pull/831
