### ISSUE TITLE
unknown flag: --payment_intent

### ISSUE THREAD

**Issue by iabduul7** [stripe/stripe-cli#833]
### Issue
while calling `stripe refunds create` it says **One of the following params should be provided for this request: payment_intent or charge.**. The focus is on `payment_intent` keyword, if I call `--help` flag, the correct parameter is `payment-intent` i.e. with hypen not underscore. 
It is just the typo which cause confusion.

### Environment
Windows

**Comment by cjavilla-stripe** [comment]
Thanks for the comment. When passing flags, all underscores in snake-cased API request arguments are converted to kebab-case with hyphens. 

In this case, e.g. `--payment-method pm_card_visa`. 

When using the -d flag and specifying the key value pair, then the argument name is still snake cased. E.g.: `-d "payment_method=pm_card_visa"`

We'd be happy to chat further over on discord.gg/stripe.
