### ISSUE TITLE
stripe get doesn't support --project-name

### ISSUE THREAD

**Issue by jwheare** [stripe/stripe-cli#84]
The command only works when there's a [default] project. Using `--project-name` to choose a project produces this:

```API key is too short, must be at least 12 characters long```

**Comment by tomer-stripe** [comment]
Thanks! I'll take a look

**Comment by JNaeemGitonga** [comment]
Seems like this is still an issue; I am getting the same error after having used the `--project-name` flag. Any help? Thanks!
