### ISSUE TITLE
"Failed to connect to Stripe" when running "stripe listen"

### ISSUE THREAD

**Issue by peterb0yd** [stripe/stripe-cli#851]
### Issue
After following the instructions to run stripe webhooks locally, I'm not able to get past "Getting ready...". I'm not behind a company firewall or proxy.

instructions I followed: https://stripe.com/docs/stripe-cli

### Expected Behavior
It should start listening for events that get triggered via `stripe trigger payment_intent.succeeded` as mentioned in the instructions

### Steps to reproduce
1. Download stripe-cli via homebrew [link](https://stripe.com/docs/stripe-cli#login-account)
2. `brew install stripe/stripe-cli/stripe`
3. login in terminal via `stripe login`
4. run local webhook express server file (named `server.js`) using the example code via `node server.js`
5. run stripe listen command using `stripe listen --forward-to localhost:4242/webhook` (I added `--log-level=debug` to show the issue that's happening)

### Traceback
```
stripe listen --forward-to localhost:8080/webhooks/stripe --log-level=debug 

⣾ Getting ready... [Wed, 13 Apr 2022 15:35:03 PDT] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣯ Getting ready... [Wed, 13 Apr 2022 15:35:14 PDT] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe default_version=2020-08-27 display_connect_filter_warning=false latest_version=2020-08-27 reconnect_delay=248 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{5086}_O2nivhb4Ef3xOeEg8lMlCMPl0uOY3AloXNXYOsJ8Rp3Pf1QnHW websocket_url=wss://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT
[Wed, 13 Apr 2022 15:35:14 PDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Wed, 13 Apr 2022 15:35:14 PDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT?websocket_feature=webhook-payloads
⣽ Getting ready... [Wed, 13 Apr 2022 15:35:24 PDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout message=
[Wed, 13 Apr 2022 15:35:24 PDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
⢿ Getting ready... [Wed, 13 Apr 2022 15:35:34 PDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT?websocket_feature=webhook-payloads
⣟ Getting ready... ^C[Wed, 13 Apr 2022 15:35:36 PDT] DEBUG proxy.Proxy.Run: Ctrl+C received, cleaning up...
[Wed, 13 Apr 2022 15:35:36 PDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: operation was canceled message=
[Wed, 13 Apr 2022 15:35:36 PDT] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...
[Wed, 13 Apr 2022 15:35:36 PDT] DEBUG websocket.Client.connect: Dialing websocket url=wss://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT?websocket_feature=webhook-payloads
[Wed, 13 Apr 2022 15:35:36 PDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: operation was canceled message=
```

### Environment
macOS - m1 chip

**Comment by tomer-stripe** [comment]
Hey @peterb0yd! This is interesting, not sure I've seen this before. Just tested on my side and everything's working for me locally so nothing seems to be out of order.

What version of the CLI are you running? Also, did the `stripe trigger` command work for you? (Similarly does `stripe customers create` succeed?)

**Comment by peterb0yd** [comment]
Hey thanks for the quick reply.

I'm using stripe version 1.8.6

`stripe trigger` does work. 

`stripe customers create` seemed to work:

```
> stripe customers create
{
  "id": "cus_LVFi6Bp8KAxqG1",
  "object": "customer",
  "address": null,
  "balance": 0,
  "created": 1649890957,
  "currency": null,
  "default_source": null,
  "delinquent": false,
  "description": null,
  "discount": null,
  "email": null,
  "invoice_prefix": "AAD3EF22",
  "invoice_settings": {
    "custom_fields": null,
    "default_payment_method": null,
    "footer": null
  },
  "livemode": false,
  "metadata": {
  },
  "name": null,
  "next_invoice_sequence": 1,
  "phone": null,
  "preferred_locales": [

  ],
  "shipping": null,
  "tax_exempt": "none",
  "test_clock": null
}
```

**Comment by tomer-stripe** [comment]
Hmmm so no issues connecting with Stripe itself. I've not used these before but I'm wondering if they work for you?
* https://websocketstest.com/
* https://www.piesocket.com/websocket-tester

I'm trying to see if something on your side is interrupting the connection or of it's something on us. Also could you try running with `--no-wss` and see if that works?

**Comment by peterb0yd** [comment]
Hmm, websockets do work:

<img width="505" alt="Screen Shot 2022-04-13 at 4 29 32 PM" src="https://user-images.githubusercontent.com/5799574/163286132-a59dd736-295b-4b64-86b1-2b8697ea53f3.png">
<img width="979" alt="Screen Shot 2022-04-13 at 4 29 58 PM" src="https://user-images.githubusercontent.com/5799574/163286182-ca060678-b58c-4bb5-8c33-ac5d6dc10421.png">

```
> stripe listen --no-wss --log-level=debug
⣟ Checking for new versions... [Wed, 13 Apr 2022 16:28:52 PDT] DEBUG Error while sending telemetry data: Post "https://r.stripe.com/0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

⣾ Getting ready... [Wed, 13 Apr 2022 16:28:59 PDT] DEBUG stripeauth.client.Authorize: Authenticating with Stripe...
⣯ Getting ready... [Wed, 13 Apr 2022 16:29:10 PDT] DEBUG stripeauth.Client.Authorize: Got successful response from Stripe default_version=2020-08-27 display_connect_filter_warning=false latest_version=2020-08-27 reconnect_delay=231 websocket_authorized_feature=webhook-payloads websocket_id=cliws_{22078}_yiPyo7BCOuLNHq9nZIL0I3dMrKVneV4gW4o3F6afTSaiQeStKA websocket_url=wss://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT
[Wed, 13 Apr 2022 16:29:10 PDT] DEBUG websocket.client.Run: Attempting to connect to Stripe
[Wed, 13 Apr 2022 16:29:10 PDT] DEBUG websocket.Client.connect: Dialing websocket url=ws://stripe-cli.stripe.com/subscribe/acct_1KUgMLJYMOMTx4nT?websocket_feature=webhook-payloads
⡿ Getting ready... [Wed, 13 Apr 2022 16:29:13 PDT] DEBUG Error while sending telemetry data: Post "https://r.stripe.com/0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

⣽ Getting ready... [Wed, 13 Apr 2022 16:29:20 PDT] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout message=
```

Same issue unfortunately ☹️

**Comment by peterb0yd** [comment]
hey so I tried these same steps on my mac mini at home without any issues. I have a feeling I may just need to run `homebrew upgrade` on my macbook and then re-install the stripe-cli. I'll give a shot and see if it works tomorrow.

**Comment by tomer-stripe** [comment]
Huh, weird! Alright, let me know if that works

**Comment by charliecruzan-stripe** [comment]
hey @peterb0yd - just wanted to check in and see if `brew upgrade` ended up solving things for you? Let me know, and if not we can try and troubleshoot this further!

**Comment by peterb0yd** [comment]
Thanks for following up.

It was kinda weird. It only caused issues on my work WiFi and only after the first attempt. When I switch Wifi from 2.4ghz to 5ghz or vice-versa, it works on the first try. If I disconnect and retry, it fails with the above error so I have to switch networks and re-run the command.

It wasn't a big deal however cuz I can only test payments on production. We're connecting bank accounts with Plaid so we can't login to a Plaid dev bank account using Stripe in dev cuz Plaid always uses real bank accounts in dev. It's a pain but w/e.

**Comment by charliecruzan-stripe** [comment]
Ah, I see, that is super weird though that it'll work when you switch networks...not sure what would cause that 🤔 especially since you said there's no company firewall

In the meantime it doesn't look like there's something actionable for us to do right now, so I'll close this issue, but feel free to follow up here with us if you learn more or if the problem gets worse/more annoying!

**Comment by RobSchilderr** [comment]
> 

Just experienced exactly the same issue. On my WiFi the results of debugging gives me:

`⡿ Getting ready... [Wed, 27 Apr 2022 13:45:16 IST] DEBUG websocket.Client.connect: Websocket connection error error=dial tcp: i/o timeout message=
[Wed, 27 Apr 2022 13:45:16 IST] DEBUG websocket.client.Run: Failed to connect to Stripe. Retrying...`

Yet, on a 3G/4G connection I seem to have no issues. Also using macOS - m1 chip.

**Comment by ishan-eventrac** [comment]
I'm having same problem. Command `stripe listen --forward-connect-to ...` gets stuck at `⣻ Getting ready...` screen. However same command seems to work before I upgraded stripe CLI last week.

Stripe version:
```bash
> stripe --version
stripe version 1.12.3
```

I'm using Mac M1. 

PS. I also tried reinstalling CLI but no luck.

**Comment by ishan-eventrac** [comment]
It works if I use VPN! ¯\\_(ツ)_/¯

**Comment by epelc** [comment]
I just upgraded and ran into this problem. It use to work a few weeks ago on same network/setup.

Tried disabling telemetry via `STRIPE_CLI_TELEMETRY_OPTOUT=1` but still get `tripecli-ws-nw.stripe.com: i/o timeout`

**Comment by Susros** [comment]
Having the same issue on M1 chip x(

**Comment by Susros** [comment]
Oh! It works after I cleared my network DNS.

**Comment by mngarwood** [comment]
I just experienced this issue on my M1 Mac and burned about 3 hours troubleshooting it 😅

Same as a lot of the previous comments here: websockets worked fine in general, no connection issues to other services. --no-wss did not help, clearing my network DNS did not help, adding new DNS servers to my WiFi router did not help...BUT I was able to get stripe listen up and running by adding Cloudflare's DNS server (1.1.1.1) directly to my DNS settings for my WiFi connection in System Preferences > Network > WiFi > Advanced > DNS. 

There seem to be several people experiencing this issue - found the fix that finally worked in recent comments on an old closed issue #359 .

**Comment by wass08** [comment]
> I just experienced this issue on my M1 Mac and burned about 3 hours troubleshooting it 😅
> 
> Same as a lot of the previous comments here: websockets worked fine in general, no connection issues to other services. --no-wss did not help, clearing my network DNS did not help, adding new DNS servers to my WiFi router did not help...BUT I was able to get stripe listen up and running by adding Cloudflare's DNS server (1.1.1.1) directly to my DNS settings for my WiFi connection in System Preferences > Network > WiFi > Advanced > DNS.
> 
> There seem to be several people experiencing this issue - found the fix that finally worked in recent comments on an old closed issue #359 .

You saved my day, thank you!

**Comment by mreddimasi** [comment]
Facing the same issue on Ubuntu with the stripe-cli 1.18.0. Following the suggestion by @wass08 changed the /etc/resolv.conf nameserver to 8.8.8.8
Stripe cli was then able to connect, login and receive the ping/pong messages

**Comment by SwapnilSonker** [comment]
just refer to 
[(https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10)]
 this article your problem will be immediately solved, it's just a matter of networking issues, nothing else to panic for...

**Comment by SwapnilSonker** [comment]
[](https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10)
