### ISSUE TITLE
Is there a way to pass metadata into stripe trigger checkout.session.completed?

### ISSUE THREAD

**Issue by shaynekasai** [stripe/stripe-cli#864]
Hello there, from my understanding, metadata is a field that can contain key/value pairs and passed through into  payment link create (https://stripe.com/docs/api/payment_links/payment_links/object)

As such, I'm using the checkout process and at the end it triggers checkout.session.completed. I would like to test it with the CLI but my flow is using the metadata, how do I pass it in via the CLI?

From the CLI documentation I can see that I can use --add but I'm unsure what the correct combination is. eg. `stripe trigger checkout.session.completed --add checkout:metadata.foo=1` and the payment yields no metadata

Any thoughts on this? Thanks!

**Comment by jdheywood** [comment]
Hey did you get a solution to this?

**Comment by jdheywood** [comment]
For reference:

Courtesy of this page: https://queen.raae.codes/emails/2022-06-03-stripe-cli/ (thank you [@queen-raae](https://github.com/queen-raae))

```
stripe trigger checkout.session.completed --override checkout_session:metadata.foo=bar
```

**Comment by a-toms** [comment]
Thanks @queen-raae and @jdheywood. The info is missing from the Stripe docs.

**Comment by DoneDeal0** [comment]
Would you know how to add a customer email to the cli command? I've tried `stripe trigger checkout.session.completed --override "customer_email:hello@world.com"` and many other options, but it fails.

**Comment by gysenlionel** [comment]
You can use this to add Stripe trigger checkout.session.completed --add checkout_session:metadata[userId]=1 
see the doc https://stripe.com/docs/cli/trigger
