### ISSUE TITLE
Local listener URL not triggering full webhook URL in Stripe CLI 

### ISSUE THREAD

**Issue by stell** [stripe/stripe-cli#865]
### Issue
When forwarding a local URL via Stripe CLI like this:

stripe listen --forward-to http://localhost:44383/myapp/index.php?option=app1&task=stripe_webhook --latest

in https://dashboard.stripe.com/test/webhooks i see the URL without parameters http://localhost:44383/myapp/index.php?option=app1

**The task parameter is lost.**

When triggering like this:

```
stripe trigger payment_intent.created
Setting up fixture for: payment_intent
Running fixture for: payment_intent
Trigger succeeded! Check dashboard for event details.
```

the listener tells:

```
> Ready! You are using Stripe API Version [2020-08-27]. Your webhook signing secret is ________________________________________
2022-05-06 15:31:18   --> payment_intent.created [evt___________________]
2022-05-06 15:31:18  <--  [404] POST http://localhost:44383/myapp/index.php?option=app1 [evt___________________]
```

I tried encoding the URL in different ways without success.

When creating the same POST call in Postman evereything works fine.

I'm using the latest CLI v1.8.11

Any ideas?

### Expected Behavior
Full URL should be triggered like in POSTMAN

### Environment
Windows

**Comment by sbkobaidze** [comment]
Any updates on this? I'm not receiving any request on my endpoint also

**Comment by yash22arora** [comment]
I am also not receiving any requests at my endpoint with Strupe CLI. When using cURL to send a mock request, everything is working. Any help?

**Comment by marklidnov84** [comment]
I am on a Windows machine. What worked for me was going to 
1. Windows Defender Firewall with Advanced Security
2. Inbound Rules (top left)
3. Then press "New Rule..." (top right)
4. Select Port
5. Select TCP
6. Select "Specific local ports". Here write down the port that you are running your server on. (3000, 30000, whatever it is)
7. Select "Allow the connection"
8. Leave all the rules applied
9. Then press next and give it a name

**Comment by e1016** [comment]
Just in case any other got on my error, the command `stripe listen --forward-to localhost:8888/my-webhook-endpoint` must be running meanwhile execute `stripe trigger [event]` *stripe trigger* send an event to *stripe listen* and finally *stripe listen* send this request to your localhost

**Comment by bookingwizard** [comment]
If you run 'stripe listen...' command in the terminal, you receive a message like `> Ready! You are using Stripe API Version [2025-02-24.acacia]. Your webhook signing secret is whsec_1e122... (^C to quit)`. 

If you want to listen for events then do not press ^C. Just open another terminal window and run `stripe trigger...`

**Comment by d4nbanan** [comment]
If you run 'stripe listen...' command in the terminal, you receive a message like > Ready! You are using Stripe API Version [2025-02-24.acacia]. Your webhook signing secret is whsec_1e122... (^C to quit).

If you want to listen for events then do not press ^C. Just open another terminal window and run stripe trigger...

**Comment by Mushaf-Hafeez** [comment]
> If you run 'stripe listen...' command in the terminal, you receive a message like > Ready! You are using Stripe API Version [2025-02-24.acacia]. Your webhook signing secret is whsec_1e122... (^C to quit).
> 
> If you want to listen for events then do not press ^C. Just open another terminal window and run stripe trigger...

Thanks, this works for me.
I am trying to solve but I could not find the solution. I searched on youtube, used chatGPT and ngrok. but doesn't work.
