### ISSUE TITLE
Typo in events resend documentation.

### ISSUE THREAD

**Issue by tsvillain** [stripe/stripe-cli#876]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
_I was trying to use `events resent` from Stripe CLI, in docs it's mentioned to add webhook endpoint use flag `--webhook_endpoint`_

### Expected Behavior
_Correct flag is `--webhook-endpoint` The only way I got to know this typo is after checking Stripe CLI code in this repo._

### Environment
_macOS_

I tried finding Docs to update it myself but I wasn't able to find one. Attaching the Screen of the Doc below: [Doc Link](https://stripe.com/docs/cli/events/resend)
![Screenshot 2022-05-25 at 10 02 55 AM](https://user-images.githubusercontent.com/42140007/170181894-cc2b9964-f386-45ea-a146-b68955576e01.png)

**Comment by tomer-stripe** [comment]
Hi! I believe this should be fixed now
