### ISSUE TITLE
Investigate golangci-lint resolution problem in test suite

### ISSUE THREAD

**Issue by suz-stripe** [stripe/stripe-cli#878]
### Issue
GitHub Action tests are failing intermittantly due to a golangci-linter installation problem.

### Expected Behavior
The golang-ci linter is successfully installed and run during each test suite run

### Steps to reproduce
Look in GitHub Action test suite failures.

### Traceback
```
curl -fsSL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.42.1
curl: (6) Could not resolve host: install.goreleaser.com
# TODO: fix disabled linter issues
./bin/golangci-lint run ./...
make: ./bin/golangci-lint: Command not found
make: *** [Makefile:39: lint] Error 127
```
### Environment
GitHub Actions

**Comment by vcheung-stripe** [comment]
Fixed: https://github.com/stripe/stripe-cli/pull/880
