### ISSUE TITLE
listen command with --load-from-webhooks-api does not work

### ISSUE THREAD

**Issue by morgoth** [stripe/stripe-cli#88]
If I understood docs correctly, when using `listen` command, I can specify `--load-from-webhooks-api` which will take all existing webhooks endpoints from existing Stripe test account (visible in dashboard) and will forward only those events that are used by those webhooks.

I have configured webhook in dashboard (pointing to our staging server).
When I use command: `stripe listen --load-from-webhooks-api --forward-to localhost:3000/webhook/stripe` I get error:
`You have not defined any webhook endpoints on your account. Go to the Stripe Dashboard to add some: https://dashboard.stripe.com/test/webhooks`

It's not clear to me if it's a bug or I am doing something wrong. Do you have any insights on this topic?
```
stripe -v
stripe version 0.2.7 (beta)
```

**Comment by tomer-stripe** [comment]
Sorry about that @morgoth! We'll dig into that.

**Comment by ob-stripe** [comment]
Hi @morgoth, can you confirm that the endpoints exist in test mode on your account?

**Comment by tomer-stripe** [comment]
Hey @morgoth, this should now be resolved in v0.3.0 -- let us know if you have any issues!

**Comment by morgoth** [comment]
Yes, looks like it is fine now. At least it starts.
Thank you for such quick fix.
