### ISSUE TITLE
W10 defender detects stripe_1.10.3_windows_x86_64.zip as a virus/trojan

### ISSUE THREAD

**Issue by ericuss** [stripe/stripe-cli#892]
I'm trying to download the stripe cli latest version, but w10/chrome detects the zip as a virus/trojan

### Issue
Trying to download the file [stripe_1.10.3_windows_x86_64.zip](https://github.com/stripe/stripe-cli/releases/download/v1.10.3/stripe_1.10.3_windows_x86_64.zip)

![image](https://user-images.githubusercontent.com/4225477/172818198-0d39cf9b-ef04-4557-b308-e7af4596c370.png)
![image](https://user-images.githubusercontent.com/4225477/172833606-7cd347df-83ff-4ef5-846d-9383a4a2149f.png)

### Expected Behavior
Not detects anything 

### Environment
Windows 10 and Chrome

**Comment by gracegoo-stripe** [comment]
Thank you for reporting @ericuss! Unfortunately, this is an issue currently out of our control: https://go.dev/doc/faq#virus. Here is a tracking issue: https://github.com/stripe/stripe-cli/issues/692

I'll look into submitting a report for analysis again. Meanwhile closing this as a duplicate. Feel free to re-open if you have any other comments or add it directly to the tracking issue
