### ISSUE TITLE
trigger fails to add metadata to payment_method.attached

### ISSUE THREAD

**Issue by eladchen** [stripe/stripe-cli#898]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
Trying to add a metadata property using trigger command

### Expected Behavior
An event should have been triggered with the "v3" property

### Steps to reproduce
> stripe trigger payment_method.attached --add "payment_method:metadata[v3]=true"

### Traceback
Setting up fixture for: customer
Running fixture for: customer
Setting up fixture for: payment_method_attach
Running fixture for: payment_method_attach
Trigger succeeded! Check dashboard for event details.

### Environment
macOS, stripe cli version 1.10.3

**Comment by gracegoo-stripe** [comment]
Hi @eladchen, the fixture name is [payment_method_attach](https://github.com/stripe/stripe-cli/blob/541d218a6f5da8884352f66950914416302ee54a/pkg/fixtures/triggers/payment_method.attached.json#L15)  so you'd want to run `stripe trigger payment_method.attached --add "payment_method_attach:metadata[v3]=true"`

However, when I tried this out I got this error from the API: 
```
Trigger failed: Request failed, status=400, body={
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: metadata",
    "param": "metadata",
    "type": "invalid_request_error"
  }
}
```
From reading the [metadata section on](https://stripe.com/docs/api/metadata) the API Ref, I don't think that `metadata` is supported for Payment Methods.

I was able to see the metadata in the event triggered for the Charge object which is listed as one of the objects that support metadata
```
stripe trigger charge.succeeded --add "charge:metadata[v3]=true"
```

**Comment by gracegoo-stripe** [comment]
Going to close this one out but please feel free to re-open if you have any other questions!
