### ISSUE TITLE
Getting invalid_request_error / resource_missing when resource is clearly there

### ISSUE THREAD

**Issue by tamoyal** [stripe/stripe-cli#923]
I'm trying to resend an event to a webhook. The command looks like:

```
stripe events resend evt_xxx--live --webhook-endpoint=we_xxx --log-level debug
```

The response I get is:

```
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such notification: 'evt_xxx",
    "param": "id",
    "type": "invalid_request_error"
  }
}
```

But I'm copying the event ID directly from the browser where I am viewing the event in the dashboard so I don't understand how it can not exist. I also verified the account ID is correct (this event should not belong to another account).

Are there any other issues that could cause this not to work?

**Comment by tomer-stripe** [comment]
Hey @tamoyal! Could you share the event id and webhook endpoint id? That'll allow us to check out what's happening on our side (the ids aren't sensitive data and can be shared publicly, but if you prefer you can email them to me too, tomer@stripe)

**Comment by tamoyal** [comment]
@tomer-stripe No problem, `evt_1LBn1rKVzSTS7UqEsieWroFm` and `we_1JnBI6KVzSTS7UqEvePo5RIY`

**Comment by tomer-stripe** [comment]
Thanks! Asking the team if they can see what's happening

**Comment by tomer-stripe** [comment]
@tamoyal so the team said the event itself is over 30 days old and we can't retry events over 30 days. The dashboard is loading an archived version of the event's data for viewing but we can't perform any operations on the event itself. Sorry about the trouble there!

I'll file some asks on team to update the documentation and messaging there so it's clearer in the future.
