### ISSUE TITLE
stripe trigger checkout.session.completed | Trigger failed | error message You cannot use `line_items.amount`, `line_items.currency` ...

### ISSUE THREAD

**Issue by ashen780** [stripe/stripe-cli#947]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
_Describe what happened and what you were trying to do_
 I was trying to test webhook events locally by triggering the checkout event by stripe CLI
### Expected Behavior
_Tell us what you expected to happen_

`stripe trigger checkout.session.completed` this should trigger checkout session completed event

### Steps to reproduce
_What are the steps we can take to reproduce this and verify it's fixed?_

`stripe trigger checkout.session.completed` this should trigger checkout session completed event without any errors

### Traceback
_Share any debug output that was given by the CLI_

`Setting up fixture for: checkout_session
Running fixture for: checkout_session
Trigger failed: Request failed, status=400, body={
  "error": {
    "message": "You cannot use `line_items.amount`, `line_items.currency`, `line_items.name`, `line_items.description`, or `line_items.images` in this API version. Please use `line_items.price` or `line_items.price_data`. Please see https://stripe.com/docs/payments/checkout/migrating-prices for more information.",
    "type": "invalid_request_error"
  }
}`

### Environment
_Select one of: macOS, Linux, Windows, Other_
Windows , stripe version 1.11.0

**Comment by etsai-stripe** [comment]
@ashen780 this issue has been addressed in the latest 1.11.1 release. thanks for reporting!
