### ISSUE TITLE
Allow card information to be passed into auth webhook using --override

### ISSUE THREAD

**Issue by sctowne1** [stripe/stripe-cli#948]
### Problem
_What are you trying to do?_
I am trying to test the issuing_authorization.request webhook using a specific stripe card. Currently any attempt to do this via the override command gives the following error: 

`"A parameter provided in the URL (card) was repeated as a GET or POST parameter. You can only provide this information as a portion of the URL."`

### Feature
_What would help you accomplish your original task_
Our system checks the card ID in the auth to fetch a user in our system, so to successfully test the system it is required that we know the card ID ahead of time, or are able to pass it in to the auth command.

### Examples
_Any example interaction you expect_
`stripe trigger issuing_authorization.request --stripe-account acct_1L1dQiR3aspVTJoe --override authorization_request:card="ic_1Kv4FiJcIAKVEIOPlsALq99q"`

**Comment by etsai-stripe** [comment]
@sctowne1  have you tried the `--add` flag? you can add new parameters to the fixture by using `-add` or `--remove` to remove

**Comment by sctowne1** [comment]
@etsai-stripe That does now work either unfortunately. Per a conversation in the Discord with Stripe Moderator koopajah:

> We don't yet support overrides on the URL path parameter and right now the card id goes here: https://github.com/stripe/stripe-cli/blob/master/pkg/fixtures/triggers/issuing_authorization.request.json#L37

**Comment by etsai-stripe** [comment]
@sctowne1 ah i see! i will add this to our feature backlog. thanks!

**Comment by etsai-stripe** [comment]
@sctowne1 have you also tried `--raw` flag?
its basically passing in the whole fixture file in a string format. ie. remove the original `card` section in the fixture, and replace the `card:id` with your card id

**Comment by sctowne1** [comment]
@etsai-stripe could you provide an example command? I do not see any documentation on its usage

**Comment by etsai-stripe** [comment]
@sctowne1 there isnt documentation because it was only design for vscode extension to use (when user customize their own fixtures through vscode extension)
but for a quick example you can do
```
$ stripe trigger - --raw '{"_meta": {"template_version": 0},"fixtures": [{"name": "customer","path": "/v1/customers","method": "post","params": {"description": "(created by Stripe CLI)"}}]}'
Setting up fixture for: customer
Running fixture for: customer
Trigger succeeded! Check dashboard for event details.
```

**Comment by sctowne1** [comment]
I keep getting an error saying that the issuing cardholder does not exist when i try to specify the required parameter cardholder. It also tells me "Received unknown parameter: id" when I try to specify the card id.

```
stripe trigger - --raw '
{"_meta":
  {"template_version": 0},
  "fixtures": [{
    "name": "card",
    "path": "/v1/issuing/cards",
    "method": "post",
    "params": {
      "currency": "USD",
      "cancellation_reason": null,
      "type": "virtual", 
      "id": "ic_1LcWIuR4sTLeLkjx5TcI59d6",
      "cardholder": "ich_1LcWItR4sTLeLkjxPiwt0FXQ"
    }
  }]
}'

```

**Comment by etsai-stripe** [comment]
i think `id` is not part of the update issuing card params?
https://stripe.com/docs/api/issuing/cards/update

by the way, i found docs for creating your own fixture using a file path to a json: https://stripe.com/docs/cli/fixtures

**Comment by sctowne1** [comment]
> i think `id` is not part of the update issuing card params? https://stripe.com/docs/api/issuing/cards/update
> 
> by the way, i found docs for creating your own fixture using a file path to a json: https://stripe.com/docs/cli/fixtures

The discord was able to help me out.

The correct command was 
```stripe trigger --stripe-account "acct_1LcWFtR4sTLeLkjx" - --raw '
{"_meta": 
 {"template_version": 0}, 
 "fixtures": [{
   "name": "authorization_request",
   "path": "/v1/issuing/cards/ic_1LcWIuR4sTLeLkjx5TcI59d6/test/authorizations",
   "method": "post",
   "params": {
     "held_amount": 100,
     "authorization_method": "online"
    }
  }]
}'```

**Comment by etsai-stripe** [comment]
@sctowne1  glad you got it figured out!
