### ISSUE TITLE
Stripe CLI fixtures with array indexing don't work as expected. 

### ISSUE THREAD

**Issue by m1dnight** [stripe/stripe-cli#962]
_The more information we have the easier it is for us to help. Feel free to remove any sections that might not apply_

### Issue
Some fixtures return a list of values. An example of such a request is the `/v1/customers/search` path. 
If one wants to use one of the values in a list, the documentation states the `.[n]` notation should be used, but this does not work. Instead, the `.n.` notation should be used. I am unsure what the correct behavior would be, hence this issue.

The documentation (https://stripe.com/docs/cli/fixtures) states the following:

> Use {cus_jenny_rosen:subscriptions.data.[0].id} to access data within a list.

### Expected Behavior
It would makes sense to me that the bracket syntax indexes in an array, while the .n syntax gets a property with the name n.

So, given a response from fixture `some_fixture`:

```json
{
  "data": [
    {
      "id": "cus_123"
    },
    {
      "id": "cus_456"
    }
  ], 
  "0": "some value"
}
```

The fixture queries should return the following.

 * `${some_fixture:data}` = `[{"id": "cus_123"}, {"id": "cus_456"}]`
 * `${some_fixture:data.[0]}` = `{"id": "cus_123"}`
 * `${some_fixture:data.[1]}` = `{"id": "cus_456"}`
 * `${some_fixture:data.0}` = `"some value"`

### Steps to reproduce
I have used this fixture below to search for a user. In my test environment I was certain I would get exactly a single user.

```json
{
  "_meta": {
    "template_version": 0
  },
  "fixtures": [
    {
      "name": "find_the_customer",
      "path": "/v1/customers/search",
      "method": "get",
      "params": {
        "query": "metadata['auth0id']:'supersecret'"
      }
    },
    {
      "name": "customer_updated",
      "path": "/v1/customers/${find_the_customer:data.0.id}",
      "method": "post",
      "params": {
        "metadata": {
          "foo": "this is value is updated via the fixture"
        }
      }
    }
  ]
}
```

Notice that the query in the second request is `find_the_customer:data.0.id}`. 
When I try the same fixture but with `${find_the_customer:data.[0].id|novalue}` the result is `novalue`.
When I use `${find_the_customer:data.[0]}`, or `${find_the_customer:data.[0].[0]}`, and so on , I get the original list, i.e., the same value as `${find_the_customer:data}`.

### Environment
MacOS 12.5, Stripe version 1.11.3.

I have already built a test case that shows the expected behavior using the .n syntax. You can see that here: https://github.com/m1dnight/stripe-cli/commit/d7ac0aa604a11717e6385ab324521441a93bfddc

**Comment by etsai-stripe** [comment]
@m1dnight 
unfortunately, the index access is a change by the [tidwall/gjson](https://github.com/tidwall/gjson) golang package
i will update the fixture doc to reflect this change!

```
result.Type           // can be String, Number, True, False, Null, or JSON
result.Str            // holds the string
result.Num            // holds the float64 number
result.Raw            // holds the raw json
result.Index          // index of raw value in original json, zero means index unknown
result.Indexes        // indexes of all the elements that match on a path containing the '#' query character.
```

thank you for catching the discrepancy and putting the test case
i will put in the test case to catch any future changes to the access pattern
